<!DOCTYPE html>
<html lang="es" xml:lang="es">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 2 Estadística inferencial | Análisis de la severidad motora en la enfermedad de Parkinson mediante características acústicas de telemonitoreo</title>
  <meta name="description" content="Análisis exploratorio e inferencial del conjunto de datos Parkinsons Telemonitoring (UCI): relación entre características demográficas, temporales y acústicas de la voz y la severidad motora (motor_UPDRS). Trabajo del curso Métodos Estadísticos, Universidad del Norte." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 2 Estadística inferencial | Análisis de la severidad motora en la enfermedad de Parkinson mediante características acústicas de telemonitoreo" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Análisis exploratorio e inferencial del conjunto de datos Parkinsons Telemonitoring (UCI): relación entre características demográficas, temporales y acústicas de la voz y la severidad motora (motor_UPDRS). Trabajo del curso Métodos Estadísticos, Universidad del Norte." />
  <meta name="github-repo" content="DiegoxorG/libro_met_est" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 2 Estadística inferencial | Análisis de la severidad motora en la enfermedad de Parkinson mediante características acústicas de telemonitoreo" />
  
  <meta name="twitter:description" content="Análisis exploratorio e inferencial del conjunto de datos Parkinsons Telemonitoring (UCI): relación entre características demográficas, temporales y acústicas de la voz y la severidad motora (motor_UPDRS). Trabajo del curso Métodos Estadísticos, Universidad del Norte." />
  

<meta name="author" content="Diego Payares &amp; Salma Romero" />


<meta name="date" content="2026-09-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>
<link rel="next" href="conclusiones.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Parkinson y telemonitoreo de la voz</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Contexto del problema</a></li>
<li class="chapter" data-level="" data-path="objetivo-general.html"><a href="objetivo-general.html"><i class="fa fa-check"></i>Objetivo general</a></li>
<li class="chapter" data-level="" data-path="objetivos-específicos.html"><a href="objetivos-específicos.html"><i class="fa fa-check"></i>Objetivos específicos</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> EDA</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#an%C3%A1lisis-exploratorio-de-motor_updrs"><i class="fa fa-check"></i><b>1.1</b> Análisis exploratorio de <code>motor_UPDRS</code></a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="intro.html"><a href="intro.html#resumen-estad%C3%ADstico"><i class="fa fa-check"></i><b>1.1.1</b> Resumen estadístico</a></li>
<li class="chapter" data-level="1.1.2" data-path="intro.html"><a href="intro.html#histograma"><i class="fa fa-check"></i><b>1.1.2</b> Histograma</a></li>
<li class="chapter" data-level="1.1.3" data-path="intro.html"><a href="intro.html#diagrama-de-caja"><i class="fa fa-check"></i><b>1.1.3</b> Diagrama de caja</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#caracterizaci%C3%B3n-de-las-variables-num%C3%A9ricas"><i class="fa fa-check"></i><b>1.2</b> Caracterización de las variables numéricas</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="intro.html"><a href="intro.html#resumen-estad%C3%ADstico-por-variable"><i class="fa fa-check"></i><b>1.2.1</b> Resumen estadístico por variable</a></li>
<li class="chapter" data-level="1.2.2" data-path="intro.html"><a href="intro.html#histogramas"><i class="fa fa-check"></i><b>1.2.2</b> Histogramas</a></li>
<li class="chapter" data-level="1.2.3" data-path="intro.html"><a href="intro.html#dispersi%C3%B3n-frente-a-motor_updrs"><i class="fa fa-check"></i><b>1.2.3</b> Dispersión frente a <code>motor_UPDRS</code></a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#caracterizaci%C3%B3n-de-la-variable-categ%C3%B3rica-sex"><i class="fa fa-check"></i><b>1.3</b> Caracterización de la variable categórica <code>sex</code></a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="intro.html"><a href="intro.html#distribuci%C3%B3n-por-registros-y-por-pacientes"><i class="fa fa-check"></i><b>1.3.1</b> Distribución por registros y por pacientes</a></li>
<li class="chapter" data-level="1.3.2" data-path="intro.html"><a href="intro.html#severidad-motora-seg%C3%BAn-el-sexo"><i class="fa fa-check"></i><b>1.3.2</b> Severidad motora según el sexo</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#relaciones-entre-las-variables-independientes-num%C3%A9ricas"><i class="fa fa-check"></i><b>1.4</b> Relaciones entre las variables independientes numéricas</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="intro.html"><a href="intro.html#pares-seleccionados"><i class="fa fa-check"></i><b>1.4.1</b> Pares seleccionados</a></li>
<li class="chapter" data-level="1.4.2" data-path="intro.html"><a href="intro.html#matriz-de-correlaciones"><i class="fa fa-check"></i><b>1.4.2</b> Matriz de correlaciones</a></li>
<li class="chapter" data-level="1.4.3" data-path="intro.html"><a href="intro.html#pares-m%C3%A1s-correlacionados"><i class="fa fa-check"></i><b>1.4.3</b> Pares más correlacionados</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#ingenier%C3%ADa-de-caracter%C3%ADsticas"><i class="fa fa-check"></i><b>1.5</b> Ingeniería de características</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="intro.html"><a href="intro.html#construcci%C3%B3n-de-los-%C3%ADndices"><i class="fa fa-check"></i><b>1.5.1</b> Construcción de los índices</a></li>
<li class="chapter" data-level="1.5.2" data-path="intro.html"><a href="intro.html#verificaci%C3%B3n-de-los-%C3%ADndices"><i class="fa fa-check"></i><b>1.5.2</b> Verificación de los índices</a></li>
<li class="chapter" data-level="1.5.3" data-path="intro.html"><a href="intro.html#descripci%C3%B3n-de-los-%C3%ADndices"><i class="fa fa-check"></i><b>1.5.3</b> Descripción de los índices</a></li>
<li class="chapter" data-level="1.5.4" data-path="intro.html"><a href="intro.html#relaci%C3%B3n-con-la-variable-respuesta"><i class="fa fa-check"></i><b>1.5.4</b> Relación con la variable respuesta</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="inferencial.html"><a href="inferencial.html"><i class="fa fa-check"></i><b>2</b> Estadística inferencial</a>
<ul>
<li class="chapter" data-level="2.1" data-path="inferencial.html"><a href="inferencial.html#unidad-de-an%C3%A1lisis-tabla-por-paciente"><i class="fa fa-check"></i><b>2.1</b> Unidad de análisis: tabla por paciente</a></li>
<li class="chapter" data-level="2.2" data-path="inferencial.html"><a href="inferencial.html#objetivo-1-severidad-motora-seg%C3%BAn-el-sexo"><i class="fa fa-check"></i><b>2.2</b> Objetivo 1: severidad motora según el sexo</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="inferencial.html"><a href="inferencial.html#an%C3%A1lisis-exploratorio"><i class="fa fa-check"></i><b>2.2.1</b> Análisis exploratorio</a></li>
<li class="chapter" data-level="2.2.2" data-path="inferencial.html"><a href="inferencial.html#supuesto-de-normalidad"><i class="fa fa-check"></i><b>2.2.2</b> Supuesto de normalidad</a></li>
<li class="chapter" data-level="2.2.3" data-path="inferencial.html"><a href="inferencial.html#supuesto-de-homocedasticidad"><i class="fa fa-check"></i><b>2.2.3</b> Supuesto de homocedasticidad</a></li>
<li class="chapter" data-level="2.2.4" data-path="inferencial.html"><a href="inferencial.html#prueba-de-hip%C3%B3tesis-t-de-student"><i class="fa fa-check"></i><b>2.2.4</b> Prueba de hipótesis: t de Student</a></li>
<li class="chapter" data-level="2.2.5" data-path="inferencial.html"><a href="inferencial.html#tama%C3%B1o-del-efecto"><i class="fa fa-check"></i><b>2.2.5</b> Tamaño del efecto</a></li>
<li class="chapter" data-level="2.2.6" data-path="inferencial.html"><a href="inferencial.html#conclusi%C3%B3n"><i class="fa fa-check"></i><b>2.2.6</b> Conclusión</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="inferencial.html"><a href="inferencial.html#objetivo-2-severidad-motora-seg%C3%BAn-el-grupo-de-edad"><i class="fa fa-check"></i><b>2.3</b> Objetivo 2: severidad motora según el grupo de edad</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="inferencial.html"><a href="inferencial.html#an%C3%A1lisis-exploratorio-1"><i class="fa fa-check"></i><b>2.3.1</b> Análisis exploratorio</a></li>
<li class="chapter" data-level="2.3.2" data-path="inferencial.html"><a href="inferencial.html#supuesto-de-normalidad-1"><i class="fa fa-check"></i><b>2.3.2</b> Supuesto de normalidad</a></li>
<li class="chapter" data-level="2.3.3" data-path="inferencial.html"><a href="inferencial.html#supuesto-de-homocedasticidad-1"><i class="fa fa-check"></i><b>2.3.3</b> Supuesto de homocedasticidad</a></li>
<li class="chapter" data-level="2.3.4" data-path="inferencial.html"><a href="inferencial.html#prueba-de-hip%C3%B3tesis-anova-de-un-factor"><i class="fa fa-check"></i><b>2.3.4</b> Prueba de hipótesis: ANOVA de un factor</a></li>
<li class="chapter" data-level="2.3.5" data-path="inferencial.html"><a href="inferencial.html#an%C3%A1lisis-de-sensibilidad-kruskal-wallis-y-prueba-de-dunn"><i class="fa fa-check"></i><b>2.3.5</b> Análisis de sensibilidad: Kruskal-Wallis y prueba de Dunn</a></li>
<li class="chapter" data-level="2.3.6" data-path="inferencial.html"><a href="inferencial.html#tama%C3%B1o-del-efecto-1"><i class="fa fa-check"></i><b>2.3.6</b> Tamaño del efecto</a></li>
<li class="chapter" data-level="2.3.7" data-path="inferencial.html"><a href="inferencial.html#conclusi%C3%B3n-1"><i class="fa fa-check"></i><b>2.3.7</b> Conclusión</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="inferencial.html"><a href="inferencial.html#objetivo-3-severidad-motora-seg%C3%BAn-el-nivel-de-inestabilidad-vocal"><i class="fa fa-check"></i><b>2.4</b> Objetivo 3: severidad motora según el nivel de inestabilidad vocal</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="inferencial.html"><a href="inferencial.html#an%C3%A1lisis-exploratorio-2"><i class="fa fa-check"></i><b>2.4.1</b> Análisis exploratorio</a></li>
<li class="chapter" data-level="2.4.2" data-path="inferencial.html"><a href="inferencial.html#supuesto-de-normalidad-2"><i class="fa fa-check"></i><b>2.4.2</b> Supuesto de normalidad</a></li>
<li class="chapter" data-level="2.4.3" data-path="inferencial.html"><a href="inferencial.html#supuesto-de-homocedasticidad-2"><i class="fa fa-check"></i><b>2.4.3</b> Supuesto de homocedasticidad</a></li>
<li class="chapter" data-level="2.4.4" data-path="inferencial.html"><a href="inferencial.html#prueba-de-hip%C3%B3tesis-t-de-student-1"><i class="fa fa-check"></i><b>2.4.4</b> Prueba de hipótesis: t de Student</a></li>
<li class="chapter" data-level="2.4.5" data-path="inferencial.html"><a href="inferencial.html#tama%C3%B1o-del-efecto-2"><i class="fa fa-check"></i><b>2.4.5</b> Tamaño del efecto</a></li>
<li class="chapter" data-level="2.4.6" data-path="inferencial.html"><a href="inferencial.html#conclusi%C3%B3n-2"><i class="fa fa-check"></i><b>2.4.6</b> Conclusión</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="inferencial.html"><a href="inferencial.html#objetivo-4-evoluci%C3%B3n-de-la-severidad-motora-durante-el-seguimiento"><i class="fa fa-check"></i><b>2.5</b> Objetivo 4: evolución de la severidad motora durante el seguimiento</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="inferencial.html"><a href="inferencial.html#an%C3%A1lisis-exploratorio-3"><i class="fa fa-check"></i><b>2.5.1</b> Análisis exploratorio</a></li>
<li class="chapter" data-level="2.5.2" data-path="inferencial.html"><a href="inferencial.html#supuesto-de-normalidad-de-las-diferencias"><i class="fa fa-check"></i><b>2.5.2</b> Supuesto de normalidad de las diferencias</a></li>
<li class="chapter" data-level="2.5.3" data-path="inferencial.html"><a href="inferencial.html#prueba-de-hip%C3%B3tesis-t-pareada"><i class="fa fa-check"></i><b>2.5.3</b> Prueba de hipótesis: t pareada</a></li>
<li class="chapter" data-level="2.5.4" data-path="inferencial.html"><a href="inferencial.html#tama%C3%B1o-del-efecto-3"><i class="fa fa-check"></i><b>2.5.4</b> Tamaño del efecto</a></li>
<li class="chapter" data-level="2.5.5" data-path="inferencial.html"><a href="inferencial.html#conclusi%C3%B3n-3"><i class="fa fa-check"></i><b>2.5.5</b> Conclusión</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="inferencial.html"><a href="inferencial.html#s%C3%ADntesis-de-resultados"><i class="fa fa-check"></i><b>2.6</b> Síntesis de resultados</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="conclusiones.html"><a href="conclusiones.html"><i class="fa fa-check"></i><b>3</b> Conclusiones</a></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/DiegoxorG/libro_met_est" target="blank">Diego Payares & Salma Romero</a></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis de la severidad motora en la enfermedad de Parkinson mediante características acústicas de telemonitoreo</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="inferencial" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Capítulo 2</span> Estadística inferencial<a href="inferencial.html#inferencial" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Este capítulo cubre los objetivos 5, 6 y 7: revisamos los supuestos de normalidad y homocedasticidad, contrastamos si la severidad motora cambia según el sexo, la edad, la inestabilidad vocal y el momento del seguimiento, y medimos el tamaño de cada efecto. En todas las pruebas usamos <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="inferencial.html#cb69-1" tabindex="-1"></a><span class="fu">library</span>(effsize)</span>
<span id="cb69-2"><a href="inferencial.html#cb69-2" tabindex="-1"></a><span class="fu">library</span>(nortest)</span>
<span id="cb69-3"><a href="inferencial.html#cb69-3" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb69-4"><a href="inferencial.html#cb69-4" tabindex="-1"></a><span class="fu">library</span>(rstatix)</span>
<span id="cb69-5"><a href="inferencial.html#cb69-5" tabindex="-1"></a><span class="fu">library</span>(dunn.test)</span></code></pre></div>
<div id="unidad-de-análisis-tabla-por-paciente" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Unidad de análisis: tabla por paciente<a href="inferencial.html#unidad-de-an%C3%A1lisis-tabla-por-paciente" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Las pruebas de hipótesis suponen observaciones independientes, y los 5.863 registros no lo son: vienen de 42 pacientes con entre 101 y 168 grabaciones cada uno, que comparten edad y sexo y cuyas puntuaciones <code>motor_UPDRS</code> están interpoladas entre visitas, así que casi no varían dentro de una misma persona. Tratarlos como independientes inflaría el tamaño de muestra y daría p-valores engañosamente pequeños (pseudorreplicación).</p>
<p>Por eso armamos una tabla con <strong>un registro por paciente</strong>: la severidad motora es el promedio de todas sus grabaciones, y de ahí salen las variables de agrupación: sexo, grupo de edad (menor de 60, 60 a 70 y mayor de 70 años) y nivel de inestabilidad vocal, alto o bajo según el promedio de cada índice esté por encima o por debajo de la mediana. Para comparar el inicio y el final del seguimiento guardamos la primera y la última grabación de cada paciente.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="inferencial.html#cb70-1" tabindex="-1"></a>pacientes <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb70-2"><a href="inferencial.html#cb70-2" tabindex="-1"></a>  <span class="fu">arrange</span>(subject., test_time) <span class="sc">%&gt;%</span></span>
<span id="cb70-3"><a href="inferencial.html#cb70-3" tabindex="-1"></a>  <span class="fu">group_by</span>(subject., sex, age) <span class="sc">%&gt;%</span></span>
<span id="cb70-4"><a href="inferencial.html#cb70-4" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb70-5"><a href="inferencial.html#cb70-5" tabindex="-1"></a>    <span class="at">n_registros =</span> <span class="fu">n</span>(),</span>
<span id="cb70-6"><a href="inferencial.html#cb70-6" tabindex="-1"></a>    <span class="at">motor =</span> <span class="fu">mean</span>(motor_UPDRS),</span>
<span id="cb70-7"><a href="inferencial.html#cb70-7" tabindex="-1"></a>    <span class="at">motor_inicio =</span> <span class="fu">first</span>(motor_UPDRS),</span>
<span id="cb70-8"><a href="inferencial.html#cb70-8" tabindex="-1"></a>    <span class="at">motor_final =</span> <span class="fu">last</span>(motor_UPDRS),</span>
<span id="cb70-9"><a href="inferencial.html#cb70-9" tabindex="-1"></a>    <span class="at">dias_seguimiento =</span> <span class="fu">last</span>(test_time) <span class="sc">-</span> <span class="fu">first</span>(test_time),</span>
<span id="cb70-10"><a href="inferencial.html#cb70-10" tabindex="-1"></a>    <span class="at">jitter =</span> <span class="fu">mean</span>(indice_jitter),</span>
<span id="cb70-11"><a href="inferencial.html#cb70-11" tabindex="-1"></a>    <span class="at">shimmer =</span> <span class="fu">mean</span>(indice_shimmer),</span>
<span id="cb70-12"><a href="inferencial.html#cb70-12" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb70-13"><a href="inferencial.html#cb70-13" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb70-14"><a href="inferencial.html#cb70-14" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb70-15"><a href="inferencial.html#cb70-15" tabindex="-1"></a>    <span class="at">grupo_edad =</span> <span class="fu">cut</span>(age,</span>
<span id="cb70-16"><a href="inferencial.html#cb70-16" tabindex="-1"></a>                     <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">59</span>, <span class="dv">70</span>, <span class="cn">Inf</span>),</span>
<span id="cb70-17"><a href="inferencial.html#cb70-17" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Menor de 60&quot;</span>, <span class="st">&quot;60 a 70&quot;</span>, <span class="st">&quot;Mayor de 70&quot;</span>)),</span>
<span id="cb70-18"><a href="inferencial.html#cb70-18" tabindex="-1"></a>    <span class="at">nivel_jitter =</span> <span class="fu">factor</span>(<span class="fu">if_else</span>(jitter <span class="sc">&gt;</span> <span class="fu">median</span>(jitter), <span class="st">&quot;Alto&quot;</span>, <span class="st">&quot;Bajo&quot;</span>),</span>
<span id="cb70-19"><a href="inferencial.html#cb70-19" tabindex="-1"></a>                          <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Bajo&quot;</span>, <span class="st">&quot;Alto&quot;</span>)),</span>
<span id="cb70-20"><a href="inferencial.html#cb70-20" tabindex="-1"></a>    <span class="at">nivel_shimmer =</span> <span class="fu">factor</span>(<span class="fu">if_else</span>(shimmer <span class="sc">&gt;</span> <span class="fu">median</span>(shimmer), <span class="st">&quot;Alto&quot;</span>, <span class="st">&quot;Bajo&quot;</span>),</span>
<span id="cb70-21"><a href="inferencial.html#cb70-21" tabindex="-1"></a>                           <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Bajo&quot;</span>, <span class="st">&quot;Alto&quot;</span>))</span>
<span id="cb70-22"><a href="inferencial.html#cb70-22" tabindex="-1"></a>  )</span>
<span id="cb70-23"><a href="inferencial.html#cb70-23" tabindex="-1"></a></span>
<span id="cb70-24"><a href="inferencial.html#cb70-24" tabindex="-1"></a><span class="fu">head</span>(pacientes) <span class="sc">%&gt;%</span></span>
<span id="cb70-25"><a href="inferencial.html#cb70-25" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">round</span>(.x, <span class="dv">2</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb70-26"><a href="inferencial.html#cb70-26" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   subject.       sex age n_registros motor motor_inicio motor_final
## 1        1 Masculino  72         149 31.90        28.20       36.98
## 2        2 Masculino  58         145 13.81        11.08       18.82
## 3        3 Masculino  57         144 27.12        23.44       28.01
## 4        4 Masculino  74         137 15.79        10.74       18.77
## 5        5 Masculino  75         156 31.63        31.00       33.76
## 6        6 Masculino  63         156 27.53        27.88       29.97
##   dias_seguimiento jitter shimmer  grupo_edad nivel_jitter nivel_shimmer
## 1           169.02  -0.40   -0.49 Mayor de 70         Bajo          Bajo
## 2           174.93   0.13    0.30 Menor de 60         Alto          Alto
## 3           160.98  -0.50   -0.70 Menor de 60         Bajo          Bajo
## 4           161.07  -0.19    0.74 Mayor de 70         Bajo          Alto
## 5           161.03  -0.17    0.13 Mayor de 70         Bajo          Alto
## 6           175.00  -0.02    0.29     60 a 70         Alto          Alto</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="inferencial.html#cb72-1" tabindex="-1"></a>pacientes <span class="sc">%&gt;%</span></span>
<span id="cb72-2"><a href="inferencial.html#cb72-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb72-3"><a href="inferencial.html#cb72-3" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb72-4"><a href="inferencial.html#cb72-4" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(motor),</span>
<span id="cb72-5"><a href="inferencial.html#cb72-5" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(motor),</span>
<span id="cb72-6"><a href="inferencial.html#cb72-6" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(motor),</span>
<span id="cb72-7"><a href="inferencial.html#cb72-7" tabindex="-1"></a>    <span class="at">RIC =</span> <span class="fu">IQR</span>(motor),</span>
<span id="cb72-8"><a href="inferencial.html#cb72-8" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(motor),</span>
<span id="cb72-9"><a href="inferencial.html#cb72-9" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(motor),</span>
<span id="cb72-10"><a href="inferencial.html#cb72-10" tabindex="-1"></a>    <span class="at">asimetria =</span> <span class="fu">skewness</span>(motor),</span>
<span id="cb72-11"><a href="inferencial.html#cb72-11" tabindex="-1"></a>    <span class="at">curtosis =</span> <span class="fu">kurtosis</span>(motor)</span>
<span id="cb72-12"><a href="inferencial.html#cb72-12" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb72-13"><a href="inferencial.html#cb72-13" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">round</span>(.x, <span class="dv">3</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb72-14"><a href="inferencial.html#cb72-14" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##    n  media   sd mediana    RIC minimo maximo asimetria curtosis
## 1 42 20.952 7.88   19.83 13.101  5.823  35.99     0.018    1.922</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="inferencial.html#cb74-1" tabindex="-1"></a><span class="fu">table</span>(pacientes<span class="sc">$</span>sex)</span></code></pre></div>
<pre><code>## 
## Masculino  Femenino 
##        28        14</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="inferencial.html#cb76-1" tabindex="-1"></a><span class="fu">table</span>(pacientes<span class="sc">$</span>grupo_edad)</span></code></pre></div>
<pre><code>## 
## Menor de 60     60 a 70 Mayor de 70 
##          14          15          13</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="inferencial.html#cb78-1" tabindex="-1"></a><span class="fu">table</span>(<span class="at">jitter =</span> pacientes<span class="sc">$</span>nivel_jitter, <span class="at">shimmer =</span> pacientes<span class="sc">$</span>nivel_shimmer)</span></code></pre></div>
<pre><code>##       shimmer
## jitter Bajo Alto
##   Bajo   16    5
##   Alto    5   16</code></pre>
<p>Quedan 42 pacientes: 28 hombres y 14 mujeres; 14, 15 y 13 por grupo de edad; y 21 con nivel alto y 21 con nivel bajo en cada índice (las dos clasificaciones coinciden en 32 pacientes, reflejo de la correlación de 0.71 entre los índices). La severidad promedio por paciente tiene media 20.95, mediana 19.83 y desviación estándar 7.88, entre 5.82 y 35.99; es simétrica (asimetría 0.02) y algo plana (curtosis 1.92), sin las dos modas del nivel de registro, porque ahora cada paciente cuenta una sola vez.</p>
<p>Para ver el problema en concreto, comparamos <code>motor_UPDRS</code> por sexo en los dos niveles:</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="inferencial.html#cb80-1" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb80-2"><a href="inferencial.html#cb80-2" tabindex="-1"></a>  <span class="at">nivel =</span> <span class="fu">c</span>(<span class="st">&quot;Registro (n = 5863)&quot;</span>, <span class="st">&quot;Paciente (n = 42)&quot;</span>),</span>
<span id="cb80-3"><a href="inferencial.html#cb80-3" tabindex="-1"></a>  <span class="at">p_valor_t =</span> <span class="fu">c</span>(<span class="fu">t.test</span>(motor_UPDRS <span class="sc">~</span> sex, <span class="at">data =</span> data, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>p.value,</span>
<span id="cb80-4"><a href="inferencial.html#cb80-4" tabindex="-1"></a>                <span class="fu">t.test</span>(motor <span class="sc">~</span> sex, <span class="at">data =</span> pacientes, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>p.value),</span>
<span id="cb80-5"><a href="inferencial.html#cb80-5" tabindex="-1"></a>  <span class="at">d_cohen =</span> <span class="fu">c</span>(<span class="fu">cohen.d</span>(motor_UPDRS <span class="sc">~</span> sex, <span class="at">data =</span> data)<span class="sc">$</span>estimate,</span>
<span id="cb80-6"><a href="inferencial.html#cb80-6" tabindex="-1"></a>              <span class="fu">cohen.d</span>(motor <span class="sc">~</span> sex, <span class="at">data =</span> pacientes)<span class="sc">$</span>estimate)</span>
<span id="cb80-7"><a href="inferencial.html#cb80-7" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb80-8"><a href="inferencial.html#cb80-8" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">round</span>(.x, <span class="dv">3</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb80-9"><a href="inferencial.html#cb80-9" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##                 nivel p_valor_t d_cohen
## 1 Registro (n = 5863)     0.019   0.066
## 2   Paciente (n = 42)     0.721   0.118</code></pre>
<p>A nivel de registro sale p = 0.019 con un efecto despreciable (d = 0.07): la “significancia” viene solo de contar a cada paciente unas 140 veces. Por paciente, con una diferencia parecida, p = 0.72. Todo lo que sigue usa la tabla <code>pacientes</code>.</p>
<p>Para no repetir código, definimos dos funciones: el resumen descriptivo por grupo y las pruebas de normalidad vistas en clase (Shapiro-Wilk, Kolmogorov-Smirnov sobre datos estandarizados y Lilliefors).</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="inferencial.html#cb82-1" tabindex="-1"></a>resumen_grupo <span class="ot">&lt;-</span> <span class="cf">function</span>(datos, grupo, <span class="at">variable =</span> <span class="st">&quot;motor&quot;</span>) {</span>
<span id="cb82-2"><a href="inferencial.html#cb82-2" tabindex="-1"></a>  datos <span class="sc">%&gt;%</span></span>
<span id="cb82-3"><a href="inferencial.html#cb82-3" tabindex="-1"></a>    <span class="fu">group_by</span>(.data[[grupo]]) <span class="sc">%&gt;%</span></span>
<span id="cb82-4"><a href="inferencial.html#cb82-4" tabindex="-1"></a>    <span class="fu">summarise</span>(</span>
<span id="cb82-5"><a href="inferencial.html#cb82-5" tabindex="-1"></a>      <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb82-6"><a href="inferencial.html#cb82-6" tabindex="-1"></a>      <span class="at">promedio =</span> <span class="fu">mean</span>(.data[[variable]]),</span>
<span id="cb82-7"><a href="inferencial.html#cb82-7" tabindex="-1"></a>      <span class="at">ds =</span> <span class="fu">sd</span>(.data[[variable]]),</span>
<span id="cb82-8"><a href="inferencial.html#cb82-8" tabindex="-1"></a>      <span class="at">mediana =</span> <span class="fu">median</span>(.data[[variable]]),</span>
<span id="cb82-9"><a href="inferencial.html#cb82-9" tabindex="-1"></a>      <span class="at">RIC =</span> <span class="fu">IQR</span>(.data[[variable]]),</span>
<span id="cb82-10"><a href="inferencial.html#cb82-10" tabindex="-1"></a>      <span class="at">min =</span> <span class="fu">min</span>(.data[[variable]]),</span>
<span id="cb82-11"><a href="inferencial.html#cb82-11" tabindex="-1"></a>      <span class="at">max =</span> <span class="fu">max</span>(.data[[variable]])</span>
<span id="cb82-12"><a href="inferencial.html#cb82-12" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb82-13"><a href="inferencial.html#cb82-13" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">round</span>(.x, <span class="dv">3</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb82-14"><a href="inferencial.html#cb82-14" tabindex="-1"></a>    <span class="fu">as.data.frame</span>()</span>
<span id="cb82-15"><a href="inferencial.html#cb82-15" tabindex="-1"></a>}</span>
<span id="cb82-16"><a href="inferencial.html#cb82-16" tabindex="-1"></a></span>
<span id="cb82-17"><a href="inferencial.html#cb82-17" tabindex="-1"></a>normalidad_grupo <span class="ot">&lt;-</span> <span class="cf">function</span>(datos, grupo, <span class="at">variable =</span> <span class="st">&quot;motor&quot;</span>) {</span>
<span id="cb82-18"><a href="inferencial.html#cb82-18" tabindex="-1"></a>  datos <span class="sc">%&gt;%</span></span>
<span id="cb82-19"><a href="inferencial.html#cb82-19" tabindex="-1"></a>    <span class="fu">group_by</span>(.data[[grupo]]) <span class="sc">%&gt;%</span></span>
<span id="cb82-20"><a href="inferencial.html#cb82-20" tabindex="-1"></a>    <span class="fu">summarise</span>(</span>
<span id="cb82-21"><a href="inferencial.html#cb82-21" tabindex="-1"></a>      <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb82-22"><a href="inferencial.html#cb82-22" tabindex="-1"></a>      <span class="at">est_w =</span> <span class="fu">shapiro.test</span>(.data[[variable]])<span class="sc">$</span>statistic,</span>
<span id="cb82-23"><a href="inferencial.html#cb82-23" tabindex="-1"></a>      <span class="at">p_sw =</span> <span class="fu">shapiro.test</span>(.data[[variable]])<span class="sc">$</span>p.value,</span>
<span id="cb82-24"><a href="inferencial.html#cb82-24" tabindex="-1"></a>      <span class="at">est_ks =</span> <span class="fu">ks.test</span>(<span class="fu">scale</span>(.data[[variable]]), <span class="st">&quot;pnorm&quot;</span>)<span class="sc">$</span>statistic,</span>
<span id="cb82-25"><a href="inferencial.html#cb82-25" tabindex="-1"></a>      <span class="at">p_ks =</span> <span class="fu">ks.test</span>(<span class="fu">scale</span>(.data[[variable]]), <span class="st">&quot;pnorm&quot;</span>)<span class="sc">$</span>p.value,</span>
<span id="cb82-26"><a href="inferencial.html#cb82-26" tabindex="-1"></a>      <span class="at">est_l =</span> <span class="fu">lillie.test</span>(.data[[variable]])<span class="sc">$</span>statistic,</span>
<span id="cb82-27"><a href="inferencial.html#cb82-27" tabindex="-1"></a>      <span class="at">p_l =</span> <span class="fu">lillie.test</span>(.data[[variable]])<span class="sc">$</span>p.value</span>
<span id="cb82-28"><a href="inferencial.html#cb82-28" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb82-29"><a href="inferencial.html#cb82-29" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">round</span>(.x, <span class="dv">3</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb82-30"><a href="inferencial.html#cb82-30" tabindex="-1"></a>    <span class="fu">as.data.frame</span>()</span>
<span id="cb82-31"><a href="inferencial.html#cb82-31" tabindex="-1"></a>}</span></code></pre></div>
</div>
<div id="objetivo-1-severidad-motora-según-el-sexo" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Objetivo 1: severidad motora según el sexo<a href="inferencial.html#objetivo-1-severidad-motora-seg%C3%BAn-el-sexo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>¿Difiere la severidad motora promedio entre hombres y mujeres?</p>
<p><span class="math display">\[H_0: \mu_{\text{Masculino}} = \mu_{\text{Femenino}} \qquad H_1: \mu_{\text{Masculino}} \neq \mu_{\text{Femenino}}\]</span></p>
<div id="análisis-exploratorio" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Análisis exploratorio<a href="inferencial.html#an%C3%A1lisis-exploratorio" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="inferencial.html#cb83-1" tabindex="-1"></a><span class="fu">resumen_grupo</span>(pacientes, <span class="st">&quot;sex&quot;</span>)</span></code></pre></div>
<pre><code>##         sex  n promedio    ds mediana    RIC   min    max
## 1 Masculino 28   21.265 7.745  21.373 11.892 5.823 35.990
## 2  Femenino 14   20.326 8.403  19.702 13.287 9.800 34.405</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="inferencial.html#cb85-1" tabindex="-1"></a>pacientes <span class="sc">%&gt;%</span></span>
<span id="cb85-2"><a href="inferencial.html#cb85-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> sex, <span class="at">y =</span> motor)) <span class="sc">+</span></span>
<span id="cb85-3"><a href="inferencial.html#cb85-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#FAD0C4&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#C2185B&quot;</span>, <span class="at">width =</span> <span class="fl">0.4</span>,</span>
<span id="cb85-4"><a href="inferencial.html#cb85-4" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&quot;#8E0038&quot;</span>) <span class="sc">+</span></span>
<span id="cb85-5"><a href="inferencial.html#cb85-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="at">color =</span> <span class="st">&quot;#8E0038&quot;</span>) <span class="sc">+</span></span>
<span id="cb85-6"><a href="inferencial.html#cb85-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Severidad motora promedio por paciente según el sexo&quot;</span>,</span>
<span id="cb85-7"><a href="inferencial.html#cb85-7" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb85-8"><a href="inferencial.html#cb85-8" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Motor UPDRS promedio (Puntos)&quot;</span>) <span class="sc">+</span></span>
<span id="cb85-9"><a href="inferencial.html#cb85-9" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/inf-sexo-boxplot-1.png" alt="" width="672" /></p>
<p>Los 28 hombres promedian 21.27 puntos (mediana 21.37, desviación 7.74) y las 14 mujeres 20.33 (mediana 19.7, desviación 8.4). La diferencia no llega a un punto, las cajas se solapan casi por completo y no hay atípicos.</p>
</div>
<div id="supuesto-de-normalidad" class="section level3 hasAnchor" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Supuesto de normalidad<a href="inferencial.html#supuesto-de-normalidad" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="inferencial.html#cb86-1" tabindex="-1"></a><span class="fu">normalidad_grupo</span>(pacientes, <span class="st">&quot;sex&quot;</span>)</span></code></pre></div>
<pre><code>##         sex  n est_w  p_sw est_ks  p_ks est_l   p_l
## 1 Masculino 28 0.973 0.663  0.126 0.716 0.126 0.302
## 2  Femenino 14 0.931 0.318  0.150 0.868 0.150 0.537</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="inferencial.html#cb88-1" tabindex="-1"></a>pacientes <span class="sc">%&gt;%</span></span>
<span id="cb88-2"><a href="inferencial.html#cb88-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> motor)) <span class="sc">+</span></span>
<span id="cb88-3"><a href="inferencial.html#cb88-3" tabindex="-1"></a>  <span class="fu">stat_qq</span>(<span class="at">color =</span> <span class="st">&quot;#C77D98&quot;</span>) <span class="sc">+</span></span>
<span id="cb88-4"><a href="inferencial.html#cb88-4" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="at">color =</span> <span class="st">&quot;#8F4A68&quot;</span>) <span class="sc">+</span></span>
<span id="cb88-5"><a href="inferencial.html#cb88-5" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> sex) <span class="sc">+</span></span>
<span id="cb88-6"><a href="inferencial.html#cb88-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Gráficos cuantil-cuantil de la severidad motora por sexo&quot;</span>,</span>
<span id="cb88-7"><a href="inferencial.html#cb88-7" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Cuantiles teóricos&quot;</span>,</span>
<span id="cb88-8"><a href="inferencial.html#cb88-8" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Cuantiles muestrales&quot;</span>) <span class="sc">+</span></span>
<span id="cb88-9"><a href="inferencial.html#cb88-9" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/inf-sexo-qq-1.png" alt="" width="672" /></p>
<p>Ninguna prueba rechaza la normalidad: Shapiro-Wilk da p = 0.663 en hombres y p = 0.318 en mujeres, y Kolmogorov-Smirnov y Lilliefors coinciden (p entre 0.3 y 0.87). En los QQ-plots los puntos siguen la recta, con las desviaciones leves en los extremos que son normales en muestras pequeñas. Asumimos normalidad en ambos grupos.</p>
</div>
<div id="supuesto-de-homocedasticidad" class="section level3 hasAnchor" number="2.2.3">
<h3><span class="header-section-number">2.2.3</span> Supuesto de homocedasticidad<a href="inferencial.html#supuesto-de-homocedasticidad" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="inferencial.html#cb89-1" tabindex="-1"></a>motor_hombres <span class="ot">&lt;-</span> pacientes <span class="sc">%&gt;%</span></span>
<span id="cb89-2"><a href="inferencial.html#cb89-2" tabindex="-1"></a>  <span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">&quot;Masculino&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb89-3"><a href="inferencial.html#cb89-3" tabindex="-1"></a>  <span class="fu">pull</span>(motor)</span>
<span id="cb89-4"><a href="inferencial.html#cb89-4" tabindex="-1"></a></span>
<span id="cb89-5"><a href="inferencial.html#cb89-5" tabindex="-1"></a>motor_mujeres <span class="ot">&lt;-</span> pacientes <span class="sc">%&gt;%</span></span>
<span id="cb89-6"><a href="inferencial.html#cb89-6" tabindex="-1"></a>  <span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">&quot;Femenino&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb89-7"><a href="inferencial.html#cb89-7" tabindex="-1"></a>  <span class="fu">pull</span>(motor)</span>
<span id="cb89-8"><a href="inferencial.html#cb89-8" tabindex="-1"></a></span>
<span id="cb89-9"><a href="inferencial.html#cb89-9" tabindex="-1"></a>prueba_f_sexo <span class="ot">&lt;-</span> <span class="fu">var.test</span>(motor_hombres, motor_mujeres)</span>
<span id="cb89-10"><a href="inferencial.html#cb89-10" tabindex="-1"></a>prueba_f_sexo</span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  motor_hombres and motor_mujeres
## F = 0.84945, num df = 27, denom df = 13, p-value = 0.6918
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.2967724 2.0636019
## sample estimates:
## ratio of variances 
##          0.8494518</code></pre>
<p>Verificamos <code>var.test</code> con el teorema de la razón de varianzas:</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="inferencial.html#cb91-1" tabindex="-1"></a>n1 <span class="ot">&lt;-</span> <span class="fu">length</span>(motor_hombres)</span>
<span id="cb91-2"><a href="inferencial.html#cb91-2" tabindex="-1"></a>n2 <span class="ot">&lt;-</span> <span class="fu">length</span>(motor_mujeres)</span>
<span id="cb91-3"><a href="inferencial.html#cb91-3" tabindex="-1"></a>s1 <span class="ot">&lt;-</span> <span class="fu">sum</span>((motor_hombres <span class="sc">-</span> <span class="fu">mean</span>(motor_hombres))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (n1 <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb91-4"><a href="inferencial.html#cb91-4" tabindex="-1"></a>s2 <span class="ot">&lt;-</span> <span class="fu">sum</span>((motor_mujeres <span class="sc">-</span> <span class="fu">mean</span>(motor_mujeres))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (n2 <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb91-5"><a href="inferencial.html#cb91-5" tabindex="-1"></a></span>
<span id="cb91-6"><a href="inferencial.html#cb91-6" tabindex="-1"></a>F0 <span class="ot">&lt;-</span> s1 <span class="sc">/</span> s2</span>
<span id="cb91-7"><a href="inferencial.html#cb91-7" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> n1 <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb91-8"><a href="inferencial.html#cb91-8" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> n2 <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb91-9"><a href="inferencial.html#cb91-9" tabindex="-1"></a>pvalor_F <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">min</span>(<span class="fu">pf</span>(F0, df1, df2), <span class="fu">pf</span>(F0, df1, df2, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>))</span>
<span id="cb91-10"><a href="inferencial.html#cb91-10" tabindex="-1"></a></span>
<span id="cb91-11"><a href="inferencial.html#cb91-11" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb91-12"><a href="inferencial.html#cb91-12" tabindex="-1"></a>int_inf_F <span class="ot">&lt;-</span> (s1 <span class="sc">/</span> s2) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">/</span> <span class="fu">qf</span>(<span class="dv">1</span> <span class="sc">-</span> alpha <span class="sc">/</span> <span class="dv">2</span>, df1, df2))</span>
<span id="cb91-13"><a href="inferencial.html#cb91-13" tabindex="-1"></a>int_sup_F <span class="ot">&lt;-</span> (s1 <span class="sc">/</span> s2) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">/</span> <span class="fu">qf</span>(alpha <span class="sc">/</span> <span class="dv">2</span>, df1, df2))</span>
<span id="cb91-14"><a href="inferencial.html#cb91-14" tabindex="-1"></a></span>
<span id="cb91-15"><a href="inferencial.html#cb91-15" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb91-16"><a href="inferencial.html#cb91-16" tabindex="-1"></a>  <span class="at">estadistico_F_manual =</span> F0,</span>
<span id="cb91-17"><a href="inferencial.html#cb91-17" tabindex="-1"></a>  <span class="at">estadistico_F_var_test =</span> <span class="fu">unname</span>(prueba_f_sexo<span class="sc">$</span>statistic),</span>
<span id="cb91-18"><a href="inferencial.html#cb91-18" tabindex="-1"></a>  <span class="at">gl_numerador =</span> df1,</span>
<span id="cb91-19"><a href="inferencial.html#cb91-19" tabindex="-1"></a>  <span class="at">gl_denominador =</span> df2,</span>
<span id="cb91-20"><a href="inferencial.html#cb91-20" tabindex="-1"></a>  <span class="at">p_valor_manual =</span> pvalor_F,</span>
<span id="cb91-21"><a href="inferencial.html#cb91-21" tabindex="-1"></a>  <span class="at">p_valor_var_test =</span> prueba_f_sexo<span class="sc">$</span>p.value,</span>
<span id="cb91-22"><a href="inferencial.html#cb91-22" tabindex="-1"></a>  <span class="at">IC_inferior_manual =</span> int_inf_F,</span>
<span id="cb91-23"><a href="inferencial.html#cb91-23" tabindex="-1"></a>  <span class="at">IC_superior_manual =</span> int_sup_F,</span>
<span id="cb91-24"><a href="inferencial.html#cb91-24" tabindex="-1"></a>  <span class="at">IC_inferior_var_test =</span> prueba_f_sexo<span class="sc">$</span>conf.int[<span class="dv">1</span>],</span>
<span id="cb91-25"><a href="inferencial.html#cb91-25" tabindex="-1"></a>  <span class="at">IC_superior_var_test =</span> prueba_f_sexo<span class="sc">$</span>conf.int[<span class="dv">2</span>]</span>
<span id="cb91-26"><a href="inferencial.html#cb91-26" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb91-27"><a href="inferencial.html#cb91-27" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">round</span>(.x, <span class="dv">4</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb91-28"><a href="inferencial.html#cb91-28" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   estadistico_F_manual estadistico_F_var_test gl_numerador gl_denominador
## 1               0.8495                 0.8495           27             13
##   p_valor_manual p_valor_var_test IC_inferior_manual IC_superior_manual
## 1         0.6918           0.6918             0.2968             2.0636
##   IC_inferior_var_test IC_superior_var_test
## 1               0.2968               2.0636</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="inferencial.html#cb93-1" tabindex="-1"></a><span class="fu">leveneTest</span>(motor <span class="sc">~</span> sex, <span class="at">data =</span> pacientes, <span class="at">center =</span> median)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  1  0.0744 0.7864
##       40</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="inferencial.html#cb95-1" tabindex="-1"></a><span class="fu">bartlett.test</span>(motor <span class="sc">~</span> sex, <span class="at">data =</span> pacientes)</span></code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  motor by sex
## Bartlett&#39;s K-squared = 0.11552, df = 1, p-value = 0.7339</code></pre>
<p>Las varianzas son 59.98 y 70.61. La prueba F da F = 0.849 (27 y 13 g.l., p = 0.692) y su intervalo para la razón de varianzas, de 0.3 a 2.06, contiene al 1; el cálculo manual coincide exactamente con <code>var.test</code>. Levene (p = 0.786) y Bartlett (p = 0.734) dicen lo mismo. No se rechaza la igualdad de varianzas, así que usamos la t de Student con varianzas iguales.</p>
</div>
<div id="prueba-de-hipótesis-t-de-student" class="section level3 hasAnchor" number="2.2.4">
<h3><span class="header-section-number">2.2.4</span> Prueba de hipótesis: t de Student<a href="inferencial.html#prueba-de-hip%C3%B3tesis-t-de-student" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="inferencial.html#cb97-1" tabindex="-1"></a>prueba_t_sexo <span class="ot">&lt;-</span> <span class="fu">t.test</span>(<span class="at">x =</span> motor_hombres, <span class="at">y =</span> motor_mujeres,</span>
<span id="cb97-2"><a href="inferencial.html#cb97-2" tabindex="-1"></a>                        <span class="at">var.equal =</span> <span class="cn">TRUE</span>, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span>
<span id="cb97-3"><a href="inferencial.html#cb97-3" tabindex="-1"></a>prueba_t_sexo</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  motor_hombres and motor_mujeres
## t = 0.36032, df = 40, p-value = 0.7205
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -4.329695  6.208460
## sample estimates:
## mean of x mean of y 
##  21.26543  20.32605</code></pre>
<p>Verificación con el teorema de la diferencia de medias:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="inferencial.html#cb99-1" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(motor_hombres)</span>
<span id="cb99-2"><a href="inferencial.html#cb99-2" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(motor_mujeres)</span>
<span id="cb99-3"><a href="inferencial.html#cb99-3" tabindex="-1"></a>s1_cuad <span class="ot">&lt;-</span> <span class="fu">var</span>(motor_hombres)</span>
<span id="cb99-4"><a href="inferencial.html#cb99-4" tabindex="-1"></a>s2_cuad <span class="ot">&lt;-</span> <span class="fu">var</span>(motor_mujeres)</span>
<span id="cb99-5"><a href="inferencial.html#cb99-5" tabindex="-1"></a></span>
<span id="cb99-6"><a href="inferencial.html#cb99-6" tabindex="-1"></a>sp_cuad <span class="ot">&lt;-</span> ((n1 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> s1_cuad <span class="sc">+</span> (n2 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> s2_cuad) <span class="sc">/</span> (n1 <span class="sc">+</span> n2 <span class="sc">-</span> <span class="dv">2</span>)</span>
<span id="cb99-7"><a href="inferencial.html#cb99-7" tabindex="-1"></a>error_estandar <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(sp_cuad <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">/</span> n1 <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> n2))</span>
<span id="cb99-8"><a href="inferencial.html#cb99-8" tabindex="-1"></a>t0 <span class="ot">&lt;-</span> (m1 <span class="sc">-</span> m2) <span class="sc">/</span> error_estandar</span>
<span id="cb99-9"><a href="inferencial.html#cb99-9" tabindex="-1"></a>df_t <span class="ot">&lt;-</span> n1 <span class="sc">+</span> n2 <span class="sc">-</span> <span class="dv">2</span></span>
<span id="cb99-10"><a href="inferencial.html#cb99-10" tabindex="-1"></a>pvalor_t <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="fu">abs</span>(t0), <span class="at">df =</span> df_t, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb99-11"><a href="inferencial.html#cb99-11" tabindex="-1"></a></span>
<span id="cb99-12"><a href="inferencial.html#cb99-12" tabindex="-1"></a>t_critico <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="dv">1</span> <span class="sc">-</span> alpha <span class="sc">/</span> <span class="dv">2</span>, <span class="at">df =</span> df_t)</span>
<span id="cb99-13"><a href="inferencial.html#cb99-13" tabindex="-1"></a>int_inf_t <span class="ot">&lt;-</span> (m1 <span class="sc">-</span> m2) <span class="sc">-</span> t_critico <span class="sc">*</span> error_estandar</span>
<span id="cb99-14"><a href="inferencial.html#cb99-14" tabindex="-1"></a>int_sup_t <span class="ot">&lt;-</span> (m1 <span class="sc">-</span> m2) <span class="sc">+</span> t_critico <span class="sc">*</span> error_estandar</span>
<span id="cb99-15"><a href="inferencial.html#cb99-15" tabindex="-1"></a></span>
<span id="cb99-16"><a href="inferencial.html#cb99-16" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb99-17"><a href="inferencial.html#cb99-17" tabindex="-1"></a>  <span class="at">estadistico_t_manual =</span> t0,</span>
<span id="cb99-18"><a href="inferencial.html#cb99-18" tabindex="-1"></a>  <span class="at">estadistico_t_t_test =</span> <span class="fu">unname</span>(prueba_t_sexo<span class="sc">$</span>statistic),</span>
<span id="cb99-19"><a href="inferencial.html#cb99-19" tabindex="-1"></a>  <span class="at">grados_libertad_manual =</span> df_t,</span>
<span id="cb99-20"><a href="inferencial.html#cb99-20" tabindex="-1"></a>  <span class="at">grados_libertad_t_test =</span> <span class="fu">unname</span>(prueba_t_sexo<span class="sc">$</span>parameter),</span>
<span id="cb99-21"><a href="inferencial.html#cb99-21" tabindex="-1"></a>  <span class="at">p_valor_manual =</span> pvalor_t,</span>
<span id="cb99-22"><a href="inferencial.html#cb99-22" tabindex="-1"></a>  <span class="at">p_valor_t_test =</span> prueba_t_sexo<span class="sc">$</span>p.value,</span>
<span id="cb99-23"><a href="inferencial.html#cb99-23" tabindex="-1"></a>  <span class="at">IC_inferior_manual =</span> int_inf_t,</span>
<span id="cb99-24"><a href="inferencial.html#cb99-24" tabindex="-1"></a>  <span class="at">IC_superior_manual =</span> int_sup_t,</span>
<span id="cb99-25"><a href="inferencial.html#cb99-25" tabindex="-1"></a>  <span class="at">IC_inferior_t_test =</span> prueba_t_sexo<span class="sc">$</span>conf.int[<span class="dv">1</span>],</span>
<span id="cb99-26"><a href="inferencial.html#cb99-26" tabindex="-1"></a>  <span class="at">IC_superior_t_test =</span> prueba_t_sexo<span class="sc">$</span>conf.int[<span class="dv">2</span>]</span>
<span id="cb99-27"><a href="inferencial.html#cb99-27" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb99-28"><a href="inferencial.html#cb99-28" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">round</span>(.x, <span class="dv">4</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb99-29"><a href="inferencial.html#cb99-29" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   estadistico_t_manual estadistico_t_t_test grados_libertad_manual
## 1               0.3603               0.3603                     40
##   grados_libertad_t_test p_valor_manual p_valor_t_test IC_inferior_manual
## 1                     40         0.7205         0.7205            -4.3297
##   IC_superior_manual IC_inferior_t_test IC_superior_t_test
## 1             6.2085            -4.3297             6.2085</code></pre>
<p>Como el grupo de mujeres es pequeño (n = 14), añadimos Mann-Whitney como análisis de sensibilidad:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="inferencial.html#cb101-1" tabindex="-1"></a><span class="fu">wilcox.test</span>(<span class="at">x =</span> motor_hombres, <span class="at">y =</span> motor_mujeres, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum exact test
## 
## data:  motor_hombres and motor_mujeres
## W = 212, p-value = 0.6828
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>La prueba t da t = 0.36 con 40 g.l. y p = 0.721; la diferencia estimada es de 0.94 puntos, con un intervalo de -4.33 a 6.21 que incluye al 0. El cálculo manual reproduce todos los valores de <code>t.test</code>, y Mann-Whitney (W = 212, p = 0.683) lleva a la misma decisión.</p>
</div>
<div id="tamaño-del-efecto" class="section level3 hasAnchor" number="2.2.5">
<h3><span class="header-section-number">2.2.5</span> Tamaño del efecto<a href="inferencial.html#tama%C3%B1o-del-efecto" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="inferencial.html#cb103-1" tabindex="-1"></a>d_sexo <span class="ot">&lt;-</span> <span class="fu">cohen.d</span>(motor_hombres, motor_mujeres, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span>
<span id="cb103-2"><a href="inferencial.html#cb103-2" tabindex="-1"></a>d_sexo</span></code></pre></div>
<pre><code>## 
## Cohen&#39;s d
## 
## d estimate: 0.1179429 (negligible)
## 95 percent confidence interval:
##      lower      upper 
## -0.5441203  0.7800062</code></pre>
<p>La d de Cohen es 0.12, un efecto despreciable, con un intervalo de -0.54 a 0.78 que incluye al 0.</p>
</div>
<div id="conclusión" class="section level3 hasAnchor" number="2.2.6">
<h3><span class="header-section-number">2.2.6</span> Conclusión<a href="inferencial.html#conclusi%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Con una confianza del 95 %, no hay evidencia de que la severidad motora difiera entre hombres y mujeres (t = 0.36, p = 0.721). La diferencia observada, menos de un punto, tampoco tiene relevancia práctica (d = 0.12).</p>
</div>
</div>
<div id="objetivo-2-severidad-motora-según-el-grupo-de-edad" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Objetivo 2: severidad motora según el grupo de edad<a href="inferencial.html#objetivo-2-severidad-motora-seg%C3%BAn-el-grupo-de-edad" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>¿Difiere la severidad motora promedio entre los tres grupos de edad?</p>
<p><span class="math display">\[H_0: \mu_{&lt;60} = \mu_{60-70} = \mu_{&gt;70} \qquad H_1: \text{al menos una media es diferente}\]</span></p>
<div id="análisis-exploratorio-1" class="section level3 hasAnchor" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> Análisis exploratorio<a href="inferencial.html#an%C3%A1lisis-exploratorio-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="inferencial.html#cb105-1" tabindex="-1"></a><span class="fu">resumen_grupo</span>(pacientes, <span class="st">&quot;grupo_edad&quot;</span>)</span></code></pre></div>
<pre><code>##    grupo_edad  n promedio    ds mediana    RIC    min    max
## 1 Menor de 60 14   18.236 7.328  15.712 11.789  9.800 31.861
## 2     60 a 70 15   19.960 8.273  19.773 12.538  5.823 34.405
## 3 Mayor de 70 13   25.023 6.806  26.404  9.651 15.791 35.990</code></pre>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="inferencial.html#cb107-1" tabindex="-1"></a>pacientes <span class="sc">%&gt;%</span></span>
<span id="cb107-2"><a href="inferencial.html#cb107-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> grupo_edad, <span class="at">y =</span> motor)) <span class="sc">+</span></span>
<span id="cb107-3"><a href="inferencial.html#cb107-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#FAD0C4&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#C2185B&quot;</span>, <span class="at">width =</span> <span class="fl">0.5</span>,</span>
<span id="cb107-4"><a href="inferencial.html#cb107-4" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&quot;#8E0038&quot;</span>) <span class="sc">+</span></span>
<span id="cb107-5"><a href="inferencial.html#cb107-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="at">color =</span> <span class="st">&quot;#8E0038&quot;</span>) <span class="sc">+</span></span>
<span id="cb107-6"><a href="inferencial.html#cb107-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Severidad motora promedio por paciente según el grupo de edad&quot;</span>,</span>
<span id="cb107-7"><a href="inferencial.html#cb107-7" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Grupo de edad (años)&quot;</span>,</span>
<span id="cb107-8"><a href="inferencial.html#cb107-8" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Motor UPDRS promedio (Puntos)&quot;</span>) <span class="sc">+</span></span>
<span id="cb107-9"><a href="inferencial.html#cb107-9" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/inf-edad-boxplot-1.png" alt="" width="672" /></p>
<p>La severidad sube con la edad: 18.24 puntos en los menores de 60 (mediana 15.71), 19.96 entre 60 y 70 (mediana 19.77) y 25.02 en los mayores de 70 (mediana 26.4), casi 7 puntos entre los extremos. Las desviaciones estándar son parecidas (7.33, 8.27 y 6.81), el grupo mayor es el más homogéneo y no hay atípicos.</p>
</div>
<div id="supuesto-de-normalidad-1" class="section level3 hasAnchor" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> Supuesto de normalidad<a href="inferencial.html#supuesto-de-normalidad-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="inferencial.html#cb108-1" tabindex="-1"></a><span class="fu">normalidad_grupo</span>(pacientes, <span class="st">&quot;grupo_edad&quot;</span>)</span></code></pre></div>
<pre><code>##    grupo_edad  n est_w  p_sw est_ks  p_ks est_l   p_l
## 1 Menor de 60 14 0.898 0.105  0.227 0.406 0.227 0.049
## 2     60 a 70 15 0.979 0.964  0.114 0.977 0.114 0.864
## 3 Mayor de 70 13 0.921 0.257  0.169 0.796 0.169 0.396</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="inferencial.html#cb110-1" tabindex="-1"></a>pacientes <span class="sc">%&gt;%</span></span>
<span id="cb110-2"><a href="inferencial.html#cb110-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> motor)) <span class="sc">+</span></span>
<span id="cb110-3"><a href="inferencial.html#cb110-3" tabindex="-1"></a>  <span class="fu">stat_qq</span>(<span class="at">color =</span> <span class="st">&quot;#C77D98&quot;</span>) <span class="sc">+</span></span>
<span id="cb110-4"><a href="inferencial.html#cb110-4" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="at">color =</span> <span class="st">&quot;#8F4A68&quot;</span>) <span class="sc">+</span></span>
<span id="cb110-5"><a href="inferencial.html#cb110-5" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> grupo_edad) <span class="sc">+</span></span>
<span id="cb110-6"><a href="inferencial.html#cb110-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Gráficos cuantil-cuantil de la severidad motora por grupo de edad&quot;</span>,</span>
<span id="cb110-7"><a href="inferencial.html#cb110-7" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Cuantiles teóricos&quot;</span>,</span>
<span id="cb110-8"><a href="inferencial.html#cb110-8" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Cuantiles muestrales&quot;</span>) <span class="sc">+</span></span>
<span id="cb110-9"><a href="inferencial.html#cb110-9" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/inf-edad-qq-1.png" alt="" width="672" /></p>
<p>Shapiro-Wilk no rechaza en ningún grupo (p = 0.105, 0.964 y 0.257) y Kolmogorov-Smirnov tampoco. Solo Lilliefors queda al límite en los menores de 60 (p = 0.049), cuyo QQ-plot se curva un poco por la concentración de valores bajos. Como Shapiro-Wilk, la prueba más potente en muestras pequeñas, no rechaza, y el ANOVA es robusto a desvíos moderados con grupos de tamaño parecido, asumimos normalidad.</p>
</div>
<div id="supuesto-de-homocedasticidad-1" class="section level3 hasAnchor" number="2.3.3">
<h3><span class="header-section-number">2.3.3</span> Supuesto de homocedasticidad<a href="inferencial.html#supuesto-de-homocedasticidad-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="inferencial.html#cb111-1" tabindex="-1"></a><span class="fu">leveneTest</span>(motor <span class="sc">~</span> grupo_edad, <span class="at">data =</span> pacientes, <span class="at">center =</span> median)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  0.2583 0.7737
##       39</code></pre>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="inferencial.html#cb113-1" tabindex="-1"></a><span class="fu">bartlett.test</span>(motor <span class="sc">~</span> grupo_edad, <span class="at">data =</span> pacientes)</span></code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  motor by grupo_edad
## Bartlett&#39;s K-squared = 0.49607, df = 2, p-value = 0.7803</code></pre>
<p>Levene (p = 0.774) y Bartlett (p = 0.78) no rechazan la igualdad de varianzas.</p>
</div>
<div id="prueba-de-hipótesis-anova-de-un-factor" class="section level3 hasAnchor" number="2.3.4">
<h3><span class="header-section-number">2.3.4</span> Prueba de hipótesis: ANOVA de un factor<a href="inferencial.html#prueba-de-hip%C3%B3tesis-anova-de-un-factor" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="inferencial.html#cb115-1" tabindex="-1"></a>modelo_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(motor <span class="sc">~</span> grupo_edad, <span class="at">data =</span> pacientes)</span>
<span id="cb115-2"><a href="inferencial.html#cb115-2" tabindex="-1"></a><span class="fu">summary</span>(modelo_anova)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)  
## grupo_edad   2  333.5  166.75    2.94 0.0647 .
## Residuals   39 2212.2   56.72                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Verificación del ANOVA con la descomposición de la suma de cuadrados:</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="inferencial.html#cb117-1" tabindex="-1"></a>menores_60 <span class="ot">&lt;-</span> pacientes <span class="sc">%&gt;%</span> <span class="fu">filter</span>(grupo_edad <span class="sc">==</span> <span class="st">&quot;Menor de 60&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(motor)</span>
<span id="cb117-2"><a href="inferencial.html#cb117-2" tabindex="-1"></a>de_60_a_70 <span class="ot">&lt;-</span> pacientes <span class="sc">%&gt;%</span> <span class="fu">filter</span>(grupo_edad <span class="sc">==</span> <span class="st">&quot;60 a 70&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(motor)</span>
<span id="cb117-3"><a href="inferencial.html#cb117-3" tabindex="-1"></a>mayores_70 <span class="ot">&lt;-</span> pacientes <span class="sc">%&gt;%</span> <span class="fu">filter</span>(grupo_edad <span class="sc">==</span> <span class="st">&quot;Mayor de 70&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(motor)</span>
<span id="cb117-4"><a href="inferencial.html#cb117-4" tabindex="-1"></a></span>
<span id="cb117-5"><a href="inferencial.html#cb117-5" tabindex="-1"></a>n1 <span class="ot">&lt;-</span> <span class="fu">length</span>(menores_60)</span>
<span id="cb117-6"><a href="inferencial.html#cb117-6" tabindex="-1"></a>n2 <span class="ot">&lt;-</span> <span class="fu">length</span>(de_60_a_70)</span>
<span id="cb117-7"><a href="inferencial.html#cb117-7" tabindex="-1"></a>n3 <span class="ot">&lt;-</span> <span class="fu">length</span>(mayores_70)</span>
<span id="cb117-8"><a href="inferencial.html#cb117-8" tabindex="-1"></a>N <span class="ot">&lt;-</span> n1 <span class="sc">+</span> n2 <span class="sc">+</span> n3</span>
<span id="cb117-9"><a href="inferencial.html#cb117-9" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb117-10"><a href="inferencial.html#cb117-10" tabindex="-1"></a></span>
<span id="cb117-11"><a href="inferencial.html#cb117-11" tabindex="-1"></a>xbar_1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(menores_60)</span>
<span id="cb117-12"><a href="inferencial.html#cb117-12" tabindex="-1"></a>xbar_2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(de_60_a_70)</span>
<span id="cb117-13"><a href="inferencial.html#cb117-13" tabindex="-1"></a>xbar_3 <span class="ot">&lt;-</span> <span class="fu">mean</span>(mayores_70)</span>
<span id="cb117-14"><a href="inferencial.html#cb117-14" tabindex="-1"></a>xbar_total <span class="ot">&lt;-</span> (<span class="fu">sum</span>(menores_60) <span class="sc">+</span> <span class="fu">sum</span>(de_60_a_70) <span class="sc">+</span> <span class="fu">sum</span>(mayores_70)) <span class="sc">/</span> N</span>
<span id="cb117-15"><a href="inferencial.html#cb117-15" tabindex="-1"></a></span>
<span id="cb117-16"><a href="inferencial.html#cb117-16" tabindex="-1"></a>SST <span class="ot">&lt;-</span> <span class="fu">sum</span>((menores_60 <span class="sc">-</span> xbar_total)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">sum</span>((de_60_a_70 <span class="sc">-</span> xbar_total)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb117-17"><a href="inferencial.html#cb117-17" tabindex="-1"></a>  <span class="fu">sum</span>((mayores_70 <span class="sc">-</span> xbar_total)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb117-18"><a href="inferencial.html#cb117-18" tabindex="-1"></a>SSA <span class="ot">&lt;-</span> n1 <span class="sc">*</span> (xbar_1 <span class="sc">-</span> xbar_total)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> n2 <span class="sc">*</span> (xbar_2 <span class="sc">-</span> xbar_total)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span></span>
<span id="cb117-19"><a href="inferencial.html#cb117-19" tabindex="-1"></a>  n3 <span class="sc">*</span> (xbar_3 <span class="sc">-</span> xbar_total)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb117-20"><a href="inferencial.html#cb117-20" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> SST <span class="sc">-</span> SSA</span>
<span id="cb117-21"><a href="inferencial.html#cb117-21" tabindex="-1"></a></span>
<span id="cb117-22"><a href="inferencial.html#cb117-22" tabindex="-1"></a>MSA <span class="ot">&lt;-</span> SSA <span class="sc">/</span> (k <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb117-23"><a href="inferencial.html#cb117-23" tabindex="-1"></a>MSE <span class="ot">&lt;-</span> SSE <span class="sc">/</span> (N <span class="sc">-</span> k)</span>
<span id="cb117-24"><a href="inferencial.html#cb117-24" tabindex="-1"></a>F0 <span class="ot">&lt;-</span> MSA <span class="sc">/</span> MSE</span>
<span id="cb117-25"><a href="inferencial.html#cb117-25" tabindex="-1"></a></span>
<span id="cb117-26"><a href="inferencial.html#cb117-26" tabindex="-1"></a>v1 <span class="ot">&lt;-</span> k <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb117-27"><a href="inferencial.html#cb117-27" tabindex="-1"></a>v2 <span class="ot">&lt;-</span> N <span class="sc">-</span> k</span>
<span id="cb117-28"><a href="inferencial.html#cb117-28" tabindex="-1"></a>F_critico <span class="ot">&lt;-</span> <span class="fu">qf</span>(<span class="dv">1</span> <span class="sc">-</span> alpha, v1, v2)</span>
<span id="cb117-29"><a href="inferencial.html#cb117-29" tabindex="-1"></a>p_valor_F <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(F0, v1, v2)</span>
<span id="cb117-30"><a href="inferencial.html#cb117-30" tabindex="-1"></a></span>
<span id="cb117-31"><a href="inferencial.html#cb117-31" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb117-32"><a href="inferencial.html#cb117-32" tabindex="-1"></a>  <span class="at">SST =</span> SST,</span>
<span id="cb117-33"><a href="inferencial.html#cb117-33" tabindex="-1"></a>  <span class="at">SSA =</span> SSA,</span>
<span id="cb117-34"><a href="inferencial.html#cb117-34" tabindex="-1"></a>  <span class="at">SSE =</span> SSE,</span>
<span id="cb117-35"><a href="inferencial.html#cb117-35" tabindex="-1"></a>  <span class="at">MSA =</span> MSA,</span>
<span id="cb117-36"><a href="inferencial.html#cb117-36" tabindex="-1"></a>  <span class="at">MSE =</span> MSE,</span>
<span id="cb117-37"><a href="inferencial.html#cb117-37" tabindex="-1"></a>  <span class="at">estadistico_F_manual =</span> F0,</span>
<span id="cb117-38"><a href="inferencial.html#cb117-38" tabindex="-1"></a>  <span class="at">estadistico_F_aov =</span> <span class="fu">summary</span>(modelo_anova)[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">`</span><span class="at">F value</span><span class="st">`</span>[<span class="dv">1</span>],</span>
<span id="cb117-39"><a href="inferencial.html#cb117-39" tabindex="-1"></a>  <span class="at">F_critico =</span> F_critico,</span>
<span id="cb117-40"><a href="inferencial.html#cb117-40" tabindex="-1"></a>  <span class="at">p_valor_manual =</span> p_valor_F,</span>
<span id="cb117-41"><a href="inferencial.html#cb117-41" tabindex="-1"></a>  <span class="at">p_valor_aov =</span> <span class="fu">summary</span>(modelo_anova)[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span>[<span class="dv">1</span>]</span>
<span id="cb117-42"><a href="inferencial.html#cb117-42" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb117-43"><a href="inferencial.html#cb117-43" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">round</span>(.x, <span class="dv">4</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb117-44"><a href="inferencial.html#cb117-44" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##        SST      SSA      SSE      MSA     MSE estadistico_F_manual
## 1 2545.706 333.4927 2212.214 166.7463 56.7234               2.9396
##   estadistico_F_aov F_critico p_valor_manual p_valor_aov
## 1            2.9396    3.2381         0.0647      0.0647</code></pre>
<p>La suma de cuadrados total (2545.71) se reparte en 333.49 entre grupos y 2212.21 dentro de ellos, lo que da F = 2.94 con 2 y 39 g.l., por debajo del valor crítico de 3.24, y p = 0.065, igual al de <code>aov</code>. Con <span class="math inline">\(\alpha = 0.05\)</span> no se rechaza <span class="math inline">\(H_0\)</span>, aunque por poco.</p>
<p>Como el ANOVA no rechaza, la prueba de Tukey se muestra solo con fines exploratorios, para ver dónde está la diferencia:</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="inferencial.html#cb119-1" tabindex="-1"></a><span class="fu">TukeyHSD</span>(modelo_anova)</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = motor ~ grupo_edad, data = pacientes)
## 
## $grupo_edad
##                             diff        lwr      upr     p adj
## 60 a 70-Menor de 60     1.723622 -5.0950960  8.54234 0.8123573
## Mayor de 70-Menor de 60 6.786979 -0.2804195 13.85438 0.0620229
## Mayor de 70-60 a 70     5.063357 -1.8896889 12.01640 0.1915409</code></pre>
<p>La única comparación que se acerca es mayores de 70 frente a menores de 60: 6.79 puntos de diferencia, p ajustado = 0.062, intervalo de -0.28 a 13.85. Las que involucran al grupo intermedio quedan lejos (p = 0.81 y 0.19).</p>
</div>
<div id="análisis-de-sensibilidad-kruskal-wallis-y-prueba-de-dunn" class="section level3 hasAnchor" number="2.3.5">
<h3><span class="header-section-number">2.3.5</span> Análisis de sensibilidad: Kruskal-Wallis y prueba de Dunn<a href="inferencial.html#an%C3%A1lisis-de-sensibilidad-kruskal-wallis-y-prueba-de-dunn" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Como el resultado quedó al límite y una prueba de normalidad también, repetimos el contraste con Kruskal-Wallis y el post hoc de Dunn con corrección de Bonferroni.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="inferencial.html#cb121-1" tabindex="-1"></a><span class="fu">kruskal.test</span>(motor <span class="sc">~</span> grupo_edad, <span class="at">data =</span> pacientes)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  motor by grupo_edad
## Kruskal-Wallis chi-squared = 6.0185, df = 2, p-value = 0.04933</code></pre>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="inferencial.html#cb123-1" tabindex="-1"></a><span class="fu">dunn.test</span>(<span class="at">x =</span> pacientes<span class="sc">$</span>motor, <span class="at">g =</span> pacientes<span class="sc">$</span>grupo_edad, <span class="at">method =</span> <span class="st">&quot;bonferroni&quot;</span>)</span></code></pre></div>
<pre><code>##   Kruskal-Wallis rank sum test
## 
## data: x and group
## Kruskal-Wallis chi-squared = 6.0185, df = 2, p-value = 0.05
## 
## 
##                     Dunn&#39;s Pairwise Comparison of x by group                    
##                                   (Bonferroni)                                  
## 
## Col Mean-│
## Row Mean │   Menor de    60 a 70
## ─────────┼──────────────────────
##  60 a 70 │  -0.779223
##          │     0.6538 
##          │
## Mayor de │  -2.404721  -1.680100
##          │     0.0243*    0.1394 
## 
## FWER = 0.05
## Reject Ho if adjusted p ≤ FWER/2, where (unadjusted) p = Pr(Z ≥ |z|)</code></pre>
<p>Kruskal-Wallis da <span class="math inline">\(\chi^2\)</span> = 6.02 (2 g.l., p = 0.049), justo por debajo de 0.05, y Dunn señala como única diferencia significativa la de mayores de 70 frente a menores de 60 (z = -2.4, p ajustado = 0.024). Ambas aproximaciones coinciden en la dirección y en el par de grupos; discrepan en si se cruza o no el umbral del 5 %, señal de que con 42 pacientes estamos al límite de la potencia necesaria.</p>
</div>
<div id="tamaño-del-efecto-1" class="section level3 hasAnchor" number="2.3.6">
<h3><span class="header-section-number">2.3.6</span> Tamaño del efecto<a href="inferencial.html#tama%C3%B1o-del-efecto-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="inferencial.html#cb125-1" tabindex="-1"></a>eta_cuadrado_manual <span class="ot">&lt;-</span> SSA <span class="sc">/</span> SST</span>
<span id="cb125-2"><a href="inferencial.html#cb125-2" tabindex="-1"></a>eta_cuadrado_manual</span></code></pre></div>
<pre><code>## [1] 0.131002</code></pre>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="inferencial.html#cb127-1" tabindex="-1"></a><span class="fu">eta_squared</span>(modelo_anova)</span></code></pre></div>
<pre><code>## grupo_edad 
##   0.131002</code></pre>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="inferencial.html#cb129-1" tabindex="-1"></a>pacientes <span class="sc">%&gt;%</span></span>
<span id="cb129-2"><a href="inferencial.html#cb129-2" tabindex="-1"></a>  <span class="fu">kruskal_effsize</span>(motor <span class="sc">~</span> grupo_edad)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 5
##   .y.       n effsize method  magnitude
## * &lt;chr&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;ord&gt;    
## 1 motor    42   0.103 eta2[H] moderate</code></pre>
<p>El eta cuadrado, SSA / SST, es 0.131 (igual al de <code>rstatix</code>): el grupo de edad explica el 13 % de la variabilidad de la severidad entre pacientes, un efecto medio-grande (referencias: 0.01 pequeño, 0.06 medio, 0.14 grande). El basado en el H de Kruskal-Wallis es 0.103, también moderado.</p>
</div>
<div id="conclusión-1" class="section level3 hasAnchor" number="2.3.7">
<h3><span class="header-section-number">2.3.7</span> Conclusión<a href="inferencial.html#conclusi%C3%B3n-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Con una confianza del 95 %, el ANOVA no permite afirmar que la severidad motora difiera entre grupos de edad (F = 2.94, p = 0.065), aunque Kruskal-Wallis sí detecta una diferencia marginal (p = 0.049) entre los mayores de 70 y los menores de 60. El tamaño del efecto (eta cuadrado = 0.13, casi 7 puntos entre extremos) indica que la diferencia es relevante en la práctica y que lo que falta es muestra, no relación: es coherente con la correlación positiva entre edad y <code>motor_UPDRS</code> que ya aparecía en el exploratorio.</p>
</div>
</div>
<div id="objetivo-3-severidad-motora-según-el-nivel-de-inestabilidad-vocal" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Objetivo 3: severidad motora según el nivel de inestabilidad vocal<a href="inferencial.html#objetivo-3-severidad-motora-seg%C3%BAn-el-nivel-de-inestabilidad-vocal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>¿Tienen los pacientes con alta inestabilidad vocal una severidad motora distinta de los de baja inestabilidad? Lo contrastamos por separado para el índice de jitter (frecuencia) y el de shimmer (amplitud):</p>
<p><span class="math display">\[H_0: \mu_{\text{Alto}} = \mu_{\text{Bajo}} \qquad H_1: \mu_{\text{Alto}} \neq \mu_{\text{Bajo}}\]</span></p>
<div id="análisis-exploratorio-2" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Análisis exploratorio<a href="inferencial.html#an%C3%A1lisis-exploratorio-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="inferencial.html#cb131-1" tabindex="-1"></a><span class="fu">resumen_grupo</span>(pacientes, <span class="st">&quot;nivel_jitter&quot;</span>)</span></code></pre></div>
<pre><code>##   nivel_jitter  n promedio    ds mediana    RIC   min    max
## 1         Bajo 21   19.244 7.935  18.988 12.944 5.823 31.899
## 2         Alto 21   22.661 7.628  24.502 12.225 8.706 35.990</code></pre>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="inferencial.html#cb133-1" tabindex="-1"></a><span class="fu">resumen_grupo</span>(pacientes, <span class="st">&quot;nivel_shimmer&quot;</span>)</span></code></pre></div>
<pre><code>##   nivel_shimmer  n promedio    ds mediana    RIC   min    max
## 1          Bajo 21   20.196 8.272  19.517 13.700 5.823 31.899
## 2          Alto 21   21.709 7.593  19.887 10.357 8.706 35.990</code></pre>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="inferencial.html#cb135-1" tabindex="-1"></a>p_jitter <span class="ot">&lt;-</span> pacientes <span class="sc">%&gt;%</span></span>
<span id="cb135-2"><a href="inferencial.html#cb135-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> nivel_jitter, <span class="at">y =</span> motor)) <span class="sc">+</span></span>
<span id="cb135-3"><a href="inferencial.html#cb135-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#FAD0C4&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#C2185B&quot;</span>, <span class="at">width =</span> <span class="fl">0.4</span>,</span>
<span id="cb135-4"><a href="inferencial.html#cb135-4" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&quot;#8E0038&quot;</span>) <span class="sc">+</span></span>
<span id="cb135-5"><a href="inferencial.html#cb135-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="at">color =</span> <span class="st">&quot;#8E0038&quot;</span>) <span class="sc">+</span></span>
<span id="cb135-6"><a href="inferencial.html#cb135-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Según el nivel del índice de jitter&quot;</span>,</span>
<span id="cb135-7"><a href="inferencial.html#cb135-7" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Nivel de inestabilidad de la frecuencia&quot;</span>,</span>
<span id="cb135-8"><a href="inferencial.html#cb135-8" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Motor UPDRS promedio (Puntos)&quot;</span>) <span class="sc">+</span></span>
<span id="cb135-9"><a href="inferencial.html#cb135-9" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb135-10"><a href="inferencial.html#cb135-10" tabindex="-1"></a></span>
<span id="cb135-11"><a href="inferencial.html#cb135-11" tabindex="-1"></a>p_shimmer <span class="ot">&lt;-</span> pacientes <span class="sc">%&gt;%</span></span>
<span id="cb135-12"><a href="inferencial.html#cb135-12" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> nivel_shimmer, <span class="at">y =</span> motor)) <span class="sc">+</span></span>
<span id="cb135-13"><a href="inferencial.html#cb135-13" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#FAD0C4&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#C2185B&quot;</span>, <span class="at">width =</span> <span class="fl">0.4</span>,</span>
<span id="cb135-14"><a href="inferencial.html#cb135-14" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&quot;#8E0038&quot;</span>) <span class="sc">+</span></span>
<span id="cb135-15"><a href="inferencial.html#cb135-15" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="at">color =</span> <span class="st">&quot;#8E0038&quot;</span>) <span class="sc">+</span></span>
<span id="cb135-16"><a href="inferencial.html#cb135-16" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Según el nivel del índice de shimmer&quot;</span>,</span>
<span id="cb135-17"><a href="inferencial.html#cb135-17" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Nivel de inestabilidad de la amplitud&quot;</span>,</span>
<span id="cb135-18"><a href="inferencial.html#cb135-18" tabindex="-1"></a>       <span class="at">y =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb135-19"><a href="inferencial.html#cb135-19" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb135-20"><a href="inferencial.html#cb135-20" tabindex="-1"></a></span>
<span id="cb135-21"><a href="inferencial.html#cb135-21" tabindex="-1"></a>p_jitter <span class="sc">+</span> p_shimmer</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/inf-voz-boxplot-1.png" alt="" width="960" /></p>
<p>Con jitter alto la severidad promedio es 22.66 (mediana 24.5) frente a 19.24 (mediana 18.99) con jitter bajo: 3.4 puntos de diferencia en las medias y 5.5 en las medianas, con dispersiones casi iguales. Con el shimmer la brecha es menor: 21.71 frente a 20.2. En los cuatro grupos el rango es amplio, no hay atípicos y las cajas se solapan bastante.</p>
</div>
<div id="supuesto-de-normalidad-2" class="section level3 hasAnchor" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Supuesto de normalidad<a href="inferencial.html#supuesto-de-normalidad-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="inferencial.html#cb136-1" tabindex="-1"></a><span class="fu">normalidad_grupo</span>(pacientes, <span class="st">&quot;nivel_jitter&quot;</span>)</span></code></pre></div>
<pre><code>##   nivel_jitter  n est_w  p_sw est_ks  p_ks est_l   p_l
## 1         Bajo 21 0.946 0.287  0.128 0.839 0.128 0.492
## 2         Alto 21 0.966 0.645  0.119 0.893 0.119 0.608</code></pre>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="inferencial.html#cb138-1" tabindex="-1"></a><span class="fu">normalidad_grupo</span>(pacientes, <span class="st">&quot;nivel_shimmer&quot;</span>)</span></code></pre></div>
<pre><code>##   nivel_shimmer  n est_w  p_sw est_ks  p_ks est_l   p_l
## 1          Bajo 21 0.929 0.132  0.155 0.636 0.155 0.206
## 2          Alto 21 0.972 0.785  0.119 0.896 0.119 0.616</code></pre>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="inferencial.html#cb140-1" tabindex="-1"></a>pacientes <span class="sc">%&gt;%</span></span>
<span id="cb140-2"><a href="inferencial.html#cb140-2" tabindex="-1"></a>  <span class="fu">select</span>(motor, nivel_jitter, nivel_shimmer) <span class="sc">%&gt;%</span></span>
<span id="cb140-3"><a href="inferencial.html#cb140-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(nivel_jitter, nivel_shimmer),</span>
<span id="cb140-4"><a href="inferencial.html#cb140-4" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">&quot;indice&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;nivel&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb140-5"><a href="inferencial.html#cb140-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">indice =</span> <span class="fu">if_else</span>(indice <span class="sc">==</span> <span class="st">&quot;nivel_jitter&quot;</span>, <span class="st">&quot;Jitter&quot;</span>, <span class="st">&quot;Shimmer&quot;</span>),</span>
<span id="cb140-6"><a href="inferencial.html#cb140-6" tabindex="-1"></a>         <span class="at">grupo =</span> <span class="fu">paste</span>(indice, nivel)) <span class="sc">%&gt;%</span></span>
<span id="cb140-7"><a href="inferencial.html#cb140-7" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> motor)) <span class="sc">+</span></span>
<span id="cb140-8"><a href="inferencial.html#cb140-8" tabindex="-1"></a>  <span class="fu">stat_qq</span>(<span class="at">color =</span> <span class="st">&quot;#C77D98&quot;</span>) <span class="sc">+</span></span>
<span id="cb140-9"><a href="inferencial.html#cb140-9" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="at">color =</span> <span class="st">&quot;#8F4A68&quot;</span>) <span class="sc">+</span></span>
<span id="cb140-10"><a href="inferencial.html#cb140-10" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> grupo, <span class="at">nrow =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb140-11"><a href="inferencial.html#cb140-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Gráficos cuantil-cuantil de la severidad motora por nivel de inestabilidad vocal&quot;</span>,</span>
<span id="cb140-12"><a href="inferencial.html#cb140-12" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Cuantiles teóricos&quot;</span>,</span>
<span id="cb140-13"><a href="inferencial.html#cb140-13" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Cuantiles muestrales&quot;</span>) <span class="sc">+</span></span>
<span id="cb140-14"><a href="inferencial.html#cb140-14" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/inf-voz-qq-1.png" alt="" width="960" /></p>
<p>Nada rechaza la normalidad: Shapiro-Wilk da p = 0.287 y 0.645 para jitter bajo y alto, y 0.132 y 0.785 para shimmer; las otras dos pruebas superan 0.2 en todos los casos y los QQ-plots se ajustan bien a la recta.</p>
</div>
<div id="supuesto-de-homocedasticidad-2" class="section level3 hasAnchor" number="2.4.3">
<h3><span class="header-section-number">2.4.3</span> Supuesto de homocedasticidad<a href="inferencial.html#supuesto-de-homocedasticidad-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="inferencial.html#cb141-1" tabindex="-1"></a>motor_jitter_alto <span class="ot">&lt;-</span> pacientes <span class="sc">%&gt;%</span> <span class="fu">filter</span>(nivel_jitter <span class="sc">==</span> <span class="st">&quot;Alto&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(motor)</span>
<span id="cb141-2"><a href="inferencial.html#cb141-2" tabindex="-1"></a>motor_jitter_bajo <span class="ot">&lt;-</span> pacientes <span class="sc">%&gt;%</span> <span class="fu">filter</span>(nivel_jitter <span class="sc">==</span> <span class="st">&quot;Bajo&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(motor)</span>
<span id="cb141-3"><a href="inferencial.html#cb141-3" tabindex="-1"></a>motor_shimmer_alto <span class="ot">&lt;-</span> pacientes <span class="sc">%&gt;%</span> <span class="fu">filter</span>(nivel_shimmer <span class="sc">==</span> <span class="st">&quot;Alto&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(motor)</span>
<span id="cb141-4"><a href="inferencial.html#cb141-4" tabindex="-1"></a>motor_shimmer_bajo <span class="ot">&lt;-</span> pacientes <span class="sc">%&gt;%</span> <span class="fu">filter</span>(nivel_shimmer <span class="sc">==</span> <span class="st">&quot;Bajo&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(motor)</span>
<span id="cb141-5"><a href="inferencial.html#cb141-5" tabindex="-1"></a></span>
<span id="cb141-6"><a href="inferencial.html#cb141-6" tabindex="-1"></a><span class="fu">var.test</span>(motor_jitter_alto, motor_jitter_bajo)</span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  motor_jitter_alto and motor_jitter_bajo
## F = 0.92426, num df = 20, denom df = 20, p-value = 0.8619
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.3750316 2.2778233
## sample estimates:
## ratio of variances 
##          0.9242596</code></pre>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="inferencial.html#cb143-1" tabindex="-1"></a><span class="fu">leveneTest</span>(motor <span class="sc">~</span> nivel_jitter, <span class="at">data =</span> pacientes, <span class="at">center =</span> median)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  1  0.0528 0.8195
##       40</code></pre>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="inferencial.html#cb145-1" tabindex="-1"></a><span class="fu">var.test</span>(motor_shimmer_alto, motor_shimmer_bajo)</span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  motor_shimmer_alto and motor_shimmer_bajo
## F = 0.8427, num df = 20, denom df = 20, p-value = 0.7056
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.341937 2.076817
## sample estimates:
## ratio of variances 
##          0.8426984</code></pre>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="inferencial.html#cb147-1" tabindex="-1"></a><span class="fu">leveneTest</span>(motor <span class="sc">~</span> nivel_shimmer, <span class="at">data =</span> pacientes, <span class="at">center =</span> median)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  1  0.5478 0.4635
##       40</code></pre>
<p>Para el jitter la razón de varianzas es 0.92 (p = 0.862; Levene p = 0.82) y para el shimmer 0.84 (p = 0.706; Levene p = 0.464). En ambos casos se mantiene la homocedasticidad y usamos la t de Student con varianzas iguales.</p>
</div>
<div id="prueba-de-hipótesis-t-de-student-1" class="section level3 hasAnchor" number="2.4.4">
<h3><span class="header-section-number">2.4.4</span> Prueba de hipótesis: t de Student<a href="inferencial.html#prueba-de-hip%C3%B3tesis-t-de-student-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La verificación manual es idéntica a la del objetivo 1, así que aquí mostramos directamente <code>t.test</code> junto con Mann-Whitney como análisis de sensibilidad.</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="inferencial.html#cb149-1" tabindex="-1"></a>prueba_t_jitter <span class="ot">&lt;-</span> <span class="fu">t.test</span>(<span class="at">x =</span> motor_jitter_alto, <span class="at">y =</span> motor_jitter_bajo,</span>
<span id="cb149-2"><a href="inferencial.html#cb149-2" tabindex="-1"></a>                          <span class="at">var.equal =</span> <span class="cn">TRUE</span>, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span>
<span id="cb149-3"><a href="inferencial.html#cb149-3" tabindex="-1"></a>prueba_t_jitter</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  motor_jitter_alto and motor_jitter_bajo
## t = 1.4228, df = 40, p-value = 0.1626
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1.437130  8.271818
## sample estimates:
## mean of x mean of y 
##  22.66097  19.24363</code></pre>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="inferencial.html#cb151-1" tabindex="-1"></a><span class="fu">wilcox.test</span>(<span class="at">x =</span> motor_jitter_alto, <span class="at">y =</span> motor_jitter_bajo, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum exact test
## 
## data:  motor_jitter_alto and motor_jitter_bajo
## W = 276, p-value = 0.1682
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="inferencial.html#cb153-1" tabindex="-1"></a>prueba_t_shimmer <span class="ot">&lt;-</span> <span class="fu">t.test</span>(<span class="at">x =</span> motor_shimmer_alto, <span class="at">y =</span> motor_shimmer_bajo,</span>
<span id="cb153-2"><a href="inferencial.html#cb153-2" tabindex="-1"></a>                           <span class="at">var.equal =</span> <span class="cn">TRUE</span>, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span>
<span id="cb153-3"><a href="inferencial.html#cb153-3" tabindex="-1"></a>prueba_t_shimmer</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  motor_shimmer_alto and motor_shimmer_bajo
## t = 0.61732, df = 40, p-value = 0.5405
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -3.439625  6.464885
## sample estimates:
## mean of x mean of y 
##  21.70862  20.19599</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="inferencial.html#cb155-1" tabindex="-1"></a><span class="fu">wilcox.test</span>(<span class="at">x =</span> motor_shimmer_alto, <span class="at">y =</span> motor_shimmer_bajo, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum exact test
## 
## data:  motor_shimmer_alto and motor_shimmer_bajo
## W = 243, p-value = 0.5837
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>Para el jitter, t = 1.423 (40 g.l., p = 0.163): 3.42 puntos más en el grupo alto, con un intervalo de -1.44 a 8.27 que incluye al 0; Mann-Whitney coincide (W = 276, p = 0.168). Para el shimmer, t = 0.617 (p = 0.541), 1.51 puntos de diferencia e intervalo de -3.44 a 6.46; Mann-Whitney da W = 243 y p = 0.584. No se rechaza <span class="math inline">\(H_0\)</span> en ningún caso.</p>
</div>
<div id="tamaño-del-efecto-2" class="section level3 hasAnchor" number="2.4.5">
<h3><span class="header-section-number">2.4.5</span> Tamaño del efecto<a href="inferencial.html#tama%C3%B1o-del-efecto-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="inferencial.html#cb157-1" tabindex="-1"></a>d_jitter <span class="ot">&lt;-</span> <span class="fu">cohen.d</span>(motor_jitter_alto, motor_jitter_bajo, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span>
<span id="cb157-2"><a href="inferencial.html#cb157-2" tabindex="-1"></a>d_jitter</span></code></pre></div>
<pre><code>## 
## Cohen&#39;s d
## 
## d estimate: 0.4390706 (small)
## 95 percent confidence interval:
##      lower      upper 
## -0.1921172  1.0702584</code></pre>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="inferencial.html#cb159-1" tabindex="-1"></a>d_shimmer <span class="ot">&lt;-</span> <span class="fu">cohen.d</span>(motor_shimmer_alto, motor_shimmer_bajo, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span>
<span id="cb159-2"><a href="inferencial.html#cb159-2" tabindex="-1"></a>d_shimmer</span></code></pre></div>
<pre><code>## 
## Cohen&#39;s d
## 
## d estimate: 0.1905099 (negligible)
## 95 percent confidence interval:
##      lower      upper 
## -0.4346207  0.8156405</code></pre>
<p>La d de Cohen es 0.44 para el jitter, un efecto pequeño que roza el medio (intervalo de -0.19 a 1.07), y 0.19 para el shimmer, despreciable (intervalo de -0.43 a 0.82). Ambos intervalos incluyen al 0.</p>
</div>
<div id="conclusión-2" class="section level3 hasAnchor" number="2.4.6">
<h3><span class="header-section-number">2.4.6</span> Conclusión<a href="inferencial.html#conclusi%C3%B3n-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Con una confianza del 95 %, no hay evidencia de que la severidad motora difiera entre pacientes con alta y baja inestabilidad vocal, ni en frecuencia (jitter: t = 1.42, p = 0.163) ni en amplitud (shimmer: t = 0.62, p = 0.541). Los tamaños del efecto sí los distinguen: el del shimmer es despreciable (d = 0.19), pero el del jitter (d = 0.44, 3.4 puntos más de severidad) no es trivial; con 21 pacientes por grupo no alcanza la significancia, pero va en la misma dirección que la asociación débil entre jitter y <code>motor_UPDRS</code> que vimos en el exploratorio.</p>
</div>
</div>
<div id="objetivo-4-evolución-de-la-severidad-motora-durante-el-seguimiento" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Objetivo 4: evolución de la severidad motora durante el seguimiento<a href="inferencial.html#objetivo-4-evoluci%C3%B3n-de-la-severidad-motora-durante-el-seguimiento" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>¿Cambia la severidad motora entre la primera y la última grabación de cada paciente? Las separan entre 153 y 204 días (mediana 170, unos seis meses). Como son dos medidas del mismo paciente, los datos son pareados y la hipótesis se plantea sobre la media de las diferencias:</p>
<p><span class="math display">\[H_0: \mu_{\text{final} - \text{inicio}} = 0 \qquad H_1: \mu_{\text{final} - \text{inicio}} \neq 0\]</span></p>
<div id="análisis-exploratorio-3" class="section level3 hasAnchor" number="2.5.1">
<h3><span class="header-section-number">2.5.1</span> Análisis exploratorio<a href="inferencial.html#an%C3%A1lisis-exploratorio-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="inferencial.html#cb161-1" tabindex="-1"></a>pacientes <span class="ot">&lt;-</span> pacientes <span class="sc">%&gt;%</span></span>
<span id="cb161-2"><a href="inferencial.html#cb161-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diferencia =</span> motor_final <span class="sc">-</span> motor_inicio)</span>
<span id="cb161-3"><a href="inferencial.html#cb161-3" tabindex="-1"></a></span>
<span id="cb161-4"><a href="inferencial.html#cb161-4" tabindex="-1"></a>pacientes <span class="sc">%&gt;%</span></span>
<span id="cb161-5"><a href="inferencial.html#cb161-5" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb161-6"><a href="inferencial.html#cb161-6" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb161-7"><a href="inferencial.html#cb161-7" tabindex="-1"></a>    <span class="at">promedio_inicio =</span> <span class="fu">mean</span>(motor_inicio),</span>
<span id="cb161-8"><a href="inferencial.html#cb161-8" tabindex="-1"></a>    <span class="at">promedio_final =</span> <span class="fu">mean</span>(motor_final),</span>
<span id="cb161-9"><a href="inferencial.html#cb161-9" tabindex="-1"></a>    <span class="at">sd_inicio =</span> <span class="fu">sd</span>(motor_inicio),</span>
<span id="cb161-10"><a href="inferencial.html#cb161-10" tabindex="-1"></a>    <span class="at">sd_final =</span> <span class="fu">sd</span>(motor_final),</span>
<span id="cb161-11"><a href="inferencial.html#cb161-11" tabindex="-1"></a>    <span class="at">mediana_inicio =</span> <span class="fu">median</span>(motor_inicio),</span>
<span id="cb161-12"><a href="inferencial.html#cb161-12" tabindex="-1"></a>    <span class="at">mediana_final =</span> <span class="fu">median</span>(motor_final),</span>
<span id="cb161-13"><a href="inferencial.html#cb161-13" tabindex="-1"></a>    <span class="at">min_inicio =</span> <span class="fu">min</span>(motor_inicio),</span>
<span id="cb161-14"><a href="inferencial.html#cb161-14" tabindex="-1"></a>    <span class="at">max_inicio =</span> <span class="fu">max</span>(motor_inicio),</span>
<span id="cb161-15"><a href="inferencial.html#cb161-15" tabindex="-1"></a>    <span class="at">min_final =</span> <span class="fu">min</span>(motor_final),</span>
<span id="cb161-16"><a href="inferencial.html#cb161-16" tabindex="-1"></a>    <span class="at">max_final =</span> <span class="fu">max</span>(motor_final)</span>
<span id="cb161-17"><a href="inferencial.html#cb161-17" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb161-18"><a href="inferencial.html#cb161-18" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">round</span>(.x, <span class="dv">3</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb161-19"><a href="inferencial.html#cb161-19" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##    n promedio_inicio promedio_final sd_inicio sd_final mediana_inicio
## 1 42          19.578         21.655     7.974    8.795         18.675
##   mediana_final min_inicio max_inicio min_final max_final
## 1        19.922          6     36.073     5.038    39.511</code></pre>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="inferencial.html#cb163-1" tabindex="-1"></a>pacientes <span class="sc">%&gt;%</span></span>
<span id="cb163-2"><a href="inferencial.html#cb163-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb163-3"><a href="inferencial.html#cb163-3" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb163-4"><a href="inferencial.html#cb163-4" tabindex="-1"></a>    <span class="at">promedio_diferencia =</span> <span class="fu">mean</span>(diferencia),</span>
<span id="cb163-5"><a href="inferencial.html#cb163-5" tabindex="-1"></a>    <span class="at">sd_diferencia =</span> <span class="fu">sd</span>(diferencia),</span>
<span id="cb163-6"><a href="inferencial.html#cb163-6" tabindex="-1"></a>    <span class="at">mediana_diferencia =</span> <span class="fu">median</span>(diferencia),</span>
<span id="cb163-7"><a href="inferencial.html#cb163-7" tabindex="-1"></a>    <span class="at">min_diferencia =</span> <span class="fu">min</span>(diferencia),</span>
<span id="cb163-8"><a href="inferencial.html#cb163-8" tabindex="-1"></a>    <span class="at">max_diferencia =</span> <span class="fu">max</span>(diferencia),</span>
<span id="cb163-9"><a href="inferencial.html#cb163-9" tabindex="-1"></a>    <span class="at">pacientes_que_aumentan =</span> <span class="fu">sum</span>(diferencia <span class="sc">&gt;</span> <span class="dv">0</span>),</span>
<span id="cb163-10"><a href="inferencial.html#cb163-10" tabindex="-1"></a>    <span class="at">pacientes_que_disminuyen =</span> <span class="fu">sum</span>(diferencia <span class="sc">&lt;</span> <span class="dv">0</span>)</span>
<span id="cb163-11"><a href="inferencial.html#cb163-11" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb163-12"><a href="inferencial.html#cb163-12" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">round</span>(.x, <span class="dv">3</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb163-13"><a href="inferencial.html#cb163-13" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##    n promedio_diferencia sd_diferencia mediana_diferencia min_diferencia
## 1 42               2.076         6.232              2.049        -13.118
##   max_diferencia pacientes_que_aumentan pacientes_que_disminuyen
## 1         14.702                     27                       15</code></pre>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="inferencial.html#cb165-1" tabindex="-1"></a>p_trayectorias <span class="ot">&lt;-</span> pacientes <span class="sc">%&gt;%</span></span>
<span id="cb165-2"><a href="inferencial.html#cb165-2" tabindex="-1"></a>  <span class="fu">select</span>(subject., motor_inicio, motor_final) <span class="sc">%&gt;%</span></span>
<span id="cb165-3"><a href="inferencial.html#cb165-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(motor_inicio, motor_final),</span>
<span id="cb165-4"><a href="inferencial.html#cb165-4" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">&quot;momento&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;motor&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb165-5"><a href="inferencial.html#cb165-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">momento =</span> <span class="fu">factor</span>(momento,</span>
<span id="cb165-6"><a href="inferencial.html#cb165-6" tabindex="-1"></a>                          <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;motor_inicio&quot;</span>, <span class="st">&quot;motor_final&quot;</span>),</span>
<span id="cb165-7"><a href="inferencial.html#cb165-7" tabindex="-1"></a>                          <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Primera grabación&quot;</span>, <span class="st">&quot;Última grabación&quot;</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb165-8"><a href="inferencial.html#cb165-8" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> momento, <span class="at">y =</span> motor, <span class="at">group =</span> subject.)) <span class="sc">+</span></span>
<span id="cb165-9"><a href="inferencial.html#cb165-9" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;gray75&quot;</span>) <span class="sc">+</span></span>
<span id="cb165-10"><a href="inferencial.html#cb165-10" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;#C77D98&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb165-11"><a href="inferencial.html#cb165-11" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;line&quot;</span>,</span>
<span id="cb165-12"><a href="inferencial.html#cb165-12" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">&quot;#8E0038&quot;</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb165-13"><a href="inferencial.html#cb165-13" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>,</span>
<span id="cb165-14"><a href="inferencial.html#cb165-14" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">&quot;#8E0038&quot;</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="at">shape =</span> <span class="dv">18</span>) <span class="sc">+</span></span>
<span id="cb165-15"><a href="inferencial.html#cb165-15" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Severidad motora al inicio y al final del seguimiento&quot;</span>,</span>
<span id="cb165-16"><a href="inferencial.html#cb165-16" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Una línea gris por paciente; en rojo, el promedio&quot;</span>,</span>
<span id="cb165-17"><a href="inferencial.html#cb165-17" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb165-18"><a href="inferencial.html#cb165-18" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Motor UPDRS (Puntos)&quot;</span>) <span class="sc">+</span></span>
<span id="cb165-19"><a href="inferencial.html#cb165-19" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb165-20"><a href="inferencial.html#cb165-20" tabindex="-1"></a></span>
<span id="cb165-21"><a href="inferencial.html#cb165-21" tabindex="-1"></a>p_diferencias <span class="ot">&lt;-</span> pacientes <span class="sc">%&gt;%</span></span>
<span id="cb165-22"><a href="inferencial.html#cb165-22" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> diferencia)) <span class="sc">+</span></span>
<span id="cb165-23"><a href="inferencial.html#cb165-23" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">12</span>, <span class="at">fill =</span> <span class="st">&quot;#FAD0C4&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#E8A598&quot;</span>) <span class="sc">+</span></span>
<span id="cb165-24"><a href="inferencial.html#cb165-24" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;gray40&quot;</span>) <span class="sc">+</span></span>
<span id="cb165-25"><a href="inferencial.html#cb165-25" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(pacientes<span class="sc">$</span>diferencia), <span class="at">color =</span> <span class="st">&quot;#8E0038&quot;</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb165-26"><a href="inferencial.html#cb165-26" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Diferencias final - inicio por paciente&quot;</span>,</span>
<span id="cb165-27"><a href="inferencial.html#cb165-27" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Línea roja: diferencia promedio&quot;</span>,</span>
<span id="cb165-28"><a href="inferencial.html#cb165-28" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Diferencia en motor UPDRS (Puntos)&quot;</span>,</span>
<span id="cb165-29"><a href="inferencial.html#cb165-29" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Número de pacientes&quot;</span>) <span class="sc">+</span></span>
<span id="cb165-30"><a href="inferencial.html#cb165-30" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb165-31"><a href="inferencial.html#cb165-31" tabindex="-1"></a></span>
<span id="cb165-32"><a href="inferencial.html#cb165-32" tabindex="-1"></a>p_trayectorias <span class="sc">+</span> p_diferencias</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/inf-pareado-grafico-1.png" alt="" width="960" /></p>
<p>La severidad promedio pasa de 19.58 puntos en la primera grabación a 21.65 en la última: un aumento medio de 2.08 puntos (mediana 2.05, desviación 6.23). No es parejo: 27 de los 42 pacientes (64 %) empeoran y 15 mejoran, con cambios individuales entre -13.12 y 14.7 puntos, como se ve en las trayectorias.</p>
</div>
<div id="supuesto-de-normalidad-de-las-diferencias" class="section level3 hasAnchor" number="2.5.2">
<h3><span class="header-section-number">2.5.2</span> Supuesto de normalidad de las diferencias<a href="inferencial.html#supuesto-de-normalidad-de-las-diferencias" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="inferencial.html#cb166-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(pacientes<span class="sc">$</span>diferencia)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  pacientes$diferencia
## W = 0.98746, p-value = 0.9196</code></pre>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="inferencial.html#cb168-1" tabindex="-1"></a><span class="fu">ks.test</span>(<span class="fu">scale</span>(pacientes<span class="sc">$</span>diferencia), <span class="st">&quot;pnorm&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Exact one-sample Kolmogorov-Smirnov test
## 
## data:  scale(pacientes$diferencia)
## D = 0.061129, p-value = 0.9948
## alternative hypothesis: two-sided</code></pre>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="inferencial.html#cb170-1" tabindex="-1"></a><span class="fu">lillie.test</span>(pacientes<span class="sc">$</span>diferencia)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  pacientes$diferencia
## D = 0.061129, p-value = 0.9583</code></pre>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="inferencial.html#cb172-1" tabindex="-1"></a>pacientes <span class="sc">%&gt;%</span></span>
<span id="cb172-2"><a href="inferencial.html#cb172-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> diferencia)) <span class="sc">+</span></span>
<span id="cb172-3"><a href="inferencial.html#cb172-3" tabindex="-1"></a>  <span class="fu">stat_qq</span>(<span class="at">color =</span> <span class="st">&quot;#C77D98&quot;</span>) <span class="sc">+</span></span>
<span id="cb172-4"><a href="inferencial.html#cb172-4" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="at">color =</span> <span class="st">&quot;#8F4A68&quot;</span>) <span class="sc">+</span></span>
<span id="cb172-5"><a href="inferencial.html#cb172-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Gráfico cuantil-cuantil de las diferencias final - inicio&quot;</span>,</span>
<span id="cb172-6"><a href="inferencial.html#cb172-6" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Cuantiles teóricos&quot;</span>,</span>
<span id="cb172-7"><a href="inferencial.html#cb172-7" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Cuantiles muestrales&quot;</span>) <span class="sc">+</span></span>
<span id="cb172-8"><a href="inferencial.html#cb172-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/inf-pareado-qq-1.png" alt="" width="672" /></p>
<p>Las diferencias se ajustan muy bien a la normal: Shapiro-Wilk da W = 0.987 (p = 0.92), Kolmogorov-Smirnov p = 0.995 y Lilliefors p = 0.958, y el QQ-plot es prácticamente una recta. Se cumple el supuesto de la t pareada.</p>
</div>
<div id="prueba-de-hipótesis-t-pareada" class="section level3 hasAnchor" number="2.5.3">
<h3><span class="header-section-number">2.5.3</span> Prueba de hipótesis: t pareada<a href="inferencial.html#prueba-de-hip%C3%B3tesis-t-pareada" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="inferencial.html#cb173-1" tabindex="-1"></a>prueba_t_pareada <span class="ot">&lt;-</span> <span class="fu">t.test</span>(<span class="at">x =</span> pacientes<span class="sc">$</span>motor_final, <span class="at">y =</span> pacientes<span class="sc">$</span>motor_inicio,</span>
<span id="cb173-2"><a href="inferencial.html#cb173-2" tabindex="-1"></a>                           <span class="at">paired =</span> <span class="cn">TRUE</span>)</span>
<span id="cb173-3"><a href="inferencial.html#cb173-3" tabindex="-1"></a>prueba_t_pareada</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  pacientes$motor_final and pacientes$motor_inicio
## t = 2.1593, df = 41, p-value = 0.03673
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  0.1343808 4.0181525
## sample estimates:
## mean difference 
##        2.076267</code></pre>
<p>Verificación con el teorema de la diferencia de medias para datos pareados:</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="inferencial.html#cb175-1" tabindex="-1"></a>n_pareado <span class="ot">&lt;-</span> <span class="fu">nrow</span>(pacientes)</span>
<span id="cb175-2"><a href="inferencial.html#cb175-2" tabindex="-1"></a>media_diff <span class="ot">&lt;-</span> <span class="fu">mean</span>(pacientes<span class="sc">$</span>diferencia)</span>
<span id="cb175-3"><a href="inferencial.html#cb175-3" tabindex="-1"></a>sd_diff <span class="ot">&lt;-</span> <span class="fu">sd</span>(pacientes<span class="sc">$</span>diferencia)</span>
<span id="cb175-4"><a href="inferencial.html#cb175-4" tabindex="-1"></a>se_diff <span class="ot">&lt;-</span> sd_diff <span class="sc">/</span> <span class="fu">sqrt</span>(n_pareado)</span>
<span id="cb175-5"><a href="inferencial.html#cb175-5" tabindex="-1"></a></span>
<span id="cb175-6"><a href="inferencial.html#cb175-6" tabindex="-1"></a>t0 <span class="ot">&lt;-</span> media_diff <span class="sc">/</span> se_diff</span>
<span id="cb175-7"><a href="inferencial.html#cb175-7" tabindex="-1"></a>df_pareado <span class="ot">&lt;-</span> n_pareado <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb175-8"><a href="inferencial.html#cb175-8" tabindex="-1"></a>pvalor_pareado <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="fu">abs</span>(t0), <span class="at">df =</span> df_pareado, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb175-9"><a href="inferencial.html#cb175-9" tabindex="-1"></a></span>
<span id="cb175-10"><a href="inferencial.html#cb175-10" tabindex="-1"></a>t_critico <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="dv">1</span> <span class="sc">-</span> alpha <span class="sc">/</span> <span class="dv">2</span>, <span class="at">df =</span> df_pareado)</span>
<span id="cb175-11"><a href="inferencial.html#cb175-11" tabindex="-1"></a>int_inf_pareado <span class="ot">&lt;-</span> media_diff <span class="sc">-</span> t_critico <span class="sc">*</span> se_diff</span>
<span id="cb175-12"><a href="inferencial.html#cb175-12" tabindex="-1"></a>int_sup_pareado <span class="ot">&lt;-</span> media_diff <span class="sc">+</span> t_critico <span class="sc">*</span> se_diff</span>
<span id="cb175-13"><a href="inferencial.html#cb175-13" tabindex="-1"></a></span>
<span id="cb175-14"><a href="inferencial.html#cb175-14" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb175-15"><a href="inferencial.html#cb175-15" tabindex="-1"></a>  <span class="at">estadistico_t_manual =</span> t0,</span>
<span id="cb175-16"><a href="inferencial.html#cb175-16" tabindex="-1"></a>  <span class="at">estadistico_t_t_test =</span> <span class="fu">unname</span>(prueba_t_pareada<span class="sc">$</span>statistic),</span>
<span id="cb175-17"><a href="inferencial.html#cb175-17" tabindex="-1"></a>  <span class="at">grados_libertad_manual =</span> df_pareado,</span>
<span id="cb175-18"><a href="inferencial.html#cb175-18" tabindex="-1"></a>  <span class="at">grados_libertad_t_test =</span> <span class="fu">unname</span>(prueba_t_pareada<span class="sc">$</span>parameter),</span>
<span id="cb175-19"><a href="inferencial.html#cb175-19" tabindex="-1"></a>  <span class="at">p_valor_manual =</span> pvalor_pareado,</span>
<span id="cb175-20"><a href="inferencial.html#cb175-20" tabindex="-1"></a>  <span class="at">p_valor_t_test =</span> prueba_t_pareada<span class="sc">$</span>p.value,</span>
<span id="cb175-21"><a href="inferencial.html#cb175-21" tabindex="-1"></a>  <span class="at">IC_inferior_manual =</span> int_inf_pareado,</span>
<span id="cb175-22"><a href="inferencial.html#cb175-22" tabindex="-1"></a>  <span class="at">IC_superior_manual =</span> int_sup_pareado,</span>
<span id="cb175-23"><a href="inferencial.html#cb175-23" tabindex="-1"></a>  <span class="at">IC_inferior_t_test =</span> prueba_t_pareada<span class="sc">$</span>conf.int[<span class="dv">1</span>],</span>
<span id="cb175-24"><a href="inferencial.html#cb175-24" tabindex="-1"></a>  <span class="at">IC_superior_t_test =</span> prueba_t_pareada<span class="sc">$</span>conf.int[<span class="dv">2</span>]</span>
<span id="cb175-25"><a href="inferencial.html#cb175-25" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb175-26"><a href="inferencial.html#cb175-26" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">round</span>(.x, <span class="dv">4</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb175-27"><a href="inferencial.html#cb175-27" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   estadistico_t_manual estadistico_t_t_test grados_libertad_manual
## 1               2.1593               2.1593                     41
##   grados_libertad_t_test p_valor_manual p_valor_t_test IC_inferior_manual
## 1                     41         0.0367         0.0367             0.1344
##   IC_superior_manual IC_inferior_t_test IC_superior_t_test
## 1             4.0182             0.1344             4.0182</code></pre>
<p>Como análisis de sensibilidad, la prueba de rangos con signo de Wilcoxon:</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="inferencial.html#cb177-1" tabindex="-1"></a><span class="fu">wilcox.test</span>(<span class="at">x =</span> pacientes<span class="sc">$</span>motor_final, <span class="at">y =</span> pacientes<span class="sc">$</span>motor_inicio, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank exact test
## 
## data:  pacientes$motor_final and pacientes$motor_inicio
## V = 630, p-value = 0.02495
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>La t pareada da t = 2.159 (41 g.l., p = 0.037); el aumento medio de 2.08 puntos tiene un intervalo de 0.13 a 4.02 que no incluye al 0. El cálculo manual coincide con <code>t.test</code> y Wilcoxon confirma (V = 630, p = 0.025).</p>
</div>
<div id="tamaño-del-efecto-3" class="section level3 hasAnchor" number="2.5.4">
<h3><span class="header-section-number">2.5.4</span> Tamaño del efecto<a href="inferencial.html#tama%C3%B1o-del-efecto-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="inferencial.html#cb179-1" tabindex="-1"></a>d_pareado <span class="ot">&lt;-</span> <span class="fu">cohen.d</span>(pacientes<span class="sc">$</span>motor_final, pacientes<span class="sc">$</span>motor_inicio, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span>
<span id="cb179-2"><a href="inferencial.html#cb179-2" tabindex="-1"></a>d_pareado</span></code></pre></div>
<pre><code>## 
## Cohen&#39;s d
## 
## d estimate: 0.2457669 (small)
## 95 percent confidence interval:
##      lower      upper 
## 0.01595287 0.47558098</code></pre>
<p>La d de Cohen pareada es 0.25, un efecto pequeño, pero esta vez el intervalo (0.02 a 0.48) no incluye al 0. Medido con la desviación estándar de las diferencias, el cambio equivale a 0.33 desviaciones (2.08 / 6.23).</p>
</div>
<div id="conclusión-3" class="section level3 hasAnchor" number="2.5.5">
<h3><span class="header-section-number">2.5.5</span> Conclusión<a href="inferencial.html#conclusi%C3%B3n-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Con una confianza del 95 %, la severidad motora aumenta de forma significativa entre la primera y la última grabación (t = 2.16, p = 0.037): en promedio, 2.08 puntos en unos seis meses. El efecto es pequeño (d = 0.25), lo que encaja con una progresión lenta en la etapa temprana de la enfermedad y con la heterogeneidad entre pacientes: cerca de un tercio mejora en ese periodo.</p>
</div>
</div>
<div id="síntesis-de-resultados" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Síntesis de resultados<a href="inferencial.html#s%C3%ADntesis-de-resultados" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="inferencial.html#cb181-1" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb181-2"><a href="inferencial.html#cb181-2" tabindex="-1"></a>  <span class="at">objetivo =</span> <span class="fu">c</span>(<span class="st">&quot;Sexo (hombres vs. mujeres)&quot;</span>,</span>
<span id="cb181-3"><a href="inferencial.html#cb181-3" tabindex="-1"></a>               <span class="st">&quot;Grupo de edad (3 grupos)&quot;</span>,</span>
<span id="cb181-4"><a href="inferencial.html#cb181-4" tabindex="-1"></a>               <span class="st">&quot;Inestabilidad de la frecuencia (jitter alto vs. bajo)&quot;</span>,</span>
<span id="cb181-5"><a href="inferencial.html#cb181-5" tabindex="-1"></a>               <span class="st">&quot;Inestabilidad de la amplitud (shimmer alto vs. bajo)&quot;</span>,</span>
<span id="cb181-6"><a href="inferencial.html#cb181-6" tabindex="-1"></a>               <span class="st">&quot;Seguimiento (última vs. primera grabación)&quot;</span>),</span>
<span id="cb181-7"><a href="inferencial.html#cb181-7" tabindex="-1"></a>  <span class="at">prueba =</span> <span class="fu">c</span>(<span class="st">&quot;t de Student&quot;</span>, <span class="st">&quot;ANOVA de un factor&quot;</span>, <span class="st">&quot;t de Student&quot;</span>,</span>
<span id="cb181-8"><a href="inferencial.html#cb181-8" tabindex="-1"></a>             <span class="st">&quot;t de Student&quot;</span>, <span class="st">&quot;t pareada&quot;</span>),</span>
<span id="cb181-9"><a href="inferencial.html#cb181-9" tabindex="-1"></a>  <span class="at">estadistico =</span> <span class="fu">c</span>(prueba_t_sexo<span class="sc">$</span>statistic,</span>
<span id="cb181-10"><a href="inferencial.html#cb181-10" tabindex="-1"></a>                  <span class="fu">summary</span>(modelo_anova)[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">`</span><span class="at">F value</span><span class="st">`</span>[<span class="dv">1</span>],</span>
<span id="cb181-11"><a href="inferencial.html#cb181-11" tabindex="-1"></a>                  prueba_t_jitter<span class="sc">$</span>statistic,</span>
<span id="cb181-12"><a href="inferencial.html#cb181-12" tabindex="-1"></a>                  prueba_t_shimmer<span class="sc">$</span>statistic,</span>
<span id="cb181-13"><a href="inferencial.html#cb181-13" tabindex="-1"></a>                  prueba_t_pareada<span class="sc">$</span>statistic),</span>
<span id="cb181-14"><a href="inferencial.html#cb181-14" tabindex="-1"></a>  <span class="at">p_valor =</span> <span class="fu">c</span>(prueba_t_sexo<span class="sc">$</span>p.value,</span>
<span id="cb181-15"><a href="inferencial.html#cb181-15" tabindex="-1"></a>              <span class="fu">summary</span>(modelo_anova)[[<span class="dv">1</span>]]<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span>[<span class="dv">1</span>],</span>
<span id="cb181-16"><a href="inferencial.html#cb181-16" tabindex="-1"></a>              prueba_t_jitter<span class="sc">$</span>p.value,</span>
<span id="cb181-17"><a href="inferencial.html#cb181-17" tabindex="-1"></a>              prueba_t_shimmer<span class="sc">$</span>p.value,</span>
<span id="cb181-18"><a href="inferencial.html#cb181-18" tabindex="-1"></a>              prueba_t_pareada<span class="sc">$</span>p.value),</span>
<span id="cb181-19"><a href="inferencial.html#cb181-19" tabindex="-1"></a>  <span class="at">tamano_efecto =</span> <span class="fu">c</span>(d_sexo<span class="sc">$</span>estimate, eta_cuadrado_manual, d_jitter<span class="sc">$</span>estimate,</span>
<span id="cb181-20"><a href="inferencial.html#cb181-20" tabindex="-1"></a>                    d_shimmer<span class="sc">$</span>estimate, d_pareado<span class="sc">$</span>estimate),</span>
<span id="cb181-21"><a href="inferencial.html#cb181-21" tabindex="-1"></a>  <span class="at">medida =</span> <span class="fu">c</span>(<span class="st">&quot;d de Cohen&quot;</span>, <span class="st">&quot;eta cuadrado&quot;</span>, <span class="st">&quot;d de Cohen&quot;</span>, <span class="st">&quot;d de Cohen&quot;</span>, <span class="st">&quot;d de Cohen&quot;</span>)</span>
<span id="cb181-22"><a href="inferencial.html#cb181-22" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb181-23"><a href="inferencial.html#cb181-23" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">decision =</span> <span class="fu">if_else</span>(p_valor <span class="sc">&lt;</span> <span class="fl">0.05</span>, <span class="st">&quot;Se rechaza H0&quot;</span>, <span class="st">&quot;No se rechaza H0&quot;</span>),</span>
<span id="cb181-24"><a href="inferencial.html#cb181-24" tabindex="-1"></a>         <span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">round</span>(.x, <span class="dv">3</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb181-25"><a href="inferencial.html#cb181-25" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##                                                objetivo             prueba
## 1                            Sexo (hombres vs. mujeres)       t de Student
## 2                              Grupo de edad (3 grupos) ANOVA de un factor
## 3 Inestabilidad de la frecuencia (jitter alto vs. bajo)       t de Student
## 4  Inestabilidad de la amplitud (shimmer alto vs. bajo)       t de Student
## 5            Seguimiento (última vs. primera grabación)          t pareada
##   estadistico p_valor tamano_efecto       medida         decision
## 1       0.360   0.721         0.118   d de Cohen No se rechaza H0
## 2       2.940   0.065         0.131 eta cuadrado No se rechaza H0
## 3       1.423   0.163         0.439   d de Cohen No se rechaza H0
## 4       0.617   0.541         0.191   d de Cohen No se rechaza H0
## 5       2.159   0.037         0.246   d de Cohen    Se rechaza H0</code></pre>
<p>Solo la comparación entre el inicio y el final del seguimiento resulta significativa: la severidad motora sube en promedio 2.08 puntos en seis meses, con un efecto pequeño. El sexo y el shimmer no se asocian con la severidad ni estadística ni prácticamente. Los otros dos resultados muestran la diferencia entre significancia y relevancia: el grupo de edad (eta cuadrado = 0.13, casi 7 puntos entre extremos) y el jitter (d = 0.44, 3.4 puntos) tienen efectos apreciables que con 42 pacientes no cruzan el umbral del 5 % en las pruebas paramétricas, aunque en el caso de la edad la no paramétrica sí lo hace por poco. En conjunto, la edad y el paso del tiempo son lo que más claramente se vincula con la severidad motora; la voz, tal como la analizamos aquí, guarda con ella una relación débil.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="conclusiones.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/DiegoxorG/libro_met_est/edit/main/02-inferencial.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
