<!DOCTYPE html>
<html lang="es" xml:lang="es">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 1 Análisis exploratorio de datos | Análisis de la severidad motora en la enfermedad de Parkinson mediante características acústicas de telemonitoreo</title>
  <meta name="description" content="Análisis exploratorio e inferencial del conjunto de datos Parkinsons Telemonitoring (UCI): relación entre características demográficas, temporales y acústicas de la voz y la severidad motora (motor_UPDRS). Trabajo del curso Métodos Estadísticos, Universidad del Norte." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 1 Análisis exploratorio de datos | Análisis de la severidad motora en la enfermedad de Parkinson mediante características acústicas de telemonitoreo" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Análisis exploratorio e inferencial del conjunto de datos Parkinsons Telemonitoring (UCI): relación entre características demográficas, temporales y acústicas de la voz y la severidad motora (motor_UPDRS). Trabajo del curso Métodos Estadísticos, Universidad del Norte." />
  <meta name="github-repo" content="DiegoxorG/libro_met_est" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 1 Análisis exploratorio de datos | Análisis de la severidad motora en la enfermedad de Parkinson mediante características acústicas de telemonitoreo" />
  
  <meta name="twitter:description" content="Análisis exploratorio e inferencial del conjunto de datos Parkinsons Telemonitoring (UCI): relación entre características demográficas, temporales y acústicas de la voz y la severidad motora (motor_UPDRS). Trabajo del curso Métodos Estadísticos, Universidad del Norte." />
  

<meta name="author" content="Diego Payares &amp; Salma Romero" />


<meta name="date" content="2026-09-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="objetivos-especificos.html"/>
<link rel="next" href="inferencial.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Parkinson y telemonitoreo de la voz</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Contexto del problema</a></li>
<li class="chapter" data-level="" data-path="objetivo-general.html"><a href="objetivo-general.html"><i class="fa fa-check"></i>Objetivo general</a></li>
<li class="chapter" data-level="" data-path="objetivos-especificos.html"><a href="objetivos-especificos.html"><i class="fa fa-check"></i>Objetivos específicos</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Análisis exploratorio de datos</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#an%C3%A1lisis-exploratorio-de-motor_updrs-variable-respuesta"><i class="fa fa-check"></i><b>1.1</b> Análisis exploratorio de <code>motor_UPDRS</code> (variable respuesta)</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="intro.html"><a href="intro.html#resumen-estad%C3%ADstico"><i class="fa fa-check"></i><b>1.1.1</b> Resumen estadístico</a></li>
<li class="chapter" data-level="1.1.2" data-path="intro.html"><a href="intro.html#histograma"><i class="fa fa-check"></i><b>1.1.2</b> Histograma</a></li>
<li class="chapter" data-level="1.1.3" data-path="intro.html"><a href="intro.html#diagrama-de-caja"><i class="fa fa-check"></i><b>1.1.3</b> Diagrama de caja</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#caracterizaci%C3%B3n-de-las-variables-num%C3%A9ricas"><i class="fa fa-check"></i><b>1.2</b> Caracterización de las variables numéricas</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="intro.html"><a href="intro.html#resumen-estad%C3%ADstico-por-variable"><i class="fa fa-check"></i><b>1.2.1</b> Resumen estadístico por variable</a></li>
<li class="chapter" data-level="1.2.2" data-path="intro.html"><a href="intro.html#histogramas"><i class="fa fa-check"></i><b>1.2.2</b> Histogramas</a></li>
<li class="chapter" data-level="1.2.3" data-path="intro.html"><a href="intro.html#dispersi%C3%B3n-frente-a-motor_updrs"><i class="fa fa-check"></i><b>1.2.3</b> Dispersión frente a <code>motor_UPDRS</code></a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#caracterizaci%C3%B3n-de-la-variable-categ%C3%B3rica-sex"><i class="fa fa-check"></i><b>1.3</b> Caracterización de la variable categórica <code>sex</code></a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="intro.html"><a href="intro.html#distribuci%C3%B3n-por-registros-y-por-pacientes"><i class="fa fa-check"></i><b>1.3.1</b> Distribución por registros y por pacientes</a></li>
<li class="chapter" data-level="1.3.2" data-path="intro.html"><a href="intro.html#severidad-motora-seg%C3%BAn-el-sexo"><i class="fa fa-check"></i><b>1.3.2</b> Severidad motora según el sexo</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#relaciones-entre-las-variables-independientes-num%C3%A9ricas"><i class="fa fa-check"></i><b>1.4</b> Relaciones entre las variables independientes numéricas</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="intro.html"><a href="intro.html#pares-seleccionados"><i class="fa fa-check"></i><b>1.4.1</b> Pares seleccionados</a></li>
<li class="chapter" data-level="1.4.2" data-path="intro.html"><a href="intro.html#matriz-de-correlaciones"><i class="fa fa-check"></i><b>1.4.2</b> Matriz de correlaciones</a></li>
<li class="chapter" data-level="1.4.3" data-path="intro.html"><a href="intro.html#pares-m%C3%A1s-correlacionados"><i class="fa fa-check"></i><b>1.4.3</b> Pares más correlacionados</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#ingenier%C3%ADa-de-caracter%C3%ADsticas"><i class="fa fa-check"></i><b>1.5</b> Ingeniería de características</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="intro.html"><a href="intro.html#construcci%C3%B3n-de-los-%C3%ADndices"><i class="fa fa-check"></i><b>1.5.1</b> Construcción de los índices</a></li>
<li class="chapter" data-level="1.5.2" data-path="intro.html"><a href="intro.html#verificaci%C3%B3n-de-los-%C3%ADndices"><i class="fa fa-check"></i><b>1.5.2</b> Verificación de los índices</a></li>
<li class="chapter" data-level="1.5.3" data-path="intro.html"><a href="intro.html#descripci%C3%B3n-de-los-%C3%ADndices"><i class="fa fa-check"></i><b>1.5.3</b> Descripción de los índices</a></li>
<li class="chapter" data-level="1.5.4" data-path="intro.html"><a href="intro.html#relaci%C3%B3n-con-la-variable-respuesta"><i class="fa fa-check"></i><b>1.5.4</b> Relación con la variable respuesta</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="inferencial.html"><a href="inferencial.html"><i class="fa fa-check"></i><b>2</b> Estadística inferencial</a>
<ul>
<li class="chapter" data-level="2.1" data-path="inferencial.html"><a href="inferencial.html#unidad-de-an%C3%A1lisis-tabla-por-paciente"><i class="fa fa-check"></i><b>2.1</b> Unidad de análisis: tabla por paciente</a></li>
<li class="chapter" data-level="2.2" data-path="inferencial.html"><a href="inferencial.html#objetivo-1-severidad-motora-seg%C3%BAn-el-sexo"><i class="fa fa-check"></i><b>2.2</b> Objetivo 1: severidad motora según el sexo</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="inferencial.html"><a href="inferencial.html#an%C3%A1lisis-exploratorio"><i class="fa fa-check"></i><b>2.2.1</b> Análisis exploratorio</a></li>
<li class="chapter" data-level="2.2.2" data-path="inferencial.html"><a href="inferencial.html#supuesto-de-normalidad"><i class="fa fa-check"></i><b>2.2.2</b> Supuesto de normalidad</a></li>
<li class="chapter" data-level="2.2.3" data-path="inferencial.html"><a href="inferencial.html#supuesto-de-homocedasticidad"><i class="fa fa-check"></i><b>2.2.3</b> Supuesto de homocedasticidad</a></li>
<li class="chapter" data-level="2.2.4" data-path="inferencial.html"><a href="inferencial.html#prueba-de-hip%C3%B3tesis-t-de-student"><i class="fa fa-check"></i><b>2.2.4</b> Prueba de hipótesis: t de Student</a></li>
<li class="chapter" data-level="2.2.5" data-path="inferencial.html"><a href="inferencial.html#tama%C3%B1o-del-efecto"><i class="fa fa-check"></i><b>2.2.5</b> Tamaño del efecto</a></li>
<li class="chapter" data-level="2.2.6" data-path="inferencial.html"><a href="inferencial.html#conclusi%C3%B3n"><i class="fa fa-check"></i><b>2.2.6</b> Conclusión</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="inferencial.html"><a href="inferencial.html#objetivo-2-severidad-motora-seg%C3%BAn-el-grupo-de-edad"><i class="fa fa-check"></i><b>2.3</b> Objetivo 2: severidad motora según el grupo de edad</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="inferencial.html"><a href="inferencial.html#an%C3%A1lisis-exploratorio-1"><i class="fa fa-check"></i><b>2.3.1</b> Análisis exploratorio</a></li>
<li class="chapter" data-level="2.3.2" data-path="inferencial.html"><a href="inferencial.html#supuesto-de-normalidad-1"><i class="fa fa-check"></i><b>2.3.2</b> Supuesto de normalidad</a></li>
<li class="chapter" data-level="2.3.3" data-path="inferencial.html"><a href="inferencial.html#supuesto-de-homocedasticidad-1"><i class="fa fa-check"></i><b>2.3.3</b> Supuesto de homocedasticidad</a></li>
<li class="chapter" data-level="2.3.4" data-path="inferencial.html"><a href="inferencial.html#prueba-de-hip%C3%B3tesis-anova-de-un-factor"><i class="fa fa-check"></i><b>2.3.4</b> Prueba de hipótesis: ANOVA de un factor</a></li>
<li class="chapter" data-level="2.3.5" data-path="inferencial.html"><a href="inferencial.html#an%C3%A1lisis-de-sensibilidad-kruskal-wallis-y-prueba-de-dunn"><i class="fa fa-check"></i><b>2.3.5</b> Análisis de sensibilidad: Kruskal-Wallis y prueba de Dunn</a></li>
<li class="chapter" data-level="2.3.6" data-path="inferencial.html"><a href="inferencial.html#tama%C3%B1o-del-efecto-1"><i class="fa fa-check"></i><b>2.3.6</b> Tamaño del efecto</a></li>
<li class="chapter" data-level="2.3.7" data-path="inferencial.html"><a href="inferencial.html#conclusi%C3%B3n-1"><i class="fa fa-check"></i><b>2.3.7</b> Conclusión</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="inferencial.html"><a href="inferencial.html#objetivo-3-severidad-motora-seg%C3%BAn-el-nivel-de-inestabilidad-vocal"><i class="fa fa-check"></i><b>2.4</b> Objetivo 3: severidad motora según el nivel de inestabilidad vocal</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="inferencial.html"><a href="inferencial.html#an%C3%A1lisis-exploratorio-2"><i class="fa fa-check"></i><b>2.4.1</b> Análisis exploratorio</a></li>
<li class="chapter" data-level="2.4.2" data-path="inferencial.html"><a href="inferencial.html#supuesto-de-normalidad-2"><i class="fa fa-check"></i><b>2.4.2</b> Supuesto de normalidad</a></li>
<li class="chapter" data-level="2.4.3" data-path="inferencial.html"><a href="inferencial.html#supuesto-de-homocedasticidad-2"><i class="fa fa-check"></i><b>2.4.3</b> Supuesto de homocedasticidad</a></li>
<li class="chapter" data-level="2.4.4" data-path="inferencial.html"><a href="inferencial.html#prueba-de-hip%C3%B3tesis-t-de-student-1"><i class="fa fa-check"></i><b>2.4.4</b> Prueba de hipótesis: t de Student</a></li>
<li class="chapter" data-level="2.4.5" data-path="inferencial.html"><a href="inferencial.html#tama%C3%B1o-del-efecto-2"><i class="fa fa-check"></i><b>2.4.5</b> Tamaño del efecto</a></li>
<li class="chapter" data-level="2.4.6" data-path="inferencial.html"><a href="inferencial.html#conclusi%C3%B3n-2"><i class="fa fa-check"></i><b>2.4.6</b> Conclusión</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="inferencial.html"><a href="inferencial.html#objetivo-4-evoluci%C3%B3n-de-la-severidad-motora-durante-el-seguimiento"><i class="fa fa-check"></i><b>2.5</b> Objetivo 4: evolución de la severidad motora durante el seguimiento</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="inferencial.html"><a href="inferencial.html#an%C3%A1lisis-exploratorio-3"><i class="fa fa-check"></i><b>2.5.1</b> Análisis exploratorio</a></li>
<li class="chapter" data-level="2.5.2" data-path="inferencial.html"><a href="inferencial.html#supuesto-de-normalidad-de-las-diferencias"><i class="fa fa-check"></i><b>2.5.2</b> Supuesto de normalidad de las diferencias</a></li>
<li class="chapter" data-level="2.5.3" data-path="inferencial.html"><a href="inferencial.html#prueba-de-hip%C3%B3tesis-t-pareada"><i class="fa fa-check"></i><b>2.5.3</b> Prueba de hipótesis: t pareada</a></li>
<li class="chapter" data-level="2.5.4" data-path="inferencial.html"><a href="inferencial.html#tama%C3%B1o-del-efecto-3"><i class="fa fa-check"></i><b>2.5.4</b> Tamaño del efecto</a></li>
<li class="chapter" data-level="2.5.5" data-path="inferencial.html"><a href="inferencial.html#conclusi%C3%B3n-3"><i class="fa fa-check"></i><b>2.5.5</b> Conclusión</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="inferencial.html"><a href="inferencial.html#objetivo-5-correlaci%C3%B3n-entre-las-caracter%C3%ADsticas-y-la-severidad-motora"><i class="fa fa-check"></i><b>2.6</b> Objetivo 5: correlación entre las características y la severidad motora</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="inferencial.html"><a href="inferencial.html#an%C3%A1lisis-exploratorio-4"><i class="fa fa-check"></i><b>2.6.1</b> Análisis exploratorio</a></li>
<li class="chapter" data-level="2.6.2" data-path="inferencial.html"><a href="inferencial.html#supuesto-de-normalidad-3"><i class="fa fa-check"></i><b>2.6.2</b> Supuesto de normalidad</a></li>
<li class="chapter" data-level="2.6.3" data-path="inferencial.html"><a href="inferencial.html#prueba-de-hip%C3%B3tesis-correlaci%C3%B3n-de-pearson-y-de-spearman"><i class="fa fa-check"></i><b>2.6.3</b> Prueba de hipótesis: correlación de Pearson y de Spearman</a></li>
<li class="chapter" data-level="2.6.4" data-path="inferencial.html"><a href="inferencial.html#tama%C3%B1o-del-efecto-4"><i class="fa fa-check"></i><b>2.6.4</b> Tamaño del efecto</a></li>
<li class="chapter" data-level="2.6.5" data-path="inferencial.html"><a href="inferencial.html#conclusi%C3%B3n-4"><i class="fa fa-check"></i><b>2.6.5</b> Conclusión</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="inferencial.html"><a href="inferencial.html#s%C3%ADntesis-de-resultados"><i class="fa fa-check"></i><b>2.7</b> Síntesis de resultados</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="conclusiones.html"><a href="conclusiones.html"><i class="fa fa-check"></i><b>3</b> Conclusiones</a></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/DiegoxorG/libro_met_est" target="blank">Diego Payares & Salma Romero</a></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis de la severidad motora en la enfermedad de Parkinson mediante características acústicas de telemonitoreo</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="intro" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Capítulo 1</span> Análisis exploratorio de datos<a href="intro.html#intro" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="intro.html#cb1-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="intro.html#cb1-2" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb1-3"><a href="intro.html#cb1-3" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-4"><a href="intro.html#cb1-4" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="intro.html#cb2-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/parkinsons_updrs.data&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="intro.html#cb3-1" tabindex="-1"></a><span class="fu">head</span>(data, <span class="at">n=</span><span class="dv">10</span>)</span></code></pre></div>
<pre><code>##    subject. age sex test_time motor_UPDRS total_UPDRS Jitter... Jitter.Abs.
## 1         1  72   0    5.6431      28.199      34.398   0.00662   3.380e-05
## 2         1  72   0   12.6660      28.447      34.894   0.00300   1.680e-05
## 3         1  72   0   19.6810      28.695      35.389   0.00481   2.462e-05
## 4         1  72   0   25.6470      28.905      35.810   0.00528   2.657e-05
## 5         1  72   0   33.6420      29.187      36.375   0.00335   2.014e-05
## 6         1  72   0   40.6520      29.435      36.870   0.00353   2.290e-05
## 7         1  72   0   47.6490      29.682      37.363   0.00422   2.404e-05
## 8         1  72   0   54.6400      29.928      37.857   0.00476   2.471e-05
## 9         1  72   0   61.6690      30.177      38.353   0.00432   2.854e-05
## 10        1  72   0   68.6880      30.424      38.849   0.00496   2.702e-05
##    Jitter.RAP Jitter.PPQ5 Jitter.DDP Shimmer Shimmer.dB. Shimmer.APQ3
## 1     0.00401     0.00317    0.01204 0.02565       0.230      0.01438
## 2     0.00132     0.00150    0.00395 0.02024       0.179      0.00994
## 3     0.00205     0.00208    0.00616 0.01675       0.181      0.00734
## 4     0.00191     0.00264    0.00573 0.02309       0.327      0.01106
## 5     0.00093     0.00130    0.00278 0.01703       0.176      0.00679
## 6     0.00119     0.00159    0.00357 0.02227       0.214      0.01006
## 7     0.00212     0.00221    0.00637 0.04352       0.445      0.02376
## 8     0.00226     0.00259    0.00678 0.02191       0.212      0.00979
## 9     0.00156     0.00207    0.00468 0.04296       0.371      0.01774
## 10    0.00258     0.00253    0.00773 0.03610       0.310      0.02030
##    Shimmer.APQ5 Shimmer.APQ11 Shimmer.DDA      NHR    HNR    RPDE     DFA
## 1       0.01309       0.01662     0.04314 0.014290 21.640 0.41888 0.54842
## 2       0.01072       0.01689     0.02982 0.011112 27.183 0.43493 0.56477
## 3       0.00844       0.01458     0.02202 0.020220 23.047 0.46222 0.54405
## 4       0.01265       0.01963     0.03317 0.027837 24.445 0.48730 0.57794
## 5       0.00929       0.01819     0.02036 0.011625 26.126 0.47188 0.56122
## 6       0.01337       0.02263     0.03019 0.009438 22.946 0.53949 0.57243
## 7       0.02621       0.03488     0.07128 0.013260 22.506 0.49250 0.54779
## 8       0.01462       0.01911     0.02937 0.027969 22.929 0.47712 0.54234
## 9       0.02134       0.03451     0.05323 0.013381 22.078 0.51563 0.61864
## 10      0.01970       0.02569     0.06089 0.018021 22.606 0.50032 0.58673
##        PPE
## 1  0.16006
## 2  0.10810
## 3  0.21014
## 4  0.33277
## 5  0.19361
## 6  0.19500
## 7  0.17563
## 8  0.23844
## 9  0.20037
## 10 0.20117</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="intro.html#cb5-1" tabindex="-1"></a><span class="fu">str</span>(data)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    5875 obs. of  22 variables:
##  $ subject.     : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ age          : int  72 72 72 72 72 72 72 72 72 72 ...
##  $ sex          : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ test_time    : num  5.64 12.67 19.68 25.65 33.64 ...
##  $ motor_UPDRS  : num  28.2 28.4 28.7 28.9 29.2 ...
##  $ total_UPDRS  : num  34.4 34.9 35.4 35.8 36.4 ...
##  $ Jitter...    : num  0.00662 0.003 0.00481 0.00528 0.00335 0.00353 0.00422 0.00476 0.00432 0.00496 ...
##  $ Jitter.Abs.  : num  3.38e-05 1.68e-05 2.46e-05 2.66e-05 2.01e-05 ...
##  $ Jitter.RAP   : num  0.00401 0.00132 0.00205 0.00191 0.00093 0.00119 0.00212 0.00226 0.00156 0.00258 ...
##  $ Jitter.PPQ5  : num  0.00317 0.0015 0.00208 0.00264 0.0013 0.00159 0.00221 0.00259 0.00207 0.00253 ...
##  $ Jitter.DDP   : num  0.01204 0.00395 0.00616 0.00573 0.00278 ...
##  $ Shimmer      : num  0.0256 0.0202 0.0168 0.0231 0.017 ...
##  $ Shimmer.dB.  : num  0.23 0.179 0.181 0.327 0.176 0.214 0.445 0.212 0.371 0.31 ...
##  $ Shimmer.APQ3 : num  0.01438 0.00994 0.00734 0.01106 0.00679 ...
##  $ Shimmer.APQ5 : num  0.01309 0.01072 0.00844 0.01265 0.00929 ...
##  $ Shimmer.APQ11: num  0.0166 0.0169 0.0146 0.0196 0.0182 ...
##  $ Shimmer.DDA  : num  0.0431 0.0298 0.022 0.0332 0.0204 ...
##  $ NHR          : num  0.0143 0.0111 0.0202 0.0278 0.0116 ...
##  $ HNR          : num  21.6 27.2 23 24.4 26.1 ...
##  $ RPDE         : num  0.419 0.435 0.462 0.487 0.472 ...
##  $ DFA          : num  0.548 0.565 0.544 0.578 0.561 ...
##  $ PPE          : num  0.16 0.108 0.21 0.333 0.194 ...</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="intro.html#cb7-1" tabindex="-1"></a>data <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="intro.html#cb7-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)), <span class="at">.names =</span> <span class="st">&quot;NA_{.col}&quot;</span>))</span></code></pre></div>
<pre><code>##   NA_subject. NA_age NA_sex NA_test_time NA_motor_UPDRS NA_total_UPDRS
## 1           0      0      0            0              0              0
##   NA_Jitter... NA_Jitter.Abs. NA_Jitter.RAP NA_Jitter.PPQ5 NA_Jitter.DDP
## 1            0              0             0              0             0
##   NA_Shimmer NA_Shimmer.dB. NA_Shimmer.APQ3 NA_Shimmer.APQ5 NA_Shimmer.APQ11
## 1          0              0               0               0                0
##   NA_Shimmer.DDA NA_NHR NA_HNR NA_RPDE NA_DFA NA_PPE
## 1              0      0      0       0      0      0</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="intro.html#cb9-1" tabindex="-1"></a>data<span class="sc">$</span>subject. <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>subject.)</span>
<span id="cb9-2"><a href="intro.html#cb9-2" tabindex="-1"></a></span>
<span id="cb9-3"><a href="intro.html#cb9-3" tabindex="-1"></a>data<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>sex,</span>
<span id="cb9-4"><a href="intro.html#cb9-4" tabindex="-1"></a>                   <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb9-5"><a href="intro.html#cb9-5" tabindex="-1"></a>                   <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Masculino&quot;</span>, <span class="st">&quot;Femenino&quot;</span>))</span>
<span id="cb9-6"><a href="intro.html#cb9-6" tabindex="-1"></a><span class="fu">str</span>(data)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    5875 obs. of  22 variables:
##  $ subject.     : Factor w/ 42 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;,&quot;4&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ age          : int  72 72 72 72 72 72 72 72 72 72 ...
##  $ sex          : Factor w/ 2 levels &quot;Masculino&quot;,&quot;Femenino&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ test_time    : num  5.64 12.67 19.68 25.65 33.64 ...
##  $ motor_UPDRS  : num  28.2 28.4 28.7 28.9 29.2 ...
##  $ total_UPDRS  : num  34.4 34.9 35.4 35.8 36.4 ...
##  $ Jitter...    : num  0.00662 0.003 0.00481 0.00528 0.00335 0.00353 0.00422 0.00476 0.00432 0.00496 ...
##  $ Jitter.Abs.  : num  3.38e-05 1.68e-05 2.46e-05 2.66e-05 2.01e-05 ...
##  $ Jitter.RAP   : num  0.00401 0.00132 0.00205 0.00191 0.00093 0.00119 0.00212 0.00226 0.00156 0.00258 ...
##  $ Jitter.PPQ5  : num  0.00317 0.0015 0.00208 0.00264 0.0013 0.00159 0.00221 0.00259 0.00207 0.00253 ...
##  $ Jitter.DDP   : num  0.01204 0.00395 0.00616 0.00573 0.00278 ...
##  $ Shimmer      : num  0.0256 0.0202 0.0168 0.0231 0.017 ...
##  $ Shimmer.dB.  : num  0.23 0.179 0.181 0.327 0.176 0.214 0.445 0.212 0.371 0.31 ...
##  $ Shimmer.APQ3 : num  0.01438 0.00994 0.00734 0.01106 0.00679 ...
##  $ Shimmer.APQ5 : num  0.01309 0.01072 0.00844 0.01265 0.00929 ...
##  $ Shimmer.APQ11: num  0.0166 0.0169 0.0146 0.0196 0.0182 ...
##  $ Shimmer.DDA  : num  0.0431 0.0298 0.022 0.0332 0.0204 ...
##  $ NHR          : num  0.0143 0.0111 0.0202 0.0278 0.0116 ...
##  $ HNR          : num  21.6 27.2 23 24.4 26.1 ...
##  $ RPDE         : num  0.419 0.435 0.462 0.487 0.472 ...
##  $ DFA          : num  0.548 0.565 0.544 0.578 0.561 ...
##  $ PPE          : num  0.16 0.108 0.21 0.333 0.194 ...</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="intro.html#cb11-1" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>sex)</span></code></pre></div>
<pre><code>## 
## Masculino  Femenino 
##      4008      1867</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="intro.html#cb13-1" tabindex="-1"></a><span class="fu">nlevels</span>(data<span class="sc">$</span>subject.)</span></code></pre></div>
<pre><code>## [1] 42</code></pre>
<p>Convertimos <code>subject.</code> en factor, porque es un identificador y no una cantidad, y le ponemos etiquetas a <code>sex</code>. Vale la pena notar desde ya que cada uno de los 42 pacientes aporta entre 101 y 168 grabaciones, así que los registros de una misma persona comparten edad, sexo y niveles de severidad muy parecidos. El exploratorio se hace sobre los registros; en la parte inferencial esta estructura sí se tendrá en cuenta.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="intro.html#cb15-1" tabindex="-1"></a>n_negativos <span class="ot">&lt;-</span> <span class="fu">sum</span>(data<span class="sc">$</span>test_time <span class="sc">&lt;</span> <span class="dv">0</span>)</span>
<span id="cb15-2"><a href="intro.html#cb15-2" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Existen&quot;</span>, n_negativos, <span class="st">&quot;registros con test_time &lt; 0.</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Existen 12 registros con test_time &lt; 0.</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="intro.html#cb17-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="intro.html#cb17-2" tabindex="-1"></a>  <span class="fu">filter</span>(test_time <span class="sc">&gt;=</span> <span class="dv">0</span>)</span>
<span id="cb17-3"><a href="intro.html#cb17-3" tabindex="-1"></a></span>
<span id="cb17-4"><a href="intro.html#cb17-4" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Después de la limpieza:&quot;</span>, n_negativos,</span>
<span id="cb17-5"><a href="intro.html#cb17-5" tabindex="-1"></a>    <span class="st">&quot;registros fueron excluidos del análisis.</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Después de la limpieza: 12 registros fueron excluidos del análisis.</code></pre>
<p>Los 12 registros con <code>test_time</code> negativo son grabaciones fechadas antes del día de reclutamiento, así que se descartan. Seguimos con 5.863 registros.</p>
<div id="análisis-exploratorio-de-motor_updrs-variable-respuesta" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Análisis exploratorio de <code>motor_UPDRS</code> (variable respuesta)<a href="intro.html#an%C3%A1lisis-exploratorio-de-motor_updrs-variable-respuesta" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="resumen-estadístico" class="section level3 hasAnchor" number="1.1.1">
<h3><span class="header-section-number">1.1.1</span> Resumen estadístico<a href="intro.html#resumen-estad%C3%ADstico" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Realicemos el resumen estadístico de la variable respuesta <code>motor_UPDRS</code>.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="intro.html#cb19-1" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="intro.html#cb19-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb19-3"><a href="intro.html#cb19-3" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(motor_UPDRS),</span>
<span id="cb19-4"><a href="intro.html#cb19-4" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(motor_UPDRS),</span>
<span id="cb19-5"><a href="intro.html#cb19-5" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(motor_UPDRS),</span>
<span id="cb19-6"><a href="intro.html#cb19-6" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(motor_UPDRS),</span>
<span id="cb19-7"><a href="intro.html#cb19-7" tabindex="-1"></a>    <span class="at">RIC =</span> <span class="fu">IQR</span>(motor_UPDRS), </span>
<span id="cb19-8"><a href="intro.html#cb19-8" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(motor_UPDRS, <span class="fl">0.25</span>),</span>
<span id="cb19-9"><a href="intro.html#cb19-9" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(motor_UPDRS, <span class="fl">0.75</span>),</span>
<span id="cb19-10"><a href="intro.html#cb19-10" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(motor_UPDRS),</span>
<span id="cb19-11"><a href="intro.html#cb19-11" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(motor_UPDRS),</span>
<span id="cb19-12"><a href="intro.html#cb19-12" tabindex="-1"></a>    <span class="at">asimetria =</span> <span class="fu">skewness</span>(motor_UPDRS),</span>
<span id="cb19-13"><a href="intro.html#cb19-13" tabindex="-1"></a>    <span class="at">curtosis =</span> <span class="fu">kurtosis</span>(motor_UPDRS))</span></code></pre></div>
<pre><code>##      n    media       sd mediana    RIC Q1     Q3 minimo maximo  asimetria
## 1 5863 21.28965 8.133419  20.871 12.594 15 27.594 5.0377 39.511 0.07672819
##   curtosis
## 1 2.061561</code></pre>
<p>La variable motor_UPDRS presenta 5.863 registros, con una media de 21.29 puntos y una desviación estándar de 8.13 puntos, lo que demuestra una variabilidad considerable en las evaluaciones de los pacientes a lo largo del estudio. Exactamente el 50 % de los registros presenta un puntaje inferior a 20.87 puntos, mientras que el 50 % restante supera esta cifra. La cercanía entre este punto medio y el promedio general (21.29 puntos) concuerda con un coeficiente de asimetría cercano a cero (0.077), sugiriendo que las puntuaciones de afectación motora se distribuyen de forma balanceada alrededor de su centro.</p>
<p>El 50 % central de las observaciones se encuentra entre 15 y 27.59 puntos, con un rango intercuartílico de 12.59. Esto deja al 25 % de la muestra en un estado de deterioro leve (por debajo de 15 puntos) y al 25 % restante en una condición más severa (por encima de 27.59 puntos).</p>
<p>La amplitud de la escala observada abarca desde un estado de afectación motora mínima de 5.04 puntos hasta un deterioro severo alcanzando los 39.51 puntos. Esta brecha confirma que la muestra integra tanto a pacientes en estadios iniciales o altamente controlados de la enfermedad como a individuos con una alteración motora considerablemente avanzada.</p>
<p>La asimetría es cercana a cero (0.077), lo que indica una distribución aproximadamente simétrica, con una ligera asimetría positiva. La curtosis de 2.06 es inferior a la correspondiente a una distribución normal (3). Esto implica una menor concentración de datos alrededor del centro y colas más ligeras, lo que nuevamente refleja que las puntuaciones del motor UPDRS están dispersas de manera más uniforme a lo largo del rango medio en lugar de agruparse de forma pronunciada en un único punto.</p>
</div>
<div id="histograma" class="section level3 hasAnchor" number="1.1.2">
<h3><span class="header-section-number">1.1.2</span> Histograma<a href="intro.html#histograma" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="intro.html#cb21-1" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="intro.html#cb21-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> motor_UPDRS)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="intro.html#cb21-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb21-4"><a href="intro.html#cb21-4" tabindex="-1"></a>                 <span class="at">binwidth =</span> <span class="dv">2</span>,</span>
<span id="cb21-5"><a href="intro.html#cb21-5" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">&quot;#FAD0C4&quot;</span>,</span>
<span id="cb21-6"><a href="intro.html#cb21-6" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">&quot;#E8A598&quot;</span>,</span>
<span id="cb21-7"><a href="intro.html#cb21-7" tabindex="-1"></a>                 <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb21-8"><a href="intro.html#cb21-8" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;#C2185B&quot;</span>,</span>
<span id="cb21-9"><a href="intro.html#cb21-9" tabindex="-1"></a>               <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb21-10"><a href="intro.html#cb21-10" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribución de la puntuación motor UPDRS&quot;</span>,</span>
<span id="cb21-11"><a href="intro.html#cb21-11" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Evaluación de densidad y frecuencia relativa&quot;</span>,</span>
<span id="cb21-12"><a href="intro.html#cb21-12" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Motor UPDRS (Puntos)&quot;</span>,</span>
<span id="cb21-13"><a href="intro.html#cb21-13" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Densidad&quot;</span>) <span class="sc">+</span></span>
<span id="cb21-14"><a href="intro.html#cb21-14" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_family =</span> <span class="st">&quot;sans&quot;</span>) <span class="sc">+</span></span>
<span id="cb21-15"><a href="intro.html#cb21-15" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb21-16"><a href="intro.html#cb21-16" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>, <span class="at">color =</span> <span class="st">&quot;#4A4A4A&quot;</span>),</span>
<span id="cb21-17"><a href="intro.html#cb21-17" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">color =</span> <span class="st">&quot;gray40&quot;</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="at">b =</span> <span class="dv">10</span>)),</span>
<span id="cb21-18"><a href="intro.html#cb21-18" tabindex="-1"></a>    <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="at">t =</span> <span class="dv">10</span>), <span class="at">color =</span> <span class="st">&quot;#4A4A4A&quot;</span>),</span>
<span id="cb21-19"><a href="intro.html#cb21-19" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="at">r =</span> <span class="dv">10</span>), <span class="at">color =</span> <span class="st">&quot;#4A4A4A&quot;</span>),</span>
<span id="cb21-20"><a href="intro.html#cb21-20" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb21-21"><a href="intro.html#cb21-21" tabindex="-1"></a>    <span class="at">panel.grid.major =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;gray92&quot;</span>)</span>
<span id="cb21-22"><a href="intro.html#cb21-22" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/histograma-motor-updrs-1.png" alt="" width="672" />
El gráfico revela una distribución bimodal en la puntuación motor UPDRS, evidenciada por dos picos o modas principales en la curva de densidad: el primero en torno a los 17 puntos (afectación leve-moderada) y el segundo alrededor de los 26 puntos (afectación moderada-avanzada), separados por un valle relativo cerca de los 21 puntos. Esta forma bimodal indica que la distribución no es normal. Conviene recordar que cada paciente aporta unas 140 grabaciones con puntuaciones muy parecidas entre sí, así que las dos modas reflejan sobre todo la mezcla de pacientes con distintos niveles de severidad, más que dos subgrupos clínicos definidos.</p>
</div>
<div id="diagrama-de-caja" class="section level3 hasAnchor" number="1.1.3">
<h3><span class="header-section-number">1.1.3</span> Diagrama de caja<a href="intro.html#diagrama-de-caja" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="intro.html#cb22-1" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="intro.html#cb22-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> motor_UPDRS)) <span class="sc">+</span></span>
<span id="cb22-3"><a href="intro.html#cb22-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#FAD0C4&quot;</span>,</span>
<span id="cb22-4"><a href="intro.html#cb22-4" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">&quot;#C2185B&quot;</span>,</span>
<span id="cb22-5"><a href="intro.html#cb22-5" tabindex="-1"></a>               <span class="at">width =</span> <span class="fl">0.3</span>,</span>
<span id="cb22-6"><a href="intro.html#cb22-6" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&quot;#8E0038&quot;</span>,</span>
<span id="cb22-7"><a href="intro.html#cb22-7" tabindex="-1"></a>               <span class="at">outlier.shape =</span> <span class="dv">16</span>,</span>
<span id="cb22-8"><a href="intro.html#cb22-8" tabindex="-1"></a>               <span class="at">outlier.size =</span> <span class="dv">2</span>,</span>
<span id="cb22-9"><a href="intro.html#cb22-9" tabindex="-1"></a>               <span class="at">outlier.alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb22-10"><a href="intro.html#cb22-10" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean,</span>
<span id="cb22-11"><a href="intro.html#cb22-11" tabindex="-1"></a>               <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>,</span>
<span id="cb22-12"><a href="intro.html#cb22-12" tabindex="-1"></a>               <span class="at">shape =</span> <span class="dv">18</span>,</span>
<span id="cb22-13"><a href="intro.html#cb22-13" tabindex="-1"></a>               <span class="at">size =</span> <span class="fl">3.5</span>,</span>
<span id="cb22-14"><a href="intro.html#cb22-14" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">&quot;#8E0038&quot;</span>) <span class="sc">+</span></span>
<span id="cb22-15"><a href="intro.html#cb22-15" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Boxplot de la puntuación motor UPDRS&quot;</span>,</span>
<span id="cb22-16"><a href="intro.html#cb22-16" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb22-17"><a href="intro.html#cb22-17" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Motor UPDRS (Puntos)&quot;</span>) <span class="sc">+</span></span>
<span id="cb22-18"><a href="intro.html#cb22-18" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_family =</span> <span class="st">&quot;sans&quot;</span>) <span class="sc">+</span></span>
<span id="cb22-19"><a href="intro.html#cb22-19" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb22-20"><a href="intro.html#cb22-20" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>, <span class="at">color =</span> <span class="st">&quot;#4A4A4A&quot;</span>),</span>
<span id="cb22-21"><a href="intro.html#cb22-21" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">color =</span> <span class="st">&quot;gray40&quot;</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="at">b =</span> <span class="dv">10</span>)),</span>
<span id="cb22-22"><a href="intro.html#cb22-22" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="at">r =</span> <span class="dv">10</span>), <span class="at">color =</span> <span class="st">&quot;#4A4A4A&quot;</span>),</span>
<span id="cb22-23"><a href="intro.html#cb22-23" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb22-24"><a href="intro.html#cb22-24" tabindex="-1"></a>    <span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb22-25"><a href="intro.html#cb22-25" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb22-26"><a href="intro.html#cb22-26" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb22-27"><a href="intro.html#cb22-27" tabindex="-1"></a>    <span class="at">panel.grid.major.y =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">&quot;gray92&quot;</span>)</span>
<span id="cb22-28"><a href="intro.html#cb22-28" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/boxplot-motor-updrs-1.png" alt="" width="672" />
El diagrama de caja confirma una distribución simétrica en la severidad motora de los pacientes, reflejando un valor central de 20.87 puntos que coincide estrechamente con el promedio muestral de 21.3 puntos. La caja abarca un amplio rango intercuartílico de 12.6 puntos, delimitado entre un estado de deterioro leve de 15 puntos y una etapa de afectación moderada-avanzada de 27.6 puntos. La extensión completa del dominio (entre 5.04 y 39.51 puntos) demuestra que la muestra de pacientes abarca todo el espectro funcional de la enfermedad. Destaca la ausencia total de valores atípicos, lo que indica que la dispersión observada no se debe a inconsistencias de medición, sino a la variabilidad biológica esperada en el progreso del Parkinson.</p>
</div>
</div>
<div id="caracterización-de-las-variables-numéricas" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Caracterización de las variables numéricas<a href="intro.html#caracterizaci%C3%B3n-de-las-variables-num%C3%A9ricas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Aquí se describen las variables independientes numéricas. Dejamos fuera <code>total_UPDRS</code>: es la otra puntuación clínica del estudio e incluye la parte motora (su correlación con <code>motor_UPDRS</code> es 0.95), así que no puede tratarse como variable explicativa.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="intro.html#cb23-1" tabindex="-1"></a><span class="fu">cor</span>(data<span class="sc">$</span>motor_UPDRS, data<span class="sc">$</span>total_UPDRS)</span></code></pre></div>
<pre><code>## [1] 0.9473407</code></pre>
<div id="resumen-estadístico-por-variable" class="section level3 hasAnchor" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> Resumen estadístico por variable<a href="intro.html#resumen-estad%C3%ADstico-por-variable" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="intro.html#cb25-1" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="intro.html#cb25-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric), <span class="sc">-</span>motor_UPDRS, <span class="sc">-</span>total_UPDRS) <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="intro.html#cb25-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb25-4"><a href="intro.html#cb25-4" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb25-5"><a href="intro.html#cb25-5" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">&quot;variable&quot;</span>,</span>
<span id="cb25-6"><a href="intro.html#cb25-6" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">&quot;valor&quot;</span></span>
<span id="cb25-7"><a href="intro.html#cb25-7" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb25-8"><a href="intro.html#cb25-8" tabindex="-1"></a>  <span class="fu">group_by</span>(variable) <span class="sc">%&gt;%</span></span>
<span id="cb25-9"><a href="intro.html#cb25-9" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb25-10"><a href="intro.html#cb25-10" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(valor)),</span>
<span id="cb25-11"><a href="intro.html#cb25-11" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(valor),</span>
<span id="cb25-12"><a href="intro.html#cb25-12" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(valor),</span>
<span id="cb25-13"><a href="intro.html#cb25-13" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(valor),</span>
<span id="cb25-14"><a href="intro.html#cb25-14" tabindex="-1"></a>    <span class="at">RIC =</span> <span class="fu">IQR</span>(valor),</span>
<span id="cb25-15"><a href="intro.html#cb25-15" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(valor, <span class="fl">0.25</span>),</span>
<span id="cb25-16"><a href="intro.html#cb25-16" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(valor, <span class="fl">0.75</span>),</span>
<span id="cb25-17"><a href="intro.html#cb25-17" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(valor),</span>
<span id="cb25-18"><a href="intro.html#cb25-18" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(valor),</span>
<span id="cb25-19"><a href="intro.html#cb25-19" tabindex="-1"></a>    <span class="at">asimetria =</span> <span class="fu">skewness</span>(valor),</span>
<span id="cb25-20"><a href="intro.html#cb25-20" tabindex="-1"></a>    <span class="at">curtosis =</span> <span class="fu">kurtosis</span>(valor)</span>
<span id="cb25-21"><a href="intro.html#cb25-21" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb25-22"><a href="intro.html#cb25-22" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">signif</span>(.x, <span class="dv">4</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb25-23"><a href="intro.html#cb25-23" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##         variable    n     media        sd   mediana       RIC        Q1
## 1            DFA 5863 6.533e-01  0.070960 6.436e-01 1.154e-01 5.961e-01
## 2            HNR 5863 2.168e+01  4.293000 2.192e+01 5.042e+00 1.940e+01
## 3      Jitter... 5863 6.156e-03  0.005628 4.900e-03 3.220e-03 3.580e-03
## 4    Jitter.Abs. 5863 4.403e-05  0.000036 3.453e-05 3.092e-05 2.242e-05
## 5     Jitter.DDP 5863 8.965e-03  0.009378 6.750e-03 5.150e-03 4.730e-03
## 6    Jitter.PPQ5 5863 3.278e-03  0.003734 2.490e-03 1.645e-03 1.825e-03
## 7     Jitter.RAP 5863 2.988e-03  0.003126 2.250e-03 1.710e-03 1.580e-03
## 8            NHR 5863 3.213e-02  0.059740 1.845e-02 2.051e-02 1.095e-02
## 9            PPE 5863 2.196e-01  0.091490 2.056e-01 1.082e-01 1.564e-01
## 10          RPDE 5863 5.414e-01  0.101000 5.422e-01 1.443e-01 4.697e-01
## 11       Shimmer 5863 3.404e-02  0.025840 2.753e-02 2.067e-02 1.911e-02
## 12 Shimmer.APQ11 5863 2.749e-02  0.020000 2.271e-02 1.707e-02 1.566e-02
## 13  Shimmer.APQ3 5863 1.716e-02  0.013240 1.370e-02 1.132e-02 9.280e-03
## 14  Shimmer.APQ5 5863 2.015e-02  0.016670 1.594e-02 1.298e-02 1.079e-02
## 15   Shimmer.DDA 5863 5.147e-02  0.039710 4.111e-02 3.398e-02 2.783e-02
## 16   Shimmer.dB. 5863 3.110e-01  0.230300 2.530e-01 1.900e-01 1.750e-01
## 17           age 5863 6.481e+01  8.828000 6.500e+01 1.400e+01 5.800e+01
## 18     test_time 5863 9.306e+01 53.320000 9.175e+01 9.112e+01 4.734e+01
##           Q3    minimo    maximo asimetria curtosis
## 1  7.115e-01 5.140e-01 8.656e-01   0.28170    2.117
## 2  2.445e+01 1.659e+00 3.788e+01  -0.81070    5.501
## 3  6.800e-03 8.300e-04 9.999e-02   6.44900   70.390
## 4  5.334e-05 2.250e-06 4.456e-04   3.28200   21.140
## 5  9.880e-03 9.800e-04 1.726e-01   6.94200   81.400
## 6  3.470e-03 4.300e-04 6.956e-02   7.58100   84.390
## 7  3.290e-03 3.300e-04 5.754e-02   6.94200   81.400
## 8  3.146e-02 2.860e-04 7.483e-01   6.54600   55.510
## 9  2.646e-01 2.198e-02 7.317e-01   1.08800    4.946
## 10 6.140e-01 1.510e-01 9.661e-01  -0.03744    2.933
## 11 3.978e-02 3.060e-03 2.686e-01   3.31300   18.240
## 12 3.273e-02 2.490e-03 2.755e-01   3.40400   22.110
## 13 2.060e-02 1.610e-03 1.627e-01   3.09800   17.730
## 14 2.377e-02 1.940e-03 1.670e-01   3.69700   22.220
## 15 6.180e-02 4.840e-03 4.880e-01   3.09800   17.730
## 16 3.650e-01 2.600e-02 2.107e+00   3.09900   16.090
## 17 7.200e+01 3.600e+01 8.500e+01  -0.38200    3.667
## 18 1.385e+02 3.958e-01 2.155e+02   0.07947    1.850</code></pre>
<p><strong><code>age</code>:</strong> La variable age presenta 5.863 registros, con una media de 64.81 años y una desviación estándar de 8.83 años, lo que evidencia una dispersión considerable en la edad de los participantes. El 50 % central de las observaciones se encuentra entre 58 y 72 años, con un rango intercuartílico de 14 años, indicando que la mayor concentración de registros corresponde a participantes dentro de este intervalo etario.</p>
<p>La edad observada varía entre 36 y 85 años, mostrando una amplitud de 49 años. Esta amplitud evidencia que, aunque el estudio se concentra principalmente en adultos mayores, existe una diferencia importante en las edades representadas en los registros.</p>
<p>La media (64.81) es ligeramente inferior al valor central de 65 años, comportamiento consistente con un coeficiente de asimetría de -0.382, que indica una asimetría negativa leve. Esto significa que existe una ligera extensión de la distribución hacia edades inferiores, aunque no se observa un sesgo pronunciado.</p>
<p>La curtosis de 3.67, superior al valor de referencia de 3 para una distribución normal bajo la definición utilizada, indica una distribución leptocúrtica, con una concentración relativamente mayor de observaciones alrededor de su centro y colas más pesadas que las de una distribución normal.</p>
<p><strong><code>test_time</code>:</strong> Presenta una media de 93.06 días y una desviación estándar de 53.32 días, lo que indica una variabilidad considerable en el tiempo transcurrido desde el reclutamiento de los participantes. El 50 % central de las observaciones se encuentra entre 47.34 y 138.46 días, con un RIC de 91.12 días, evidenciando que los registros abarcan un periodo amplio del seguimiento.</p>
<p>El valor mínimo es 0.39583 días y el máximo es 215.49 días, por lo que, después de la limpieza, todos los registros presentan valores de tiempo transcurrido no negativos y compatibles con la interpretación de esta variable. La asimetría de 0.0795, muy cercana a cero, indica que la distribución es aproximadamente simétrica, sin un sesgo marcado hacia ninguno de los extremos.</p>
<p>La curtosis de 1.8504 indica que la distribución presenta una concentración central menor que la de una distribución normal y colas relativamente menos pronunciadas. En conjunto, test_time muestra una distribución equilibrada alrededor de su valor central, con una dispersión amplia que refleja que las mediciones fueron realizadas en distintos momentos del periodo de seguimiento.</p>
<p><strong><code>Jitter...</code>:</strong> Presenta 5.863 registros, con una media de 0.00616 y una desviación estándar de 0.00563, lo que evidencia una variabilidad relativa considerable respecto a su nivel promedio.</p>
<p>El 50 % central de las observaciones se encuentra entre 0.00358 y 0.0068, con un rango intercuartílico de 0.00322. El rango observado va desde 0.00083 hasta 0.09999, mostrando una amplitud considerable y una concentración de la mayoría de los registros en valores bajos, acompañada de observaciones mucho mayores.</p>
<p>La diferencia entre la media (0.00616) y el valor central (0.0049) es consistente con un coeficiente de asimetría de 6.45, que evidencia una asimetría positiva. Por tanto, la distribución presenta una cola derecha extensa, generada por observaciones de Jitter considerablemente superiores a la concentración principal de los datos.</p>
<p>La curtosis de 70.39 refuerza este comportamiento, indicando una concentración importante de observaciones en valores bajos y presencia de valores extremos en la cola superior.</p>
<p><strong><code>Jitter.Abs.</code>:</strong> Presenta una media de 4.4 × 10<sup>-5</sup> y una desviación estándar de 3.6 × 10<sup>-5</sup>, evidenciando una variabilidad importante en relación con su magnitud promedio.</p>
<p>El 50 % central de los registros se encuentra entre 2.24 × 10<sup>-5</sup> y 5.33 × 10<sup>-5</sup>, con un rango intercuartílico de 3.09 × 10<sup>-5</sup>. Los valores observados oscilan entre 2.25 × 10<sup>-6</sup> y 4.46 × 10<sup>-4</sup>, mostrando una amplitud considerable respecto al nivel habitual de la variable.</p>
<p>El coeficiente de asimetría de 3.28 indica una asimetría positiva marcada, por lo que existen observaciones considerablemente superiores a la concentración principal de los datos.</p>
<p>La curtosis de 21.14, muy superior a 3, confirma una elevada concentración de valores alrededor de niveles bajos y una cola derecha pesada. En consecuencia, Jitter.Abs. presenta un comportamiento claramente no simétrico y potencialmente influido por valores extremos.</p>
<p><strong><code>Jitter.RAP</code>:</strong> La variable presenta una media de 0.00299 y una desviación estándar de 0.00313, indicando una dispersión ligeramente superior al valor promedio.</p>
<p>El 50 % central de las observaciones se encuentra entre 0.00158 y 0.00329, con un rango intercuartílico de 0.00171. El rango observado va desde 0.00033 hasta 0.05754.</p>
<p>El coeficiente de asimetría de 6.94 evidencia una asimetría positiva extremadamente elevada, indicando una cola derecha muy pronunciada. La diferencia entre la media (0.00299) y el valor central (0.00225) también es consistente con este comportamiento.</p>
<p>La curtosis de 81.4 es extremadamente superior a 3, por lo que la distribución presenta valores extremos muy alejados de la concentración principal de las observaciones.</p>
<p><strong><code>Jitter.PPQ5</code>:</strong> Presenta una media de 0.00328 y una desviación estándar de 0.00373, mostrando una dispersión elevada en relación con su magnitud promedio.</p>
<p>El 50 % central de las observaciones se concentra entre 0.00182 y 0.00347, con un rango intercuartílico de 0.00164. Los valores observados se encuentran entre 0.00043 y 0.06956.</p>
<p>El coeficiente de asimetría de 7.58 evidencia una asimetría positiva extremadamente pronunciada que, en conjunto con la curtosis de 84.39, evidencia que la mayoría de los registros presentan niveles relativamente bajos de Jitter.PPQ5, mientras que un número reducido de observaciones alcanza valores considerablemente superiores, generando una cola derecha muy pesada.</p>
<p><strong><code>Jitter.DDP</code>:</strong> Presenta una media de 0.00896 y una desviación estándar de 0.00938, evidenciando una variabilidad considerable respecto a su nivel promedio.</p>
<p>El 50 % central de los registros se encuentra entre 0.00473 y 0.00988, con un rango intercuartílico de 0.00515. Los valores observados oscilan entre 0.00098 y 0.17263.</p>
<p>La asimetría de 6.94 evidencia una asimetría positiva extremadamente pronunciada, indicando que la distribución presenta una cola derecha extensa.</p>
<p>La curtosis de 81.4 es muy superior al valor de referencia de una distribución normal, por lo que Jitter.DDP presenta una fuerte concentración de registros en valores bajos y un conjunto reducido de valores elevados.</p>
<p><strong><code>Shimmer</code>:</strong> Presenta una media de 0.034 y una desviación estándar de 0.0258, evidenciando una dispersión importante respecto a su valor promedio.</p>
<p>El 50 % central de los registros se encuentra entre 0.01911 y 0.03978, con un rango intercuartílico de 0.02067. El rango observado va desde 0.00306 hasta 0.26863, lo que evidencia una amplitud considerable en los valores registrados.</p>
<p>El coeficiente de asimetría de 3.31 indica una asimetría positiva marcada, mostrando una cola derecha generada por observaciones con valores elevados.</p>
<p>La curtosis de 18.24 es considerablemente superior a 3, indicando una distribución con una concentración de observaciones alrededor de valores relativamente bajos y presencia de valores extremos superiores.</p>
<p><strong><code>Shimmer.APQ3</code>:</strong> Presenta una media de 0.01716 y una desviación estándar de 0.01324, lo que evidencia una dispersión considerable en relación con su valor promedio.</p>
<p>El 50 % central de los registros se encuentra entre 0.00928 y 0.0206, con un rango intercuartílico de 0.01132. Los valores observados oscilan entre 0.00161 y 0.16267, mostrando una amplitud considerable en comparación con los valores que concentran la mayor parte de las observaciones.</p>
<p>El coeficiente de asimetría de 3.1 evidencia una asimetría positiva marcada, indicando que existe una cola extendida hacia valores superiores y que algunas observaciones presentan niveles considerablemente mayores que los habituales.</p>
<p>La curtosis de 17.73, muy superior al valor de referencia de 3, indica una alta concentración de observaciones alrededor de los valores centrales, acompañada de la presencia de valores alejados de dicha concentración. Por tanto, la variable presenta un comportamiento claramente influenciado por observaciones extremas hacia valores elevados.</p>
<p><strong><code>Shimmer.APQ5</code>:</strong> Presenta una media de 0.02015 y una desviación estándar de 0.01667, evidenciando una dispersión considerable respecto a su valor promedio.</p>
<p>El 50 % central de las observaciones se encuentra entre 0.01079 y 0.02377, con un rango intercuartílico de 0.01298. Los valores observados se encuentran entre 0.00194 y 0.16702, mostrando una amplitud considerable respecto al intervalo donde se concentra la mayor parte de los registros.</p>
<p>La asimetría de 3.7 evidencia una asimetría positiva marcada, indicando que existe una cola extendida hacia valores superiores y que un conjunto reducido de observaciones presenta valores considerablemente mayores que los registrados habitualmente.</p>
<p>La curtosis de 22.22, considerablemente superior a 3, indica una alta concentración de observaciones alrededor de los valores centrales junto con la presencia de valores alejados de dicha concentración. En conjunto, estos resultados muestran que la variable está fuertemente influenciada por observaciones elevadas poco frecuentes.</p>
<p><strong><code>Shimmer.APQ11</code>:</strong> Presenta una media de 0.02749 y una desviación estándar de 0.02, mostrando una dispersión considerable respecto a su promedio.</p>
<p>El 50 % central de los registros se encuentra entre 0.01566 y 0.03273, con un rango intercuartílico de 0.01707. Los valores observados oscilan entre 0.00249 y 0.27546, evidenciando una amplitud considerable respecto al intervalo donde se concentra la mayor parte de las observaciones.</p>
<p>El coeficiente de asimetría de 3.4 indica una asimetría positiva marcada, mostrando una extensión considerable de los valores hacia el extremo superior y la existencia de observaciones notablemente superiores al comportamiento central.</p>
<p>La curtosis de 22.11, muy superior a 3, indica una alta concentración de observaciones alrededor de los valores centrales y una presencia importante de valores alejados de este centro. Esto sugiere que los valores elevados, aunque menos frecuentes, tienen una influencia relevante sobre el comportamiento general de la variable.</p>
<p><strong><code>Shimmer.DDA</code>:</strong> Presenta una media de 0.05147 y una desviación estándar de 0.03971, evidenciando una dispersión elevada en relación con su valor promedio.</p>
<p>El 50 % central de las observaciones se encuentra entre 0.02783 y 0.0618, con un rango intercuartílico de 0.03398. El rango completo se extiende desde 0.00484 hasta 0.48802, mostrando una amplitud considerable frente al intervalo central de los datos.</p>
<p>El coeficiente de asimetría de 3.1 indica una asimetría positiva marcada, por lo que existe una extensión de los valores hacia el extremo superior y algunas observaciones alcanzan niveles considerablemente mayores que los habituales.</p>
<p>La curtosis de 17.73, superior a 3, indica una alta concentración de observaciones alrededor de los valores centrales acompañada de la presencia de valores alejados de dicha concentración. En conjunto, esto evidencia que algunos valores elevados tienen una influencia importante sobre la forma general de los datos.</p>
<p><strong><code>Shimmer.dB.</code>:</strong> Presenta una media de 0.311 y una desviación estándar de 0.23, lo que evidencia una dispersión considerable respecto a su valor promedio.</p>
<p>El 50 % central de las observaciones se encuentra entre 0.175 y 0.365, con un rango intercuartílico de 0.19. Los valores observados oscilan entre 0.026 y 2.107, mostrando una amplitud considerable en comparación con el intervalo central de los registros.</p>
<p>El coeficiente de asimetría de 3.1 evidencia una asimetría positiva marcada, indicando una extensión de los valores hacia el extremo superior y la presencia de observaciones considerablemente mayores que la mayoría de los registros.</p>
<p>La curtosis de 16.09, muy superior a 3, indica una alta concentración de observaciones alrededor de los valores centrales junto con la existencia de valores alejados de esta concentración. Por tanto, los valores elevados, aunque menos frecuentes, tienen una influencia importante sobre la variabilidad observada en la variable.</p>
<p><strong><code>NHR</code>:</strong> Presenta una media de 0.0321 y una desviación estándar de 0.0597. La desviación estándar es considerablemente superior a la media, lo que evidencia una variabilidad relativa elevada en los registros.</p>
<p>El 50 % central de las observaciones se encuentra entre 0.01095 y 0.03146, con un rango intercuartílico de 0.02051. Sin embargo, los valores observados se extienden desde 0.000286 hasta 0.74826, mostrando una amplitud muy elevada respecto al intervalo donde se concentra la mayor parte de las observaciones.</p>
<p>El coeficiente de asimetría de 6.55 evidencia una asimetría positiva pronunciada, indicando que existe una cola derecha muy extensa producida por un conjunto reducido de observaciones con valores excepcionalmente altos.</p>
<p>La curtosis de 55.51, muy superior a 3, indica una concentración muy elevada de observaciones alrededor de valores bajos y la presencia de valores extremadamente alejados de dicha concentración. En consecuencia, los valores altos, aunque poco frecuentes, tienen una influencia importante sobre la media y la desviación estándar de NHR.</p>
<p><strong><code>HNR</code>:</strong> Presenta una media de 21.68 y una desviación estándar de 4.29, evidenciando una dispersión moderada respecto a su valor promedio.</p>
<p>El 50 % central de los registros se encuentra entre 19.4 y 24.45, con un rango intercuartílico de 5.04. Los valores observados oscilan entre 1.66 y 37.88, mostrando una amplitud considerable en comparación con el intervalo central.</p>
<p>La media (21.68) se encuentra ligeramente por debajo del valor central (21.92), lo cual es consistente con el coeficiente de asimetría de -0.811, que indica una asimetría negativa moderada. Esto significa que los valores presentan una extensión ligeramente mayor hacia el extremo inferior.</p>
<p>La curtosis de 5.5, superior a 3, indica una mayor concentración de observaciones alrededor de los valores centrales y una presencia de valores alejados de esta concentración. Por tanto, aunque la mayoría de los registros se encuentra en un intervalo relativamente definido, existen observaciones que se alejan considerablemente de dicho comportamiento central.</p>
<p><strong><code>RPDE</code>:</strong> Presenta una media de 0.541 y una desviación estándar de 0.101, evidenciando una dispersión moderada alrededor de su valor promedio.</p>
<p>El 50 % central de las observaciones se encuentra entre 0.47 y 0.614, con un rango intercuartílico de 0.144. Los valores observados oscilan entre 0.151 y 0.966, mostrando una amplitud considerable respecto al intervalo central.</p>
<p>La media (0.541) es prácticamente igual al valor central (0.542), y el coeficiente de asimetría de -0.037 se encuentra muy próximo a cero. Esto indica que los valores se encuentran aproximadamente equilibrados alrededor del centro, sin una inclinación importante hacia valores inferiores o superiores.</p>
<p>La curtosis de 2.93 se encuentra muy próxima al valor de referencia de 3, lo que indica que la concentración de observaciones y el comportamiento de los valores alejados del centro son similares a los esperados en una distribución normal, aunque este resultado por sí solo no permite establecer que los datos sean normales.</p>
<p><strong><code>DFA</code>:</strong> Presenta una media de 0.653 y una desviación estándar de 0.071, indicando una dispersión relativamente moderada alrededor de su valor promedio.</p>
<p>El 50 % central de las observaciones se encuentra entre 0.596 y 0.711, con un rango intercuartílico de 0.115. Los valores observados oscilan entre 0.514 y 0.866, representando una amplitud de aproximadamente 0.352.</p>
<p>La media (0.653) es ligeramente superior al valor central (0.644), mientras que el coeficiente de asimetría de 0.282 indica una asimetría positiva leve, con una ligera extensión hacia valores superiores.</p>
<p>La curtosis de 2.12, inferior a 3, indica que existe una menor concentración de observaciones alrededor del centro y menor presencia de valores alejados que la esperada en una distribución normal. Esto sugiere que los valores presentan una dispersión relativamente más uniforme dentro del rango observado.</p>
<p><strong><code>PPE</code>:</strong> Presenta una media de 0.22 y una desviación estándar de 0.0915, evidenciando una dispersión moderada respecto a su valor promedio.</p>
<p>El 50 % central de las observaciones se encuentra entre 0.156 y 0.265, con un rango intercuartílico de 0.108. Los valores observados oscilan entre 0.02198 y 0.73173, mostrando una amplitud considerable en comparación con el intervalo central.</p>
<p>El coeficiente de asimetría de 1.09 indica una asimetría positiva moderada, lo que evidencia una extensión de los valores hacia el extremo superior y la presencia de algunas observaciones considerablemente mayores que la concentración principal.</p>
<p>La curtosis de 4.95, superior a 3, indica una mayor concentración de observaciones alrededor de los valores centrales y una presencia importante de valores alejados del centro. En conjunto, la variable presenta una cola superior apreciable y cierta influencia de valores elevados sobre sus medidas de tendencia central y dispersión.</p>
</div>
<div id="histogramas" class="section level3 hasAnchor" number="1.2.2">
<h3><span class="header-section-number">1.2.2</span> Histogramas<a href="intro.html#histogramas" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="intro.html#cb27-1" tabindex="-1"></a>variables_numericas <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="intro.html#cb27-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric), <span class="sc">-</span>motor_UPDRS, <span class="sc">-</span>total_UPDRS) <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="intro.html#cb27-3" tabindex="-1"></a>  <span class="fu">names</span>()</span>
<span id="cb27-4"><a href="intro.html#cb27-4" tabindex="-1"></a></span>
<span id="cb27-5"><a href="intro.html#cb27-5" tabindex="-1"></a><span class="cf">for</span> (variable <span class="cf">in</span> variables_numericas) {</span>
<span id="cb27-6"><a href="intro.html#cb27-6" tabindex="-1"></a>  </span>
<span id="cb27-7"><a href="intro.html#cb27-7" tabindex="-1"></a>  grafico <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> .data[[variable]])) <span class="sc">+</span></span>
<span id="cb27-8"><a href="intro.html#cb27-8" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(</span>
<span id="cb27-9"><a href="intro.html#cb27-9" tabindex="-1"></a>      <span class="at">bins =</span> <span class="dv">30</span>,</span>
<span id="cb27-10"><a href="intro.html#cb27-10" tabindex="-1"></a>      <span class="at">fill =</span> <span class="st">&quot;pink&quot;</span>,</span>
<span id="cb27-11"><a href="intro.html#cb27-11" tabindex="-1"></a>      <span class="at">color =</span> <span class="st">&quot;black&quot;</span></span>
<span id="cb27-12"><a href="intro.html#cb27-12" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb27-13"><a href="intro.html#cb27-13" tabindex="-1"></a>    <span class="fu">labs</span>(</span>
<span id="cb27-14"><a href="intro.html#cb27-14" tabindex="-1"></a>      <span class="at">title =</span> <span class="fu">paste</span>(<span class="st">&quot;Distribución de&quot;</span>, variable),</span>
<span id="cb27-15"><a href="intro.html#cb27-15" tabindex="-1"></a>      <span class="at">x =</span> variable,</span>
<span id="cb27-16"><a href="intro.html#cb27-16" tabindex="-1"></a>      <span class="at">y =</span> <span class="st">&quot;Frecuencia&quot;</span></span>
<span id="cb27-17"><a href="intro.html#cb27-17" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb27-18"><a href="intro.html#cb27-18" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span>
<span id="cb27-19"><a href="intro.html#cb27-19" tabindex="-1"></a>  </span>
<span id="cb27-20"><a href="intro.html#cb27-20" tabindex="-1"></a>  <span class="fu">print</span>(grafico)</span>
<span id="cb27-21"><a href="intro.html#cb27-21" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/histogramas-independientes-1.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/histogramas-independientes-2.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/histogramas-independientes-3.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/histogramas-independientes-4.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/histogramas-independientes-5.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/histogramas-independientes-6.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/histogramas-independientes-7.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/histogramas-independientes-8.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/histogramas-independientes-9.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/histogramas-independientes-10.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/histogramas-independientes-11.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/histogramas-independientes-12.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/histogramas-independientes-13.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/histogramas-independientes-14.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/histogramas-independientes-15.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/histogramas-independientes-16.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/histogramas-independientes-17.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/histogramas-independientes-18.png" alt="" width="672" />
<strong><code>age</code>:</strong> La distribución de la edad muestra que la mayoría de los pacientes son adultos mayores, con picos de frecuencia muy claros entre los 55 y 60 años, entre los 65 y 68 años, y entre los 72 y 74 años, además de un grupo pequeño aislado alrededor de los 36 años. Como la edad no cambia dentro de un paciente, cada barra refleja cuántos pacientes tienen esa edad y cuántas grabaciones aportó cada uno; el grupo de los 36 años, por ejemplo, es un solo paciente. Esta concentración en edades avanzadas coincide con el comportamiento real de la enfermedad de Parkinson, donde los diagnósticos aumentan considerablemente a partir de los 60 años. Tener pacientes con diferentes edades servirá para analizar si el empeoramiento en la voz y en el control motor se debe al avance de la enfermedad o simplemente al envejecimiento natural.</p>
<p><strong><code>test_time</code>:</strong> El tiempo de prueba muestra un registro continuo y parejo durante los primeros 170 días del estudio, con una pequeña baja cerca del día 90 y una caída marcada después del día 180. Esto indica que a los pacientes se les realizó un seguimiento constante y organizado durante aproximadamente seis meses. La disminución a partir del día 180 ocurre porque varios pacientes completaron su tiempo en el estudio o dejaron de enviar mediciones, garantizando una base de datos sólida para evaluar cómo evolucionan los síntomas con el paso de los meses.</p>
<p><strong><code>Jitter...</code>:</strong> La medida porcentual de variación en la frecuencia de la voz (Jitter(…)) se concentra en valores bajos, casi todos menores al 0.01 (1 %). La gráfica tiene una cola larga hacia la derecha que llega a valores superiores a 0.05, donde se ubican las tomas de voz con inestabilidades graves. En la práctica, esto significa que las alteraciones fuertes en el tono no son lo habitual en todas las pruebas, sino eventos específicos que destacan sobre el resto.</p>
<p><strong><code>Jitter.Abs.</code>:</strong> La variación absoluta de la frecuencia en microsegundos (Jitter.Abs.) concentra casi todos sus datos en la zona baja, entre 2 × 10<sup>-5</sup> y 6 × 10<sup>-5</sup> segundos. La cola extendida hacia la derecha muestra que existen pocas mediciones con una alteración de voz severa. La forma de esta gráfica es idéntica a la de Jitter(…), lo que confirma que ambas variables miden prácticamente lo mismo y que será necesario combinarlas o seleccionar solo una durante la ingeniería de características para no duplicar información.</p>
<p><strong><code>Jitter.RAP</code>:</strong> Esta variable repite el mismo patrón de acumulación en valores bajos, situando su punto más alto muy cerca de cero (entre 0.001 y 0.005) y cayendo rápidamente hacia la derecha. Como esta métrica evalúa los cambios de frecuencia entre ciclos de voz cercanos, la falta de valores altos demuestra que solo un grupo reducido de pruebas presenta inestabilidad frecuente. Su parecido con los otros indicadores de frecuencia confirma que todas las variables de la familia Jitter están midiendo el mismo problema de trasfondo.</p>
<p><strong><code>Jitter.PPQ5</code>:</strong> El indicador de variación de tono en bloques de 5 periodos (Jitter.PPQ5) muestra una acumulación masiva en valores menores a 0.005 y se reduce rápidamente hacia la derecha hasta llegar a 0.03. Al promediar la voz en intervalos más largos para suavizar cambios repentinos, el hecho de que la gráfica siga concentrada en la izquierda confirma que la inestabilidad vocal sostenida es un síntoma claro pero presente solo en las pruebas de pacientes con mayor afectación.</p>
<p><strong><code>Jitter.DDP</code>:</strong> Esta métrica presenta una forma idéntica a Jitter.RAP, con la mayoría de los datos amontonados por debajo del 0.01 y unos pocos casos dispersos hacia el 0.05. Esta similitud se debe a que, por definición matemática, los valores de DDP son exactamente el triple de los de RAP. Al ser una copia multiplicada por tres, incluir ambas variables en un análisis inferencial o en un modelo resultaría redundante.</p>
<p><strong><code>Shimmer</code>:</strong> La variación en la amplitud de la voz se concentra principalmente en valores bajos, entre 0.02 y 0.05, donde alcanza su pico más alto antes de caer rápidamente. La gráfica muestra una cola larga hacia la derecha que se extiende hasta 0.25, lo que representa un número pequeño de pruebas con cambios de volumen muy pronunciados. Esta acumulación en el extremo izquierdo indica que las alteraciones graves de amplitud no son la norma en todas las grabaciones, sino casos específicos.</p>
<p><strong><code>Shimmer.dB.</code>:</strong> La medida en decibelios sigue el mismo patrón, situando la mayor cantidad de datos entre 0.15 y 0.35 dB. Presenta una caída progresiva hacia la derecha con algunos registros dispersos que superan 1.5 dB. Dado que mide lo mismo que la variable anterior pero en una escala logarítmica, la forma es prácticamente la misma, ofreciendo información equivalente sobre los cambios de volumen en la voz.</p>
<p><strong><code>Shimmer.APQ3</code>:</strong> La inestabilidad de amplitud evaluada en grupos de 3 periodos se agrupa con fuerza en valores muy pequeños, alcanzando su punto máximo entre 0.01 y 0.02. A partir de ahí desciende de forma acelerada y deja una cola muy fina que llega hasta 0.15. Esto confirma que las variaciones bruscas a corto plazo son poco habituales en la muestra.</p>
<p><strong><code>Shimmer.APQ5</code>:</strong> El indicador basado en bloques de 5 periodos repite una forma casi idéntica a las anteriores, concentrando el pico principal alrededor de 0.015. Mantiene la mayor parte de los registros en la zona baja y deja solo un puñado de observaciones por encima de 0.05, lo que refleja que el patrón de comportamiento se conserva.</p>
<p><strong><code>Shimmer.APQ11</code>:</strong> La evaluación en bloques más largos de 11 periodos mantiene el pico dominante en la zona baja (entre 0.015 y 0.03) y una cola que se estira suavemente hacia la derecha. La similitud con las otras variantes APQ demuestra una alta dependencia entre ellas, por lo que medir la amplitud en diferentes tamaños de ventana entrega un resultado prácticamente idéntico.</p>
<p><strong><code>Shimmer.DDA</code>:</strong> Esta variable muestra la misma tendencia que las anteriores, con la mayoría de las mediciones concentradas por debajo de 0.08 y una cola muy larga que se extiende hasta 0.4. Al ser una variante directamente derivada del cálculo de APQ3, no aporta información nueva y genera redundancia con el resto del grupo.</p>
<p><strong><code>NHR</code>:</strong> La relación entre ruido y señal armónica se amontona casi por completo en la zona más baja del gráfico, entre 0.01 y 0.05. Apenas unos pocos casos aislados superan el valor de 0.2. Esto señala que la presencia de ruido excesivo en las grabaciones es un evento muy poco frecuente y bien delimitado dentro de los datos.</p>
<p><strong><code>HNR</code>:</strong> A diferencia de las anteriores, la proporción de armonía respecto al ruido presenta una forma de campana bien centrada, con el punto más alto entre los 21 y 24 dB. Los datos se distribuyen de manera pareja hacia ambos lados, aunque con un leve estiramiento en la zona baja (de 0 a 10 dB) que corresponde a las grabaciones con peor calidad vocal o más ruido de fondo.</p>
<p><strong><code>RPDE</code>:</strong> La medida de complejidad del tono muestra una distribución en forma de campana muy limpia y equilibrada, con su centro justo en el rango de 0.5 a 0.55. Los valores se extienden suavemente desde 0.25 hasta 0.75, lo que indica que esta variable se comporta de forma bastante regular en la muestra sin concentraciones extremas en los bordes.</p>
<p><strong><code>DFA</code>:</strong> El indicador de fractalidad de la señal presenta dos elevaciones muy claras: la primera y más alta está entre 0.6 y 0.63, mientras que la segunda se ubica entre 0.71 y 0.74. Esta separación en dos grupos principales sugiere que los pacientes se dividen en dos categorías según la estructura de sus frecuencias de voz.</p>
<p><strong><code>PPE</code>:</strong> La medida de variación en la frecuencia fundamental muestra una acumulación clara alrededor del rango de 0.18 a 0.22, donde alcanza su pico de máxima frecuencia. A partir de ese punto, la barra desciende de forma progresiva hacia la derecha, dejando una cola suave que se extiende hasta valores cercanos a 0.6. Esto indica que la gran mayoría de los registros presentan un comportamiento relativamente estable en el tono, mientras que las variaciones más marcadas o inestables ocurren únicamente en un grupo reducido de pruebas.</p>
</div>
<div id="dispersión-frente-a-motor_updrs" class="section level3 hasAnchor" number="1.2.3">
<h3><span class="header-section-number">1.2.3</span> Dispersión frente a <code>motor_UPDRS</code><a href="intro.html#dispersi%C3%B3n-frente-a-motor_updrs" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="intro.html#cb28-1" tabindex="-1"></a>variables_numericas <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="intro.html#cb28-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric), <span class="sc">-</span>motor_UPDRS, <span class="sc">-</span>total_UPDRS) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="intro.html#cb28-3" tabindex="-1"></a>  <span class="fu">names</span>()</span>
<span id="cb28-4"><a href="intro.html#cb28-4" tabindex="-1"></a></span>
<span id="cb28-5"><a href="intro.html#cb28-5" tabindex="-1"></a><span class="cf">for</span> (variable <span class="cf">in</span> variables_numericas) {</span>
<span id="cb28-6"><a href="intro.html#cb28-6" tabindex="-1"></a>  </span>
<span id="cb28-7"><a href="intro.html#cb28-7" tabindex="-1"></a>  grafico <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> .data[[variable]], <span class="at">y =</span> motor_UPDRS)) <span class="sc">+</span></span>
<span id="cb28-8"><a href="intro.html#cb28-8" tabindex="-1"></a>    <span class="fu">geom_point</span>(</span>
<span id="cb28-9"><a href="intro.html#cb28-9" tabindex="-1"></a>      <span class="at">alpha =</span> <span class="fl">0.5</span>,</span>
<span id="cb28-10"><a href="intro.html#cb28-10" tabindex="-1"></a>      <span class="at">color =</span> <span class="st">&quot;#C77D98&quot;</span></span>
<span id="cb28-11"><a href="intro.html#cb28-11" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb28-12"><a href="intro.html#cb28-12" tabindex="-1"></a>    <span class="fu">labs</span>(</span>
<span id="cb28-13"><a href="intro.html#cb28-13" tabindex="-1"></a>      <span class="at">title =</span> <span class="fu">paste</span>(variable, <span class="st">&quot;vs motor_UPDRS&quot;</span>),</span>
<span id="cb28-14"><a href="intro.html#cb28-14" tabindex="-1"></a>      <span class="at">x =</span> variable,</span>
<span id="cb28-15"><a href="intro.html#cb28-15" tabindex="-1"></a>      <span class="at">y =</span> <span class="st">&quot;motor_UPDRS&quot;</span></span>
<span id="cb28-16"><a href="intro.html#cb28-16" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb28-17"><a href="intro.html#cb28-17" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span>
<span id="cb28-18"><a href="intro.html#cb28-18" tabindex="-1"></a>  </span>
<span id="cb28-19"><a href="intro.html#cb28-19" tabindex="-1"></a>  <span class="fu">print</span>(grafico)</span>
<span id="cb28-20"><a href="intro.html#cb28-20" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-1.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-2.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-3.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-4.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-5.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-6.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-7.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-8.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-9.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-10.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-11.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-12.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-13.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-14.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-15.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-16.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-17.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-vs-motor-updrs-18.png" alt="" width="672" />
<strong><code>age</code> vs <code>motor_UPDRS</code>:</strong> Los puntos forman franjas verticales, una por paciente, porque la edad no cambia dentro de una persona. Los pacientes más jóvenes (36 y entre 49 y 60 años) se concentran en la mitad baja de la escala, mientras que entre los 65 y los 75 años aparecen las franjas que llegan a 35 o más puntos. La tendencia es visible pero débil: en cada edad conviven pacientes leves y severos.</p>
<p><strong><code>test_time</code> vs <code>motor_UPDRS</code>:</strong> Cada paciente dibuja una trayectoria casi horizontal a lo largo de los 200 días de seguimiento, con una inclinación leve en la mayoría. Como las trayectorias cubren toda la escala en cualquier momento del estudio, el tiempo transcurrido, por sí solo, no cambia el nivel de afectación motora del conjunto: lo que se ve es la evolución lenta de cada persona desde su propio nivel.</p>
<p><strong><code>Jitter...</code> vs <code>motor_UPDRS</code>:</strong> Casi todos los registros forman una banda vertical en valores de Jitter menores a 0.02 que cubre toda la escala motora, de 5 a 40 puntos. Los pocos registros con Jitter alto, hacia 0.05 y 0.1, se ubican sobre todo entre 15 y 35 puntos, algo por encima del centro de la banda, pero son tan escasos que la asociación es débil.</p>
<p><strong><code>Jitter.Abs.</code> vs <code>motor_UPDRS</code>:</strong> El patrón es prácticamente idéntico al de Jitter porcentual: una banda densa por debajo de 0.0001 segundos que abarca todas las puntuaciones motoras y una cola dispersa a la derecha con pocos registros. La escasez de datos en niveles altos de alteración absoluta impide ver una relación clara.</p>
<p><strong><code>Jitter.RAP</code> vs <code>motor_UPDRS</code>:</strong> La mayor parte de las observaciones se amontona cerca del origen y ocupa todo el rango de severidad. Los registros con inestabilidad rápida más alta (por encima de 0.02) tienden a quedar en la mitad superior de la escala, lo que sugiere que una voz más inestable entre ciclos inmediatos acompaña a evaluaciones motoras algo más severas, aunque con mucha dispersión.</p>
<p><strong><code>Jitter.PPQ5</code> vs <code>motor_UPDRS</code>:</strong> Repite la forma de las otras variables de la familia Jitter: banda densa en valores bajos y cola corta a la derecha. Al promediar el tono en bloques de 5 periodos se suavizan las variaciones pequeñas, pero la lectura es la misma: a mayor alteración vocal acumulada, los registros se sitúan con algo más de frecuencia en puntajes motores altos.</p>
<p><strong><code>Jitter.DDP</code> vs <code>motor_UPDRS</code>:</strong> La gráfica es visualmente idéntica a la de Jitter.RAP, solo que con el eje horizontal extendido hasta 0.15 por la escala multiplicativa. Muestra exactamente la misma nube, lo que refuerza que no aporta información nueva frente a RAP para describir el estado motor.</p>
<p><strong><code>Shimmer</code> vs <code>motor_UPDRS</code>:</strong> La gran masa de puntos se ubica en variaciones de amplitud menores a 0.05 y cubre toda la escala motora. Los registros con cambios de volumen más drásticos, entre 0.1 y 0.25, aparecen con más frecuencia por encima de los 20 puntos que por debajo, lo que apunta a una asociación positiva, pero leve.</p>
<p><strong><code>Shimmer.dB.</code> vs <code>motor_UPDRS</code>:</strong> La nube es la misma que la de Shimmer en escala logarítmica: la mayoría de las mediciones se acumula por debajo de 0.5 dB, y los pocos registros con alta variación de volumen, hacia 1.5 y 2 dB, se dispersan entre 15 y 35 puntos, con mayor presencia en la parte alta de la escala.</p>
<p><strong><code>Shimmer.APQ3</code> vs <code>motor_UPDRS</code>:</strong> La enorme mayoría de las mediciones se agrupa por debajo de 0.05 y ocupa todo el rango de severidad. La cola de valores altos es corta y poco poblada, de modo que apenas se insinúa una mayor severidad en los registros más inestables.</p>
<p><strong><code>Shimmer.APQ5</code> vs <code>motor_UPDRS</code>:</strong> Comportamiento casi idéntico al de APQ3: concentración masiva cerca de cero y una cola dispersa en la que los valores más altos de inestabilidad coinciden, con muchas excepciones, con puntajes motores por encima del promedio.</p>
<p><strong><code>Shimmer.APQ11</code> vs <code>motor_UPDRS</code>:</strong> Es la variable de la familia Shimmer donde la asociación se ve un poco más clara: los registros con APQ11 superior a 0.05 se concentran entre 20 y 35 puntos, mientras que la banda densa de valores bajos sigue cubriendo toda la escala. Aun así, la relación es débil.</p>
<p><strong><code>Shimmer.DDA</code> vs <code>motor_UPDRS</code>:</strong> Muestra una distribución idéntica a la de APQ3 por su definición matemática, con casi todas las observaciones amontonadas cerca del origen por debajo de 0.1 y una cola escasa a la derecha.</p>
<p><strong><code>NHR</code> vs <code>motor_UPDRS</code>:</strong> La inmensa mayoría de los datos se agrupa en valores de NHR cercanos a 0 y abarca toda la escala motora. Los pocos registros con ruido alto, hacia 0.4 y 0.7, se reparten entre 15 y 35 puntos sin un patrón nítido.</p>
<p><strong><code>HNR</code> vs <code>motor_UPDRS</code>:</strong> A diferencia de las anteriores, los datos se distribuyen de forma amplia entre 10 y 30 dB. Los registros con HNR bajo (por debajo de 20 dB) aparecen con más frecuencia en la mitad alta de la escala motora, y los de HNR alto (por encima de 25 dB) en la mitad baja: una mayor proporción de señal limpia respecto al ruido se asocia, débilmente, con menor deterioro motor.</p>
<p><strong><code>RPDE</code> vs <code>motor_UPDRS</code>:</strong> Los datos cubren de forma amplia y dispersa el eje entre 0.25 y 0.75, y a cualquier nivel de RPDE hay registros de toda la escala. Los valores altos de entropía son algo más frecuentes entre los puntajes motores elevados, lo que sugiere una asociación positiva suave.</p>
<p><strong><code>DFA</code> vs <code>motor_UPDRS</code>:</strong> Los puntos se reparten en dos franjas verticales, alrededor de 0.6 y de 0.75, que corresponden a los dos grupos vistos en el histograma. La franja de DFA más bajo contiene más registros con puntajes altos que la de DFA elevado, de modo que el exponente de escalado fractal guarda una relación ligeramente inversa con la severidad motora.</p>
<p><strong><code>PPE</code> vs <code>motor_UPDRS</code>:</strong> La nube es amplia entre 0.1 y 0.5. Aunque la mayoría de los registros tiene PPE menor a 0.3 y ocupa todo el rango de severidad, las mediciones con PPE más alto se ubican con más frecuencia entre 25 y 35 puntos, lo que la convierte en una de las medidas acústicas con asociación positiva más visible, aunque sigue siendo débil.</p>
</div>
</div>
<div id="caracterización-de-la-variable-categórica-sex" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Caracterización de la variable categórica <code>sex</code><a href="intro.html#caracterizaci%C3%B3n-de-la-variable-categ%C3%B3rica-sex" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><code>sex</code> es la única variable categórica. Como cada paciente aporta muchas grabaciones, la mostramos por registros y por pacientes.</p>
<div id="distribución-por-registros-y-por-pacientes" class="section level3 hasAnchor" number="1.3.1">
<h3><span class="header-section-number">1.3.1</span> Distribución por registros y por pacientes<a href="intro.html#distribuci%C3%B3n-por-registros-y-por-pacientes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="intro.html#cb29-1" tabindex="-1"></a>tabla_sexo <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="intro.html#cb29-2" tabindex="-1"></a>  <span class="fu">count</span>(sex, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="intro.html#cb29-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(n <span class="sc">/</span> <span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>))</span>
<span id="cb29-4"><a href="intro.html#cb29-4" tabindex="-1"></a></span>
<span id="cb29-5"><a href="intro.html#cb29-5" tabindex="-1"></a>tabla_sexo</span></code></pre></div>
<pre><code>##         sex    n Porcentaje
## 1 Masculino 3996       68.2
## 2  Femenino 1867       31.8</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="intro.html#cb31-1" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="intro.html#cb31-2" tabindex="-1"></a>  <span class="fu">distinct</span>(subject., sex) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="intro.html#cb31-3" tabindex="-1"></a>  <span class="fu">count</span>(sex, <span class="at">name =</span> <span class="st">&quot;pacientes&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="intro.html#cb31-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(pacientes <span class="sc">/</span> <span class="fu">sum</span>(pacientes) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>))</span></code></pre></div>
<pre><code>##         sex pacientes Porcentaje
## 1 Masculino        28       66.7
## 2  Femenino        14       33.3</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="intro.html#cb33-1" tabindex="-1"></a>tabla_sexo <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="intro.html#cb33-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Etiqueta =</span> <span class="fu">paste0</span>(n, <span class="st">&quot; (&quot;</span>, Porcentaje, <span class="st">&quot;%)&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="intro.html#cb33-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> sex, <span class="at">y =</span> n)) <span class="sc">+</span></span>
<span id="cb33-4"><a href="intro.html#cb33-4" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;#FAD0C4&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#C2185B&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb33-5"><a href="intro.html#cb33-5" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Etiqueta), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb33-6"><a href="intro.html#cb33-6" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>))) <span class="sc">+</span></span>
<span id="cb33-7"><a href="intro.html#cb33-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribución de los registros según el sexo del paciente&quot;</span>,</span>
<span id="cb33-8"><a href="intro.html#cb33-8" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb33-9"><a href="intro.html#cb33-9" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Número de registros&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-10"><a href="intro.html#cb33-10" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/grafico-sexo-1.png" alt="" width="672" /></p>
<p>Dos de cada tres registros son de hombres (3.996 frente a 1.867), y lo mismo pasa con los pacientes: 28 hombres y 14 mujeres. La proporción es coherente con la mayor frecuencia del Parkinson en hombres, pero deja un grupo de mujeres pequeño, algo a tener en cuenta cuando se comparen por paciente.</p>
</div>
<div id="severidad-motora-según-el-sexo" class="section level3 hasAnchor" number="1.3.2">
<h3><span class="header-section-number">1.3.2</span> Severidad motora según el sexo<a href="intro.html#severidad-motora-seg%C3%BAn-el-sexo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Ahora comparemos la severidad motora según el sexo del paciente.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="intro.html#cb34-1" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="intro.html#cb34-2" tabindex="-1"></a>  <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="intro.html#cb34-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb34-4"><a href="intro.html#cb34-4" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(motor_UPDRS),</span>
<span id="cb34-5"><a href="intro.html#cb34-5" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(motor_UPDRS),</span>
<span id="cb34-6"><a href="intro.html#cb34-6" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(motor_UPDRS),</span>
<span id="cb34-7"><a href="intro.html#cb34-7" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(motor_UPDRS),</span>
<span id="cb34-8"><a href="intro.html#cb34-8" tabindex="-1"></a>    <span class="at">RIC =</span> <span class="fu">IQR</span>(motor_UPDRS),</span>
<span id="cb34-9"><a href="intro.html#cb34-9" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(motor_UPDRS, <span class="fl">0.25</span>),</span>
<span id="cb34-10"><a href="intro.html#cb34-10" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(motor_UPDRS, <span class="fl">0.75</span>),</span>
<span id="cb34-11"><a href="intro.html#cb34-11" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(motor_UPDRS),</span>
<span id="cb34-12"><a href="intro.html#cb34-12" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(motor_UPDRS)</span>
<span id="cb34-13"><a href="intro.html#cb34-13" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb34-14"><a href="intro.html#cb34-14" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##         sex    n    media       sd mediana    RIC     Q1     Q3 minimo maximo
## 1 Masculino 3996 21.46022 7.897393  21.208 12.514 15.000 27.514 5.0377 39.511
## 2  Femenino 1867 20.92458 8.607728  20.125 14.090 13.599 27.689 6.0102 37.957</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="intro.html#cb36-1" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="intro.html#cb36-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> sex, <span class="at">y =</span> motor_UPDRS)) <span class="sc">+</span></span>
<span id="cb36-3"><a href="intro.html#cb36-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#FAD0C4&quot;</span>,</span>
<span id="cb36-4"><a href="intro.html#cb36-4" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">&quot;#C2185B&quot;</span>,</span>
<span id="cb36-5"><a href="intro.html#cb36-5" tabindex="-1"></a>               <span class="at">width =</span> <span class="fl">0.4</span>,</span>
<span id="cb36-6"><a href="intro.html#cb36-6" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&quot;#8E0038&quot;</span>) <span class="sc">+</span></span>
<span id="cb36-7"><a href="intro.html#cb36-7" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean,</span>
<span id="cb36-8"><a href="intro.html#cb36-8" tabindex="-1"></a>               <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>,</span>
<span id="cb36-9"><a href="intro.html#cb36-9" tabindex="-1"></a>               <span class="at">shape =</span> <span class="dv">18</span>,</span>
<span id="cb36-10"><a href="intro.html#cb36-10" tabindex="-1"></a>               <span class="at">size =</span> <span class="fl">3.5</span>,</span>
<span id="cb36-11"><a href="intro.html#cb36-11" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">&quot;#8E0038&quot;</span>) <span class="sc">+</span></span>
<span id="cb36-12"><a href="intro.html#cb36-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Puntuación motor UPDRS según el sexo del paciente&quot;</span>,</span>
<span id="cb36-13"><a href="intro.html#cb36-13" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb36-14"><a href="intro.html#cb36-14" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Motor UPDRS (Puntos)&quot;</span>) <span class="sc">+</span></span>
<span id="cb36-15"><a href="intro.html#cb36-15" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/boxplot-motor-sexo-1.png" alt="" width="672" /></p>
<p>Las medias son casi iguales: 21.46 puntos en hombres y 20.92 en mujeres, medio punto de diferencia frente a desviaciones estándar cercanas a 8. Ambos grupos cubren casi toda la escala y no tienen atípicos; la caja de las mujeres es un poco más ancha y empieza más abajo (Q1 de 13.6 frente a 15), es decir, hay algo más de registros con afectación leve. A simple vista no hay una diferencia clara entre sexos; la prueba formal se hace en el capítulo inferencial, por paciente.</p>
</div>
</div>
<div id="relaciones-entre-las-variables-independientes-numéricas" class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> Relaciones entre las variables independientes numéricas<a href="intro.html#relaciones-entre-las-variables-independientes-num%C3%A9ricas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="pares-seleccionados" class="section level3 hasAnchor" number="1.4.1">
<h3><span class="header-section-number">1.4.1</span> Pares seleccionados<a href="intro.html#pares-seleccionados" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="intro.html#cb37-1" tabindex="-1"></a>comparaciones <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb37-2"><a href="intro.html#cb37-2" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;test_time&quot;</span>),</span>
<span id="cb37-3"><a href="intro.html#cb37-3" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;Jitter...&quot;</span>, <span class="st">&quot;Jitter.PPQ5&quot;</span>),</span>
<span id="cb37-4"><a href="intro.html#cb37-4" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;Jitter.RAP&quot;</span>, <span class="st">&quot;Jitter.DDP&quot;</span>),</span>
<span id="cb37-5"><a href="intro.html#cb37-5" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;Shimmer.APQ3&quot;</span>, <span class="st">&quot;Shimmer.DDA&quot;</span>),</span>
<span id="cb37-6"><a href="intro.html#cb37-6" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;Shimmer&quot;</span>, <span class="st">&quot;HNR&quot;</span>),</span>
<span id="cb37-7"><a href="intro.html#cb37-7" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;RPDE&quot;</span>, <span class="st">&quot;PPE&quot;</span>)</span>
<span id="cb37-8"><a href="intro.html#cb37-8" tabindex="-1"></a>)</span>
<span id="cb37-9"><a href="intro.html#cb37-9" tabindex="-1"></a></span>
<span id="cb37-10"><a href="intro.html#cb37-10" tabindex="-1"></a><span class="cf">for</span> (comparacion <span class="cf">in</span> comparaciones) {</span>
<span id="cb37-11"><a href="intro.html#cb37-11" tabindex="-1"></a>  </span>
<span id="cb37-12"><a href="intro.html#cb37-12" tabindex="-1"></a>  variable_x <span class="ot">&lt;-</span> comparacion[<span class="dv">1</span>]</span>
<span id="cb37-13"><a href="intro.html#cb37-13" tabindex="-1"></a>  variable_y <span class="ot">&lt;-</span> comparacion[<span class="dv">2</span>]</span>
<span id="cb37-14"><a href="intro.html#cb37-14" tabindex="-1"></a>  </span>
<span id="cb37-15"><a href="intro.html#cb37-15" tabindex="-1"></a>  grafico <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb37-16"><a href="intro.html#cb37-16" tabindex="-1"></a>    data,</span>
<span id="cb37-17"><a href="intro.html#cb37-17" tabindex="-1"></a>    <span class="fu">aes</span>(</span>
<span id="cb37-18"><a href="intro.html#cb37-18" tabindex="-1"></a>      <span class="at">x =</span> .data[[variable_x]],</span>
<span id="cb37-19"><a href="intro.html#cb37-19" tabindex="-1"></a>      <span class="at">y =</span> .data[[variable_y]]</span>
<span id="cb37-20"><a href="intro.html#cb37-20" tabindex="-1"></a>    )</span>
<span id="cb37-21"><a href="intro.html#cb37-21" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb37-22"><a href="intro.html#cb37-22" tabindex="-1"></a>    <span class="fu">geom_point</span>(</span>
<span id="cb37-23"><a href="intro.html#cb37-23" tabindex="-1"></a>      <span class="at">alpha =</span> <span class="fl">0.5</span>,</span>
<span id="cb37-24"><a href="intro.html#cb37-24" tabindex="-1"></a>      <span class="at">color =</span> <span class="st">&quot;#C77D98&quot;</span></span>
<span id="cb37-25"><a href="intro.html#cb37-25" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb37-26"><a href="intro.html#cb37-26" tabindex="-1"></a>    <span class="fu">labs</span>(</span>
<span id="cb37-27"><a href="intro.html#cb37-27" tabindex="-1"></a>      <span class="at">title =</span> <span class="fu">paste</span>(variable_x, <span class="st">&quot;vs&quot;</span>, variable_y),</span>
<span id="cb37-28"><a href="intro.html#cb37-28" tabindex="-1"></a>      <span class="at">x =</span> variable_x,</span>
<span id="cb37-29"><a href="intro.html#cb37-29" tabindex="-1"></a>      <span class="at">y =</span> variable_y</span>
<span id="cb37-30"><a href="intro.html#cb37-30" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb37-31"><a href="intro.html#cb37-31" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span>
<span id="cb37-32"><a href="intro.html#cb37-32" tabindex="-1"></a>  </span>
<span id="cb37-33"><a href="intro.html#cb37-33" tabindex="-1"></a>  <span class="fu">print</span>(grafico)</span>
<span id="cb37-34"><a href="intro.html#cb37-34" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/dispersion-pares-seleccionados-1.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-pares-seleccionados-2.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-pares-seleccionados-3.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-pares-seleccionados-4.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-pares-seleccionados-5.png" alt="" width="672" /><img src="parkinson-updrs_files/figure-html/dispersion-pares-seleccionados-6.png" alt="" width="672" />
<strong><code>age</code> vs <code>test_time</code>:</strong> Muestra una distribución de datos organizada en columnas verticales definidas por la edad de cada paciente, extendiéndose de manera uniforme a lo largo del eje del tiempo de prueba entre los 0 y casi 200 días. Esta estructura confirma que los participantes de distintas edades ingresaron y completaron el estudio bajo esquemas de seguimiento similares, sin evidenciar una relación lineal o sesgo entre la edad de la persona y la duración o frecuencia de sus mediciones.</p>
<p><strong><code>Jitter...</code> vs <code>Jitter.PPQ5</code>:</strong> Presenta una relación positiva clara y directa entre ambas métricas de variación de frecuencia. La masa de datos se concentra de forma densa cerca del origen (valores menores a 0.02), mientras que a medida que aumentan los niveles de inestabilidad vocal se observa una leve dispersión progresiva de los puntos. Esto demuestra una alta correlación entre el indicador general y la evaluación en bloques de 5 periodos.</p>
<p><strong><code>Jitter.RAP</code> vs <code>Jitter.DDP</code>:</strong> Muestra una relación lineal perfecta, donde todos los datos se alinean sin desviación alguna sobre una única trayectoria recta. Jitter.RAP mide la inestabilidad rápida en la frecuencia de la voz y Jitter.DDP representa esa misma variación pero multiplicada por tres. Esto confirma que ambas variables entregan la misma información sobre el temblor vocal, por lo que existe una redundancia total y basta con conservar solo una de ellas para el análisis.</p>
<p><strong><code>Shimmer.APQ3</code> vs <code>Shimmer.DDA</code>:</strong> Al igual que el par anterior, presenta una relación lineal perfecta sin ninguna dispersión de los puntos fuera de la línea trazada. La variable DDA es exactamente el triple de APQ3, por lo que esta gráfica ratifica una colinealidad entre ambas métricas de amplitud y la conveniencia de descartar una de ellas en la fase de ingeniería de características.</p>
<p><strong><code>Shimmer</code> vs <code>HNR</code>:</strong> Muestra una fuerte relación curvilínea e inversa entre la variación de la amplitud de la voz y la relación armónico-ruido. A medida que Shimmer aumenta desde 0.02 hacia valores superiores a 0.15, la variable HNR cae de manera drástica desde niveles superiores a 30 dB hasta valores inferiores a 10 dB. La mayor concentración de observaciones se ubica en zonas de baja alteración de amplitud y alto nivel armónico, reflejando que la pérdida de estabilidad en el volumen degrada de forma directa la pureza de la señal vocal.</p>
<p><strong><code>RPDE</code> vs <code>PPE</code>:</strong> Presenta una tendencia positiva moderada con una dispersión considerable de los datos en forma de nube ascendente. A medida que la entropía de la señal (RPDE) aumenta de 0.25 a 0.75, la entropía del periodo de tono (PPE) muestra un incremento gradual en sus valores promedio, pasando de rangos cercanos a 0.1 a valores sobre 0.4. Esto demuestra que ambos problemas avanzan juntos: conforme empeora el timbre vocal, se incrementa el descontrol en la frecuencia de la voz, reflejando el deterioro del paciente desde dos ángulos distintos.</p>
</div>
<div id="matriz-de-correlaciones" class="section level3 hasAnchor" number="1.4.2">
<h3><span class="header-section-number">1.4.2</span> Matriz de correlaciones<a href="intro.html#matriz-de-correlaciones" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para ver de forma sistemática qué variables se parecen entre sí, calculamos la matriz de correlaciones de Pearson de las independientes numéricas. <code>total_UPDRS</code> queda fuera por la razón ya explicada: es una puntuación clínica que contiene a <code>motor_UPDRS</code>, no una característica de la voz.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="intro.html#cb38-1" tabindex="-1"></a>variables_independientes <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="intro.html#cb38-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric), <span class="sc">-</span>motor_UPDRS, <span class="sc">-</span>total_UPDRS)</span>
<span id="cb38-3"><a href="intro.html#cb38-3" tabindex="-1"></a></span>
<span id="cb38-4"><a href="intro.html#cb38-4" tabindex="-1"></a>matriz_correlaciones <span class="ot">&lt;-</span> <span class="fu">cor</span>(variables_independientes)</span>
<span id="cb38-5"><a href="intro.html#cb38-5" tabindex="-1"></a></span>
<span id="cb38-6"><a href="intro.html#cb38-6" tabindex="-1"></a><span class="fu">as.data.frame</span>(<span class="fu">as.table</span>(matriz_correlaciones)) <span class="sc">%&gt;%</span></span>
<span id="cb38-7"><a href="intro.html#cb38-7" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Var1, <span class="at">y =</span> Var2, <span class="at">fill =</span> Freq)) <span class="sc">+</span></span>
<span id="cb38-8"><a href="intro.html#cb38-8" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="at">color =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb38-9"><a href="intro.html#cb38-9" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(Freq, <span class="dv">2</span>)), <span class="at">size =</span> <span class="fl">2.6</span>) <span class="sc">+</span></span>
<span id="cb38-10"><a href="intro.html#cb38-10" tabindex="-1"></a>  <span class="fu">scale_fill_gradient2</span>(</span>
<span id="cb38-11"><a href="intro.html#cb38-11" tabindex="-1"></a>    <span class="at">low =</span> <span class="st">&quot;lightblue&quot;</span>, <span class="at">mid =</span> <span class="st">&quot;white&quot;</span>, <span class="at">high =</span> <span class="st">&quot;#FFB6C1&quot;</span>, <span class="at">midpoint =</span> <span class="dv">0</span>,</span>
<span id="cb38-12"><a href="intro.html#cb38-12" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>), <span class="at">name =</span> <span class="st">&quot;Correlación&quot;</span></span>
<span id="cb38-13"><a href="intro.html#cb38-13" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb38-14"><a href="intro.html#cb38-14" tabindex="-1"></a>  <span class="fu">coord_equal</span>() <span class="sc">+</span></span>
<span id="cb38-15"><a href="intro.html#cb38-15" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb38-16"><a href="intro.html#cb38-16" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Matriz de correlaciones de las variables independientes numéricas&quot;</span>,</span>
<span id="cb38-17"><a href="intro.html#cb38-17" tabindex="-1"></a>    <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb38-18"><a href="intro.html#cb38-18" tabindex="-1"></a>    <span class="at">y =</span> <span class="cn">NULL</span></span>
<span id="cb38-19"><a href="intro.html#cb38-19" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb38-20"><a href="intro.html#cb38-20" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb38-21"><a href="intro.html#cb38-21" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/matriz-correlaciones-1.png" alt="" width="1056" /></p>
<p>Lo primero que salta a la vista en la matriz son dos bloques de color intenso: las cinco medidas de Jitter se correlacionan entre sí con valores de 0.79 a 1, y las seis de Shimmer con valores de 0.89 a 1. Esto es debido a que dentro de cada familia todas las variables miden lo mismo (la variación de la frecuencia en un caso y la de la amplitud en el otro), solo que con fórmulas y escalas distintas. Incluso hay dos pares con correlación exactamente igual a 1, porque <code>Jitter.DDP</code> y <code>Shimmer.DDA</code> no son más que el triple de <code>Jitter.RAP</code> y <code>Shimmer.APQ3</code>.</p>
<p>Fuera de esos bloques las relaciones son las esperables: las dos familias se asocian entre sí de forma moderada (0.59 a 0.73), <code>NHR</code> sube y <code>HNR</code> baja cuando la voz se vuelve más inestable, <code>PPE</code> acompaña sobre todo al jitter, y <code>DFA</code>, <code>age</code> y <code>test_time</code> apenas se relacionan con el resto.</p>
<p>La conclusión es que usar las once medidas de Jitter y Shimmer a la vez sería redundante y traería problemas de multicolinealidad, así que en la ingeniería de características cada familia se resumirá en una sola variable. Antes de eso, vale la pena mirar de cerca los pares más correlacionados que todavía no se habían graficado.</p>
</div>
<div id="pares-más-correlacionados" class="section level3 hasAnchor" number="1.4.3">
<h3><span class="header-section-number">1.4.3</span> Pares más correlacionados<a href="intro.html#pares-m%C3%A1s-correlacionados" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="intro.html#cb39-1" tabindex="-1"></a>grafico_dispersion <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y, titulo) {</span>
<span id="cb39-2"><a href="intro.html#cb39-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> .data[[x]], <span class="at">y =</span> .data[[y]])) <span class="sc">+</span></span>
<span id="cb39-3"><a href="intro.html#cb39-3" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">color =</span> <span class="st">&quot;#C77D98&quot;</span>) <span class="sc">+</span></span>
<span id="cb39-4"><a href="intro.html#cb39-4" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> titulo, <span class="at">x =</span> x, <span class="at">y =</span> y) <span class="sc">+</span></span>
<span id="cb39-5"><a href="intro.html#cb39-5" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span>
<span id="cb39-6"><a href="intro.html#cb39-6" tabindex="-1"></a>}</span>
<span id="cb39-7"><a href="intro.html#cb39-7" tabindex="-1"></a>        </span>
<span id="cb39-8"><a href="intro.html#cb39-8" tabindex="-1"></a>p_cor1 <span class="ot">&lt;-</span> <span class="fu">grafico_dispersion</span>(<span class="st">&quot;Jitter...&quot;</span>, <span class="st">&quot;Jitter.RAP&quot;</span>, <span class="st">&quot;Jitter(%) y Jitter:RAP&quot;</span>)</span>
<span id="cb39-9"><a href="intro.html#cb39-9" tabindex="-1"></a>p_cor2 <span class="ot">&lt;-</span> <span class="fu">grafico_dispersion</span>(<span class="st">&quot;Jitter...&quot;</span>, <span class="st">&quot;Jitter.Abs.&quot;</span>, <span class="st">&quot;Jitter(%) y Jitter(Abs)&quot;</span>)</span>
<span id="cb39-10"><a href="intro.html#cb39-10" tabindex="-1"></a>p_cor3 <span class="ot">&lt;-</span> <span class="fu">grafico_dispersion</span>(<span class="st">&quot;Shimmer&quot;</span>, <span class="st">&quot;Shimmer.dB.&quot;</span>, <span class="st">&quot;Shimmer y Shimmer(dB)&quot;</span>)</span>
<span id="cb39-11"><a href="intro.html#cb39-11" tabindex="-1"></a>p_cor4 <span class="ot">&lt;-</span> <span class="fu">grafico_dispersion</span>(<span class="st">&quot;Shimmer&quot;</span>, <span class="st">&quot;Shimmer.APQ5&quot;</span>, <span class="st">&quot;Shimmer y Shimmer:APQ5&quot;</span>)</span>
<span id="cb39-12"><a href="intro.html#cb39-12" tabindex="-1"></a>p_cor5 <span class="ot">&lt;-</span> <span class="fu">grafico_dispersion</span>(<span class="st">&quot;Shimmer.APQ5&quot;</span>, <span class="st">&quot;Shimmer.APQ11&quot;</span>, <span class="st">&quot;Shimmer:APQ5 y Shimmer:APQ11&quot;</span>)</span>
<span id="cb39-13"><a href="intro.html#cb39-13" tabindex="-1"></a>p_cor6 <span class="ot">&lt;-</span> <span class="fu">grafico_dispersion</span>(<span class="st">&quot;Jitter.PPQ5&quot;</span>, <span class="st">&quot;NHR&quot;</span>, <span class="st">&quot;Jitter:PPQ5 y NHR&quot;</span>)</span>
<span id="cb39-14"><a href="intro.html#cb39-14" tabindex="-1"></a></span>
<span id="cb39-15"><a href="intro.html#cb39-15" tabindex="-1"></a>(p_cor1 <span class="sc">+</span> p_cor2 <span class="sc">+</span> p_cor3) <span class="sc">/</span> (p_cor4 <span class="sc">+</span> p_cor5 <span class="sc">+</span> p_cor6)</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/dispersion-pares-correlacionados-1.png" alt="" width="1152" /></p>
<p><strong><code>Jitter...</code> vs <code>Jitter.RAP</code>:</strong> Los puntos se alinean casi perfectamente (r = 0.98) y solo se abren un poco por encima de 0.03, donde hay pocos datos. Las dos miden la misma perturbación de la frecuencia entre ciclos, así que crecen casi en proporción.</p>
<p><strong><code>Jitter...</code> vs <code>Jitter.Abs.</code>:</strong> La relación es fuerte (r = 0.87), pero la nube se abre en forma de cono porque la medida absoluta depende del tono de cada voz: un mismo porcentaje de variación son más microsegundos en una voz grave que en una aguda. Dos registros (pacientes 14 y 30) con Jitter cercano a 0.1 y variación absoluta baja se salen claramente del patrón.</p>
<p><strong><code>Shimmer</code> vs <code>Shimmer.dB.</code>:</strong> Es la correlación más alta entre variables que no son múltiplos exactos (r = 0.99). La nube se curva apenas en los valores altos por la escala logarítmica de los decibelios; en la práctica, las dos dicen lo mismo.</p>
<p><strong><code>Shimmer</code> vs <code>Shimmer.APQ5</code>:</strong> Relación casi lineal (r = 0.98), con la mayoría de los registros por debajo de 0.05. Solo por encima de 0.1 se nota dispersión, porque el promedio en bloques de cinco periodos suaviza los cambios más bruscos.</p>
<p><strong><code>Shimmer.APQ5</code> vs <code>Shimmer.APQ11</code>:</strong> Es el par más disperso de la familia (r = 0.94). En las grabaciones más inestables <code>Shimmer.APQ11</code> tiende a quedar por encima de <code>Shimmer.APQ5</code>, y la nube se abre hacia arriba en la parte derecha.</p>
<p><strong><code>Jitter.PPQ5</code> vs <code>NHR</code>:</strong> Es la relación más fuerte entre una medida de perturbación y una de ruido (r = 0.86). En la gran mayoría de registros, con <code>Jitter.PPQ5</code> por debajo de 0.01, el NHR se queda casi siempre bajo 0.1; en los pocos con Jitter alto el ruido se dispara hasta 0.75. Más inestabilidad suele venir con más ruido, aunque no tan de la mano como dentro de cada familia.</p>
</div>
</div>
<div id="ingeniería-de-características" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> Ingeniería de características<a href="intro.html#ingenier%C3%ADa-de-caracter%C3%ADsticas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="construcción-de-los-índices" class="section level3 hasAnchor" number="1.5.1">
<h3><span class="header-section-number">1.5.1</span> Construcción de los índices<a href="intro.html#construcci%C3%B3n-de-los-%C3%ADndices" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Cada familia mide un mismo fenómeno con fórmulas y unidades distintas: <code>Jitter...</code> está en porcentaje, <code>Jitter.Abs.</code> en segundos, <code>Shimmer.dB.</code> en decibelios. Como no se pueden promediar directamente, estandarizamos cada variable (restamos su media y dividimos por su desviación estándar) y promediamos los valores estandarizados de cada familia. Así nacen <code>indice_jitter</code> e <code>indice_shimmer</code>: un valor de 0 es una grabación con perturbación promedio, los positivos indican más inestabilidad que el promedio y los negativos menos, medido en desviaciones estándar.</p>
<p>Dejamos fuera <code>Jitter.DDP</code> y <code>Shimmer.DDA</code>, que son el triple exacto de <code>Jitter.RAP</code> y <code>Shimmer.APQ3</code>: estandarizadas darían los mismos valores y contarían dos veces. <code>NHR</code>, <code>HNR</code>, <code>RPDE</code>, <code>DFA</code> y <code>PPE</code> se quedan como están, porque cada una mide algo distinto (ruido, complejidad, escalado fractal, entropía) y sus correlaciones entre sí no pasan de 0.76; <code>age</code> y <code>test_time</code> también, ya que no se correlacionan con nada.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="intro.html#cb40-1" tabindex="-1"></a>estandarizar <span class="ot">&lt;-</span> <span class="cf">function</span>(x) (x <span class="sc">-</span> <span class="fu">mean</span>(x)) <span class="sc">/</span> <span class="fu">sd</span>(x)</span>
<span id="cb40-2"><a href="intro.html#cb40-2" tabindex="-1"></a></span>
<span id="cb40-3"><a href="intro.html#cb40-3" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb40-4"><a href="intro.html#cb40-4" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb40-5"><a href="intro.html#cb40-5" tabindex="-1"></a>    <span class="at">indice_jitter =</span> (<span class="fu">estandarizar</span>(Jitter...) <span class="sc">+</span> <span class="fu">estandarizar</span>(Jitter.Abs.) <span class="sc">+</span></span>
<span id="cb40-6"><a href="intro.html#cb40-6" tabindex="-1"></a>                       <span class="fu">estandarizar</span>(Jitter.RAP) <span class="sc">+</span> <span class="fu">estandarizar</span>(Jitter.PPQ5)) <span class="sc">/</span> <span class="dv">4</span>,</span>
<span id="cb40-7"><a href="intro.html#cb40-7" tabindex="-1"></a>    <span class="at">indice_shimmer =</span> (<span class="fu">estandarizar</span>(Shimmer) <span class="sc">+</span> <span class="fu">estandarizar</span>(Shimmer.dB.) <span class="sc">+</span></span>
<span id="cb40-8"><a href="intro.html#cb40-8" tabindex="-1"></a>                        <span class="fu">estandarizar</span>(Shimmer.APQ3) <span class="sc">+</span> <span class="fu">estandarizar</span>(Shimmer.APQ5) <span class="sc">+</span></span>
<span id="cb40-9"><a href="intro.html#cb40-9" tabindex="-1"></a>                        <span class="fu">estandarizar</span>(Shimmer.APQ11)) <span class="sc">/</span> <span class="dv">5</span></span>
<span id="cb40-10"><a href="intro.html#cb40-10" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<div id="verificación-de-los-índices" class="section level3 hasAnchor" number="1.5.2">
<h3><span class="header-section-number">1.5.2</span> Verificación de los índices<a href="intro.html#verificaci%C3%B3n-de-los-%C3%ADndices" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para comprobar que los índices no pierden información, los correlacionamos con cada variable original (incluidas las dos excluidas) y entre sí.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="intro.html#cb41-1" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="intro.html#cb41-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">c</span>(Jitter..., Jitter.Abs., Jitter.RAP, Jitter.PPQ5, Jitter.DDP),</span>
<span id="cb41-3"><a href="intro.html#cb41-3" tabindex="-1"></a>                   <span class="sc">~</span> <span class="fu">round</span>(<span class="fu">cor</span>(.x, indice_jitter), <span class="dv">3</span>)))</span></code></pre></div>
<pre><code>##   Jitter... Jitter.Abs. Jitter.RAP Jitter.PPQ5 Jitter.DDP
## 1     0.992        0.91      0.981       0.963      0.981</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="intro.html#cb43-1" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="intro.html#cb43-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">c</span>(Shimmer, Shimmer.dB., Shimmer.APQ3, Shimmer.APQ5,</span>
<span id="cb43-3"><a href="intro.html#cb43-3" tabindex="-1"></a>                     Shimmer.APQ11, Shimmer.DDA),</span>
<span id="cb43-4"><a href="intro.html#cb43-4" tabindex="-1"></a>                   <span class="sc">~</span> <span class="fu">round</span>(<span class="fu">cor</span>(.x, indice_shimmer), <span class="dv">3</span>)))</span></code></pre></div>
<pre><code>##   Shimmer Shimmer.dB. Shimmer.APQ3 Shimmer.APQ5 Shimmer.APQ11 Shimmer.DDA
## 1   0.996       0.992        0.977         0.99         0.956       0.977</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="intro.html#cb45-1" tabindex="-1"></a><span class="fu">cor</span>(data<span class="sc">$</span>indice_jitter, data<span class="sc">$</span>indice_shimmer)</span></code></pre></div>
<pre><code>## [1] 0.7089249</code></pre>
<p>El índice de jitter se correlaciona entre 0.91 y 0.99 con sus cinco variables, y el de shimmer entre 0.96 y 1 con sus seis: cada uno reproduce casi por completo a su familia. Entre ellos la correlación es 0.71, alta pero no tanto como para fundirlos: las voces inestables suelen serlo en frecuencia y amplitud a la vez, pero cada índice conserva información propia.</p>
</div>
<div id="descripción-de-los-índices" class="section level3 hasAnchor" number="1.5.3">
<h3><span class="header-section-number">1.5.3</span> Descripción de los índices<a href="intro.html#descripci%C3%B3n-de-los-%C3%ADndices" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="intro.html#cb47-1" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb47-2"><a href="intro.html#cb47-2" tabindex="-1"></a>  <span class="fu">select</span>(indice_jitter, indice_shimmer) <span class="sc">%&gt;%</span></span>
<span id="cb47-3"><a href="intro.html#cb47-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb47-4"><a href="intro.html#cb47-4" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb47-5"><a href="intro.html#cb47-5" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">&quot;variable&quot;</span>,</span>
<span id="cb47-6"><a href="intro.html#cb47-6" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">&quot;valor&quot;</span></span>
<span id="cb47-7"><a href="intro.html#cb47-7" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb47-8"><a href="intro.html#cb47-8" tabindex="-1"></a>  <span class="fu">group_by</span>(variable) <span class="sc">%&gt;%</span></span>
<span id="cb47-9"><a href="intro.html#cb47-9" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb47-10"><a href="intro.html#cb47-10" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(valor)),</span>
<span id="cb47-11"><a href="intro.html#cb47-11" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(valor),</span>
<span id="cb47-12"><a href="intro.html#cb47-12" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(valor),</span>
<span id="cb47-13"><a href="intro.html#cb47-13" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(valor),</span>
<span id="cb47-14"><a href="intro.html#cb47-14" tabindex="-1"></a>    <span class="at">RIC =</span> <span class="fu">IQR</span>(valor),</span>
<span id="cb47-15"><a href="intro.html#cb47-15" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(valor, <span class="fl">0.25</span>),</span>
<span id="cb47-16"><a href="intro.html#cb47-16" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(valor, <span class="fl">0.75</span>),</span>
<span id="cb47-17"><a href="intro.html#cb47-17" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(valor),</span>
<span id="cb47-18"><a href="intro.html#cb47-18" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(valor),</span>
<span id="cb47-19"><a href="intro.html#cb47-19" tabindex="-1"></a>    <span class="at">asimetria =</span> <span class="fu">skewness</span>(valor),</span>
<span id="cb47-20"><a href="intro.html#cb47-20" tabindex="-1"></a>    <span class="at">curtosis =</span> <span class="fu">kurtosis</span>(valor)</span>
<span id="cb47-21"><a href="intro.html#cb47-21" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb47-22"><a href="intro.html#cb47-22" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="sc">-</span><span class="fu">c</span>(variable, n), <span class="sc">~</span> <span class="fu">round</span>(.x, <span class="dv">3</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb47-23"><a href="intro.html#cb47-23" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##         variable    n media    sd mediana   RIC     Q1    Q3 minimo maximo
## 1  indice_jitter 5863     0 0.962  -0.225 0.578 -0.459 0.119 -0.920 13.354
## 2 indice_shimmer 5863     0 0.982  -0.247 0.818 -0.580 0.238 -1.191  8.635
##   asimetria curtosis
## 1     5.613   52.085
## 2     3.171   17.133</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="intro.html#cb49-1" tabindex="-1"></a>datos_caracteristicas <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb49-2"><a href="intro.html#cb49-2" tabindex="-1"></a>  <span class="fu">select</span>(indice_jitter, indice_shimmer) <span class="sc">%&gt;%</span></span>
<span id="cb49-3"><a href="intro.html#cb49-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb49-4"><a href="intro.html#cb49-4" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb49-5"><a href="intro.html#cb49-5" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">&quot;variable&quot;</span>,</span>
<span id="cb49-6"><a href="intro.html#cb49-6" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">&quot;valor&quot;</span></span>
<span id="cb49-7"><a href="intro.html#cb49-7" tabindex="-1"></a>  )</span>
<span id="cb49-8"><a href="intro.html#cb49-8" tabindex="-1"></a></span>
<span id="cb49-9"><a href="intro.html#cb49-9" tabindex="-1"></a>p_hist_caracteristicas <span class="ot">&lt;-</span> datos_caracteristicas <span class="sc">%&gt;%</span></span>
<span id="cb49-10"><a href="intro.html#cb49-10" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> valor)) <span class="sc">+</span></span>
<span id="cb49-11"><a href="intro.html#cb49-11" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">40</span>, <span class="at">fill =</span> <span class="st">&quot;#FAD0C4&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#E8A598&quot;</span>) <span class="sc">+</span></span>
<span id="cb49-12"><a href="intro.html#cb49-12" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> variable, <span class="at">scales =</span> <span class="st">&quot;free&quot;</span>, <span class="at">ncol =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb49-13"><a href="intro.html#cb49-13" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribución de los índices creados&quot;</span>, <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">+</span></span>
<span id="cb49-14"><a href="intro.html#cb49-14" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb49-15"><a href="intro.html#cb49-15" tabindex="-1"></a></span>
<span id="cb49-16"><a href="intro.html#cb49-16" tabindex="-1"></a>p_box_caracteristicas <span class="ot">&lt;-</span> datos_caracteristicas <span class="sc">%&gt;%</span></span>
<span id="cb49-17"><a href="intro.html#cb49-17" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> variable, <span class="at">y =</span> valor)) <span class="sc">+</span></span>
<span id="cb49-18"><a href="intro.html#cb49-18" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#FAD0C4&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#C2185B&quot;</span>,</span>
<span id="cb49-19"><a href="intro.html#cb49-19" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&quot;#8E0038&quot;</span>, <span class="at">outlier.alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb49-20"><a href="intro.html#cb49-20" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&quot;#8E0038&quot;</span>) <span class="sc">+</span></span>
<span id="cb49-21"><a href="intro.html#cb49-21" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> variable, <span class="at">scales =</span> <span class="st">&quot;free&quot;</span>, <span class="at">ncol =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb49-22"><a href="intro.html#cb49-22" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Valores atípicos de los índices creados&quot;</span>, <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb49-23"><a href="intro.html#cb49-23" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb49-24"><a href="intro.html#cb49-24" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(), <span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>())</span>
<span id="cb49-25"><a href="intro.html#cb49-25" tabindex="-1"></a></span>
<span id="cb49-26"><a href="intro.html#cb49-26" tabindex="-1"></a>p_hist_caracteristicas <span class="sc">+</span> p_box_caracteristicas</span></code></pre></div>
<p><img src="parkinson-updrs_files/figure-html/graficos-caracteristicas-1.png" alt="" width="1152" /></p>
<p>Para cuantificar lo que muestran los boxplots, contamos los atípicos con la regla de 1.5 veces el rango intercuartílico y calculamos los percentiles 90 y 99 de cada índice:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="intro.html#cb50-1" tabindex="-1"></a>datos_caracteristicas <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="intro.html#cb50-2" tabindex="-1"></a>  <span class="fu">group_by</span>(variable) <span class="sc">%&gt;%</span></span>
<span id="cb50-3"><a href="intro.html#cb50-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb50-4"><a href="intro.html#cb50-4" tabindex="-1"></a>    <span class="at">limite_superior =</span> <span class="fu">quantile</span>(valor, <span class="fl">0.75</span>) <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> <span class="fu">IQR</span>(valor),</span>
<span id="cb50-5"><a href="intro.html#cb50-5" tabindex="-1"></a>    <span class="at">atipicos_superiores =</span> <span class="fu">sum</span>(valor <span class="sc">&gt;</span> limite_superior),</span>
<span id="cb50-6"><a href="intro.html#cb50-6" tabindex="-1"></a>    <span class="at">porcentaje =</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">mean</span>(valor <span class="sc">&gt;</span> limite_superior), <span class="dv">1</span>),</span>
<span id="cb50-7"><a href="intro.html#cb50-7" tabindex="-1"></a>    <span class="at">atipicos_inferiores =</span> <span class="fu">sum</span>(valor <span class="sc">&lt;</span> <span class="fu">quantile</span>(valor, <span class="fl">0.25</span>) <span class="sc">-</span> <span class="fl">1.5</span> <span class="sc">*</span> <span class="fu">IQR</span>(valor)),</span>
<span id="cb50-8"><a href="intro.html#cb50-8" tabindex="-1"></a>    <span class="at">p90 =</span> <span class="fu">quantile</span>(valor, <span class="fl">0.90</span>),</span>
<span id="cb50-9"><a href="intro.html#cb50-9" tabindex="-1"></a>    <span class="at">p99 =</span> <span class="fu">quantile</span>(valor, <span class="fl">0.99</span>)</span>
<span id="cb50-10"><a href="intro.html#cb50-10" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb50-11"><a href="intro.html#cb50-11" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">round</span>(.x, <span class="dv">2</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb50-12"><a href="intro.html#cb50-12" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##         variable limite_superior atipicos_superiores porcentaje
## 1  indice_jitter            0.99                 416        7.1
## 2 indice_shimmer            1.46                 325        5.5
##   atipicos_inferiores  p90  p99
## 1                   0 0.67 4.41
## 2                   0 0.89 4.68</code></pre>
<p><strong>Índice de jitter.</strong> Por construcción la media es 0 (desviación estándar 0.96). La mediana es -0.23 y la mitad central de las grabaciones cabe entre -0.46 y 0.12, un intervalo de apenas media desviación estándar. Pero mientras el mínimo es -0.92, el máximo llega a 13.35: la cola derecha es larguísima, y eso se refleja en una asimetría de 5.61 y una curtosis de 52. El índice hereda la forma de las medidas de Jitter originales, que ya eran muy asimétricas.</p>
<p>En el histograma casi todo se concentra entre -1 y 0.5 y luego sigue una cola delgada hasta 13. El boxplot lo confirma: caja compacta, ningún atípico por abajo y 416 registros (7.1 %) por encima del bigote superior de 0.99, en una cadena que llega a 13 desviaciones estándar. El 90 % de las grabaciones está por debajo de 0.67 y el 99 % por debajo de 4.41: la inestabilidad severa de la frecuencia es cosa de un grupo pequeño de grabaciones muy alejadas del resto.</p>
<p><strong>Índice de shimmer.</strong> También tiene media 0 (desviación estándar 0.98) y mediana -0.25. El 50 % central va de -0.58 a 0.24, un rango intercuartílico de 0.82, más amplio que el del jitter: la variación de amplitud es más heterogénea entre grabaciones que la de frecuencia. Los valores van de -1.19 a 8.64, y la asimetría (3.17) y la curtosis (17.13), aunque altas, son bastante menores que las del jitter.</p>
<p>El histograma tiene su pico entre -0.75 y 0, baja de forma gradual hasta 2.5 y deja una cola dispersa hasta 8.6. En el boxplot la caja es algo más ancha que la del jitter, sin atípicos por abajo y con 325 registros (5.5 %) por encima de 1.46. El 90 % de las grabaciones queda por debajo de 0.89 y el 99 % por debajo de 4.68: de nuevo, las alteraciones graves son pocas y están muy separadas del resto.</p>
</div>
<div id="relación-con-la-variable-respuesta" class="section level3 hasAnchor" number="1.5.4">
<h3><span class="header-section-number">1.5.4</span> Relación con la variable respuesta<a href="intro.html#relaci%C3%B3n-con-la-variable-respuesta" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Por último, vemos cómo se relacionan con la respuesta las variables que quedan tras la ingeniería de características.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="intro.html#cb52-1" tabindex="-1"></a>variables_finales <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;test_time&quot;</span>, <span class="st">&quot;indice_jitter&quot;</span>, <span class="st">&quot;indice_shimmer&quot;</span>,</span>
<span id="cb52-2"><a href="intro.html#cb52-2" tabindex="-1"></a>                       <span class="st">&quot;NHR&quot;</span>, <span class="st">&quot;HNR&quot;</span>, <span class="st">&quot;RPDE&quot;</span>, <span class="st">&quot;DFA&quot;</span>, <span class="st">&quot;PPE&quot;</span>)</span>
<span id="cb52-3"><a href="intro.html#cb52-3" tabindex="-1"></a></span>
<span id="cb52-4"><a href="intro.html#cb52-4" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb52-5"><a href="intro.html#cb52-5" tabindex="-1"></a>  <span class="fu">select</span>(motor_UPDRS, <span class="fu">all_of</span>(variables_finales)) <span class="sc">%&gt;%</span></span>
<span id="cb52-6"><a href="intro.html#cb52-6" tabindex="-1"></a>  <span class="fu">cor</span>() <span class="sc">%&gt;%</span></span>
<span id="cb52-7"><a href="intro.html#cb52-7" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb52-8"><a href="intro.html#cb52-8" tabindex="-1"></a>  <span class="fu">rownames_to_column</span>(<span class="st">&quot;variable&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb52-9"><a href="intro.html#cb52-9" tabindex="-1"></a>  <span class="fu">select</span>(variable, <span class="at">correlacion =</span> motor_UPDRS) <span class="sc">%&gt;%</span></span>
<span id="cb52-10"><a href="intro.html#cb52-10" tabindex="-1"></a>  <span class="fu">filter</span>(variable <span class="sc">!=</span> <span class="st">&quot;motor_UPDRS&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb52-11"><a href="intro.html#cb52-11" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(correlacion)))</span></code></pre></div>
<pre><code>##         variable correlacion
## 1            age  0.27446940
## 2            PPE  0.16333440
## 3            HNR -0.15734364
## 4           RPDE  0.12844355
## 5            DFA -0.11632962
## 6 indice_shimmer  0.10741041
## 7            NHR  0.07527343
## 8  indice_jitter  0.07446472
## 9      test_time  0.06963928</code></pre>
<p>Las 16 medidas acústicas quedaron en 7 (los dos índices más <code>NHR</code>, <code>HNR</code>, <code>RPDE</code>, <code>DFA</code> y <code>PPE</code>) sin perder información apreciable. Ninguna se asocia con fuerza a <code>motor_UPDRS</code>: la mayor correlación es la de <code>age</code> (0.27), seguida de <code>PPE</code> (0.16), <code>HNR</code> (-0.16), <code>RPDE</code> (0.13) y <code>DFA</code> (-0.12); los índices de shimmer (0.11) y jitter (0.07) quedan aún más abajo. Es lo mismo que mostraban los gráficos de dispersión: registro a registro, la relación entre la voz y la severidad motora es débil. Por eso en la parte inferencial tiene más sentido comparar la severidad entre grupos de pacientes (sexo, edad, nivel de inestabilidad vocal) que apoyarse en estas correlaciones.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="objetivos-especificos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="inferencial.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/DiegoxorG/libro_met_est/edit/main/01-intro.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
